### ISSUE TITLE
Update Linux build notes

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#1]
Scanning through the Linux build notes, I noticed that a lot of the package info for Arch Linux was way out of date. Fixed that (at least partially), but testing is required to figure out whether the listed dependencies are actually correct. The Ubuntu / Debian package list is probably similarly outdated.

Also, the "i586-mingw32" bits look _highly_ suspect. I'm pretty sure we're not targeting Pentiums anymore.

On a related note, @mb14, feel free to tear up the Windows build notes where prudent.

**Comment by ghost** [comment]
Good work!

I added some notes in italics to the Windows build notes. I hardly feel like I am a qualified expert on building it for Windows having only built the 32-bit version on one machine using one version of msys/autotools/sdl, all of which I already had installed. But I will, at some point, check that the links in the build notes are up to date. As more people try building on Windows we can update them as needed.
