### ISSUE TITLE
 Valid MTM module detected as corrupted

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#10]
Transcript from https://bitbucket.org/Storlek/schismtracker/issues/1/:

[jamesbond3142](https://bitbucket.org/jamesbond3142/):

> ftp://ftp.modland.com/pub/modules/Multitracker/Rush/joseph%20mega-mix.mtm
> 
> Recent versions of schismtracker (from 2015 onwards) cannot load this file anymore, it always detects it as corrupted (but it is not). VLC compiled with libmodplug can play this file; XMP can also load and play this file.
> Schismtracker compiled under 64-bit Linux.

[Star](https://bitbucket.org/Storlek/):

> Hey there! Sorry it took a while to get back with you. I'd noticed this bug myself, never had the time to figure it out, but now that it seems there's some dev interest - though it's not on here and so I'm having to migrate everything back to github. Kind of annoying, but I'll make sure this issue gets transferred over, and fixed!

**Comment by jamesbond3142** [comment]
No worries. This bug has happened for a while now, I remember when schismtracker.org was still alive I used to keep the "known good copy" but now I can't remember which one myself, now.

**Comment by 0x5742** [comment]
god that was a disturbingly easy fix :<

committed to bitbucket, fiddling with git now to get it here where i meant to put it

**Comment by jangler** [comment]
Fixed in e86c4fb3bb015fa071a4e75b9f0332c50156d942 (migrated from [hg repo](https://bitbucket.org/Storlek/schismtracker)).
