### ISSUE TITLE
MIDI keyjazzing doesn't work if sample isn't assigned to note

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#100]
Obviously MIDI output doesn't rely on sample assignment since MIDI is configured per instrument; you should be able to use Schism as a MIDI controller without any samples at all.

**Comment by esaruoho** [comment]
Ok, so this is the solution, I just gotta set a sample into the Midi Instrument channel and the midi notes will be output? Thanks for the workaround! Would be neat, of course, to be able to midikeyjazz without having to have samples, @jangler.
 :)

**Comment by jangler** [comment]
Yeah, it's dumb. I guess that's why you weren't able to keyjazz? I'm going to self-assign this because it is dumb.

**Comment by esaruoho** [comment]
Hi, one thing, I noticed that when using an Instrument with Midi and a sample in it, even if I set the sample volume to 0 (F3), the sample would play (when in F4 and keyjazzing via midi) Then when I set the sample Global Volume to 0 (F3), then the sample wouldn't play.

**Comment by esaruoho** [comment]
Yeah @jangler the minute I read this "midi keyjazz won't work unless if there's a sample assigned" a lightbulb went off on top of my head and I went and loaded a sample in and midi-keyjazz worked. Nice!

**Comment by esaruoho** [comment]
@jangler hi, is there something i can do to help with this one? like, i'm not a coder, but is there some data i can provide or something?

**Comment by jangler** [comment]
Nah, it *should* be pretty straightforward to code once I have time.

**Comment by jangler** [comment]
(Mostly notes to self)

This seems to be related to the `MIDI_LIKE_TRACKER` option; see [line 381 of schism/audio_playback.c](https://github.com/schismtracker/schismtracker/blob/master/schism/audio_playback.c#L330-L389). I don't think that's the whole story, though.

The real problem is probably in [`_schism_midi_out_note`](https://github.com/schismtracker/schismtracker/blob/master/schism/audio_playback.c#L1026) when `m_note` has a value of `NOTE_NONE`--which will happen when an instrument doesn't have notes mapped to samples.

**Comment by esaruoho** [comment]
@jangler okay, really looking forward to this - if you get the time, i'd be delighted to try a branch.
i just need to probably create a script for building from the newest..

**Comment by jangler** [comment]
Want to check out the `midi-keyjazz` branch? I think it's fixed.

**Comment by esaruoho** [comment]
@jangler `midi-keyjazz` makes it possible for me to have a no-sample instrument, with midi going out when i keyjazz. seems like you fixed it!

**Comment by jangler** [comment]
OK, fixed in 1f1be65 (merged into master).
