### ISSUE TITLE
Using diskwriter changes playback until song is reloaded

### ISSUE THREAD

**Issue by zoikkis** [schismtracker/schismtracker#102]
For some reason, after using diskwriter for export module or CTRL-O / CTRL-B to resample, the playback changes so that the samples, or instruments, sound different. This also affects the actual rendered sample. Re-initializing soundcard with CTRL-I doesn't change it back. Only reloading the song makes the playback normal again.

I had a sinewave based single-cycle instrument with volume modulation that sounded smooth with a build that was based on current master and with increased "volume ramp" but after rendering there was lots of clicks with both rendered sample and the playback of song. After re-loading song the playback was back to normal but the rendered sample naturally remained with clicks.

I then thought that maybe problem was introduced with this new "customised build" so I loaded up 20170413 and tried rendering again. This time the sinewave instrument that had a lot of crackles with 20170413 version, actually rendered out very smoothly and also crackles disappeared from playback, until I reloaded the song when crackles came back.

Same behaviour with two different computers (Windows 7 and Windows 8.1)

In config, I have the following settings, excluding MIDI and some other settings:
[Audio]
sample_rate=44100
bits=16
channels=2
buffer_size=512
[Mixer Settings]
channel_limit=128
interpolation_mode=1
no_ramping=0
surround_effect=1
[EQ Low Band]
freq=14
gain=0
[EQ Med Low Band]
freq=16
gain=0
[EQ Med High Band]
freq=96
gain=0
[EQ High Band]
freq=127
gain=0
[Video]
driver=sdl
fullscreen=0
mouse_cursor=0
lazy_redraw=0
gl_bilinear=0
[General]
key_repeat_delay=125
key_repeat_rate=25
vis_style=1
time_display=1
classic_mode=0
make_backups=1
numbered_backups=0
accidentals_as_flats=0
meta_is_ctrl=0
altgr_is_alt=1
midi_like_tracker=0
stop_on_load=1
palette=-1
palette_cur=...ULGmeYuumg.KhzKyyUj257P.5SAzzzqus4cczzELFECBA
[Directories]
module_pattern=*.it\073 *.xm\073 *.s3m\073 *.mtm\073 *.669\073 *.mod\073 *.mdl\073 *.mt2\073 *.stm\073 *.far\073 *.ult\073 *.med\073 *.ptm\073 *.okt\073 *.amf\073 *.dmf\073 *.imf\073 *.sfx\073 *.mus
export_pattern=*.wav\073 *.aiff\073 *.aif
sort_with=strcasecmp
[Info Page]
layout=samples 19 global 3 track24 15
[Pattern Editor]
link_effect_column=0
draw_divisions=1
centralise_cursor=1
highlight_current_row=1
edit_copy_mask=7
volume_percent=100
fast_volume_percent=67
fast_volume_mode=0
keyjazz_noteoff=1
keyjazz_write_noteoff=0
keyjazz_repeat=1
mask_copy_search_mode=0
invert_home_end=1
crayola_mode=0
track_view_scheme=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
channel_multi=----------------------------------------------------------------
[Diskwriter]
rate=44100
bits=16
channels=2

**Comment by jangler** [comment]
Weird; haven't looked into this yet but I'll give it a shot. Could you provide the module file that you're noticed the problem with?

**Comment by zoikkis** [comment]
You can find sinetest.it from the following link:

https://drive.google.com/drive/folders/0B3hbQj3jc0eiUGd1REszMUE0Zk0?usp=sharing

First pattern plays the instrument, which has lots of crackles with 20170413. Second pattern plays back sample rendered with 20170413, which in this case sounds smoother. Third pattern plays back sample that was rendered with master build and added volume ramping. Instrument has lost a lot from its transients(slow attack) and some weird snapping occurs towards the end of sample.

**Comment by zoikkis** [comment]
Did some more testing. If you have "Ramp volume at start of sample" disabled from Preferences page, exporting doesn't have any effect on playback or rendered file. So it seems clear that whenever export function is used, some additional volume ramping is added both to the rendered file and to any playback that happens after the rendering, if ramp volume is enabled. It is only resetted when reloading a song.

**Comment by jangler** [comment]
Thank you! This is good info to have.

**Comment by alpharisc** [comment]
Hello,

I joined up just to have a discussion about this very issue. I used Impulse Tracker from 1995 until around 2000 and purchased the Stereo Disk writer. I used it with the GUSMAX.MMX/SB16.MMX driver and later the ITVSOUND.MMX. I have noticed that there is a lot of static on the volume envelopes in general and I do not remember them being there with the MMX drivers (during real-time playback) and they are certainly not there with the WAV driver (as I can still use this via DosBox). I have made a small IT project with a sinewave playing a tune using NNA with a notefade of 255 and a sustain point at max volume 2 ticks across, during regular playback in Schism this sounds extremely static like, example below.

https://soundcloud.com/alpharisc/sine-test/s-un1IE

Here is the sound test.
1st part of the clip is playback in Schism Tracker before using the export to WAV function
2nd part of the clip is the playback in Schism Tracker after using the export to WAV function
3rd part of the clip is the exported to WAV from Schism Tracker
4th part is the exported WAV with Impulse Tracker WAV driver

I think the build of Impulse Tracker I am using is a beta as well as it is different to the last one that was released to the public, I do not believe this has any impact on the exporting of the file.

Glad to see people are still interested in Impulse Tracker, Schism Tracker is absolutely wonderful, hope that we can get the playback sounding similar to the Impulse Tracker WAV driver!

Cheers

**Comment by jangler** [comment]
Yeah, that's no good. The fact that using the export function changes playback is a little concerning; possibly some flags get set when the export starts and aren't reset when export it finished.

**Comment by jangler** [comment]
Well, I finally fixed this, almost two years later. From the looks of the code, this also affected equalizer quality, although I never use EQ settings and don't know if I'd be able to tell anyway. This probably warrants a new release immediately since it's such a horrible bug.
