### ISSUE TITLE
script plugins support

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#105]
would be great if schismtracker could support script plugin support, in languages like Lua, Python, etc. - there we could create our own plugins, for processing information, for import/export, etc.

**Comment by jangler** [comment]
If anything, it would be Lua, but this is a pretty big feature and one that I think is far outside the scope of what Schism Tracker is intended to provide. I'm just going to close this since I think realistically it won't happen unless an ambitious developer takes the initiative.
