### ISSUE TITLE
recording from virtual keyboard using our text keyboard

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#106]
would be great having something like this: https://guitarsix.com/play/piano

**Comment by jangler** [comment]
Can you elaborate? I don't understand exactly what you're requesting.

**Comment by zoikkis** [comment]
Isn't that exactly how Schismtracker is currently used, using text keyboard as virtual keys :)

**Comment by jangler** [comment]
Still not sure what this request is and it hasn't been clarified in six months, so I'm going to close it. If you want to enter note data via a virtual keyboard that you click with your mouse, I think you can find a MIDI solution for that.

**Comment by esaruoho** [comment]
@nitrofurano what did you actually mean by this? i mean, did you want schismtracker to have a synthesizer of it's own that is played, instead of samples and midi?
