### ISSUE TITLE
palettes from /usr/share/schism/palettes/ and ~/.local/share/schism/palettes/ instead from ./schism/palettes.c

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#107]
would be great if the palettes could be stored in independent files, so we could create and share our own custom palettes more easily

**Comment by jangler** [comment]
It's actually even easier than that; a palette is stored as a string in the config file in the `palette_cur` variable under `[General]`. In my config:

    palette_cur=...ULGh_Tuumg.KzzKGaHI257K.5SADbSruscccY4KLFECBA
