### ISSUE TITLE
Xircon IRC highlight interfering with Schism

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#11]
Abridged IRC log:

> <shawn> there's also a bug where schism will hang if someone nick highlights me in irc...this one isn't as detrimental, but its still a big bug because when you're tracking and someone says your name on irc, it doesn't fully take away functionality, it disables (or better yet, recognizes it as your shift key being held) output so that if you hit any function keys while tracking, it just disables the channel youre listening to
> <jangler> what client?
> <shawn> well the irc one, i use xircon...so when someone says my name, it makes the num lock blink
> <shawn> something i just did has locked the + and - keypad in the f3 screen..i dunno if its related to xircon interfering or what

**Comment by jangler** [comment]
Reading this again, this sounds more like caps lock _and_ num lock?? Someone who has Windows and a keyboard that actually has lights for this stuff should check this out.

**Comment by 0x5742** [comment]
to be honest I'm just surprised anyone uses xircon in this day and age, it was a dead project even back when I used it ages ago. I don't remember it ever blinking keyboard lights though?

**Comment by jangler** [comment]
Yeah, I'm just going to close this. I don't think anyone else cares and I don't think it's worth spending the time to test. Maybe it was even magically fixed between 2012 and now.
