### ISSUE TITLE
Crash when trying to open this file

### ISSUE THREAD

**Issue by HybridDog** [schismtracker/schismtracker#117]
I've found some file which claims to be an Amiga-SoundTracker-Audio file. When opening the file with schismtracker, it crashes instead of giving error messages.
The file, gdb and valgrind output are in this archive:
![files zip](https://user-images.githubusercontent.com/3192173/28239298-86bbe08a-6969-11e7-8a13-fff4f75cc8ed.png)

**Comment by sagamusix** [comment]
Should be fixed through cad65eeeb5b8bbcf993c299afed54826790b7e07

**Comment by HybridDog** [comment]
It doesn't crash, thanks.
![2017-07-16-140536_642x430_scrot](https://user-images.githubusercontent.com/3192173/28247411-26f106ae-6a30-11e7-9c39-37c92587f13f.png)
