### ISSUE TITLE
Add support for Modplug engine's oversampling setting to configuration

### ISSUE THREAD

**Issue by strongholdmedia** [schismtracker/schismtracker#119]
I have a few "toy"/test projects using "high" sample rate samples (that is, 44100), and I can definitely hear aliasing at some frequencies with some samples.

I also found that - among others - OpenMPT's `modplug.h` has a setting:
`	MODPLUG_ENABLE_OVERSAMPLING     = 1 << 0,  /* Enable oversampling (*highly* recommended) */`in `_ModPlug_Flags`.

It would be nice, if this be user-configurable in config (unless I'm missing something and this is used and also on by default, in which case it needs a more thorough re-vamping, please state if so, will then try to find some kind of solution for that).

Also, if already there, it would be nice to have `_ModPlug_ResamplingMode` configurable too, again only if the default is not `MODPLUG_RESAMPLE_FIR     = 3   /* 8-tap fir filter (extremely high quality) */`.

**Comment by jangler** [comment]
The default mixing mode in Schism Tracker, as it was in Impulse Tracker, is linear interpolation. You can change the mixing mode to an 8-tap FIR filter, as OpenMPT uses by default, using the Preferences (Shift-F5) screen.

Does that address your problem? I'm not exactly sure what OpenMPT's oversampling does compared to what Schism does.

**Comment by strongholdmedia** [comment]
Thanks for letting me know, I was not aware of this setting. I will listen in some minutes and will let you know if that "solves" the issue.

**Comment by strongholdmedia** [comment]
Thanks, even the "Cubic Spline" setting solves my problem perfectly, so this is a non-issue.
I still do reference #37 as I totally agree in what is stated in there retrospectively; also some people will probably search for oversampling, others for interpolation, maybe this way it will be easier to find this solution by whoever deems necessary.
I close this issue as there is nothing else to do here.

**Comment by strongholdmedia** [comment]
Sorry to bother again, but also, the "Master Volume Left" and "Master Volume Right" sliders are dropped at 000 and don't seem to actually influence anything; is this intentional?

**Comment by jangler** [comment]
Good question. I never tried using them. I'll open an issue about that specifically.
