### ISSUE TITLE
How I what OSX?

### ISSUE THREAD

**Issue by esaruoho** [schismtracker/schismtracker#12]
How system OSX Schism Tracker make download zip then start app how compile method system unknown difficult to guess no documentation for osx system install update compile method.

help?

**Comment by jangler** [comment]
https://github.com/schismtracker/schismtracker/blob/master/docs/building_on_osx.md

Does that help?

Now that I think of it, the [docs/](https://github.com/schismtracker/schismtracker/blob/master/docs/) should be linked to or mentioned in the readme (and probably the wiki landing page). Their location isn't exactly obvious, even if you go to the wiki.

**Comment by esaruoho** [comment]
Thank you, appreciates much I do

**Comment by jangler** [comment]
Added compilation notes link to the readme in b9f3a65eb72207be71abb6002896dfc323a7199f, and cleaned up the wiki just a little bit (why weren't the Windows build notes mentioned at all??). If you have any more questions, feel free to ask here (or in [the chipmusic.org thread](http://chipmusic.org/forums/topic/18439/what-happened-to-schismtrackerorg/), I suppose, since you've brought this up there as well).

**Comment by esaruoho** [comment]
Is it possible to move that building_on_osx.md to be in the root folder, much like the "COMPILE-WIN32.txt" already is? :)

**Comment by ghost** [comment]
COMPILE-WIN32.txt shouldn't be in the root folder anymore, we decided to move all the docs to the docs/ folder for simplicity - if you have COMPILE-WIN32.txt in the root folder I guess you have an old version of the sources, or extracted the new sources into a folder on top of the old sources.

**Comment by jangler** [comment]
(The latest master.zip is accessible at https://github.com/schismtracker/schismtracker/archive/master.zip. GitHub appears to have made this less obvious/accessible via the UI than it used to be.)

**Comment by esaruoho** [comment]
I've create a PR ( #132 ) with accurate and valid macOS installation instructions for creation of `./schismtracker` and `Schism_Tracker.app`.
