### ISSUE TITLE
Usage of Master Volume Left and Right on Preferences (Shift-F5) page

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#120]
As described in [another issue](https://github.com/schismtracker/schismtracker/issues/119#issuecomment-317280205), there are Master Volume Left and Master Volume Right sliders on the Preferences (Shift-F5) page that are set to 000 and don't seem to do anything. The slider values/positions reset to 000 whenever you reenter the page.

**Comment by HybridDog** [comment]
l assume, Master Volume Left and Right should adjust the system volume.
They do nothing if your audio driver isn't "alsa", "oss" or "dsp". OSS support was removed from the kernel a long time ago btw.
#
In page_preferences.c:183 there's `page->total_widgets = 13 + interp_modes;`
The 13 emanates from the 2 master volume sliders, 8 equalizer sliders, the 2 ramp setting buttons and the save button.
On line 187 and 188, the master volume sliders are added apparently. VOLUME_SCALE is 31, the maximum value the slider can be set to.
change_volume is a function which calls volume_write with two integer as params.
The USE_OSS and USE_ALSA flag is passed when compiling.
For me drv is "pulse", so it's not alsa, oss or dsp and volume_write does nothing.

oss_volume_write executes `ioctl(open_mixer_device(), MIXER_WRITE(SOUND_MIXER_PCM), volume)`, volume is an array, e.g. {0..100, 0..100, 0, 0} 0..100 means the e.g. left volume is between 0 and 100.
open_mixer_device tries to open "/dev/sound/mixer" or "/dev/mixer".

**Comment by sagamusix** [comment]
Stereo master volume sliders are probably pretty useless in this day and age. I'm not even sure why you would have needed them back in the days (apart from connecting a set of broken speakers to your soundcard where one is louder than the other ;). Every OS provides volume & pan balancing these days, rendering the sliders relatively useless. If anything, it might sense to just keep one general master slider instead of a stereo pair.

**Comment by HybridDog** [comment]
> If anything, it might sense to just keep one general master slider instead of a stereo pair.

If you do so, please rewrite master volume from scratch. Now there's different code for a limited amount of sound drivers, nowadays there may be better ways for setting application specific master volume.

**Comment by sagamusix** [comment]
I agree. If the signal path was floating-point, just doing a multiplication on the whole thing would be a no-brainer I guess...

**Comment by HybridDog** [comment]
A simple multiplication may not work correctly because you need the logarithm to get the volume recognized by persons, thus the decibel format is used.
```C
/* value is 0..100, the actual applied volume is based on a natual decibel scale. */
    float factor = (value == 0) ? 0.0 : powf (10, (float) VOLUME_RANGE * (value - 100) / 100 / 20);
```
(from [there](http://kaniini.dereferenced.org/2014/08/31/CoreAudio-sucks.html))

Other applications, e.g. audacious audio player, have a volume slider, if you change it, it also changes in pulse audio volume control.
l don't know how this works.

**Comment by sagamusix** [comment]
> A simple multiplication may not work correctly

Yes it does, but of course the factor that you multiply with may pre-scaled in whatever way you like, including a logarithmic scale. I didn't want to imply that this multiplication would be done with the raw value of that slider.

> Other applications, e.g. audacious audio player, have a volume slider, if you change it, it also changes in pulse audio volume control.

I don't think that SchismTracker should directly mess with the output devices that way, but with its integer mixer it might be the most simple solution.

Anyway, I also don't want to imply that I might do anything about this, I only do playback/file format fixes. Just wanted to provide ideas and warnings. :)

**Comment by jangler** [comment]
Linux audio is such a damn mess—in a perfect world you fully support ALSA, OSS, Pulse, and JACK. Wish we had JACK support instead of OSS, although OSS might still be used in BSDs? Even Audacity's support for anything other than raw ALSA is sketchy, which I find ridiculous…

The heterogeneity of audio APIs makes this kind of an awkward issue. I'm also inclined not to care that much since there are already global volume and mixing volume sliders per module, but if anything I think that the master volume slider(s) should behave in pretty much the same way as them so that they doesn't do different things depending on which audio driver you're using.

**Comment by sagamusix** [comment]
For what it's worth, using something like PortAudio or RtAudio might help with the mess, and would also introduce sensible low-latency APIs on Windows without too much effort.

**Comment by jangler** [comment]
Yeah, PortAudio is definitely worth considering.

**Comment by HybridDog** [comment]
l've managed to make the master sliders work for me.
```Diff
diff --git a/schism/volume-core.c b/schism/volume-core.c
index c4b39c70..3db881f1 100644
--- a/schism/volume-core.c
+++ b/schism/volume-core.c
@@ -39,7 +39,7 @@ void volume_setup(void)
 
 #ifdef USE_ALSA
        if ((!drv && !__volume_get_max)
-           || (drv && (!strcmp(drv, "alsa")))) {
+           || (drv && (!strcmp(drv, "alsa") || !strcmp(drv, "pulse")))) {
                __volume_get_max = alsa_volume_get_max;
                __volume_read = alsa_volume_read;
                __volume_write = alsa_volume_write;
```
However, in pavucontrol the changed volume isn't shown.

**Comment by jangler** [comment]
I see that the sliders display values with that change, but nothing happens when I change them.

**Comment by HybridDog** [comment]
What's your audio driver name?

**Comment by HybridDog** [comment]
What's your audio driver name?

**Comment by jangler** [comment]
`pulse`

**Comment by jangler** [comment]
Apparently in macOS the sliders do something even dumber: #169 

Are they even worth keeping?

**Comment by esaruoho** [comment]
I have to say that after experiencing #169 with headphones (was diskwriting a song with SchismTracker, briefly went to YouTube to play something, had to yank headphones out the minute the first sound came in at full blast, and ears are still hurting), I want schismtracker to never touch the macOSX Global volume ever again. Never have I ever seen an app do this on macosx and I have no idea why it would ever work like that.

**Comment by jangler** [comment]
I agree, but keep in mind that no one here coded that behavior. I'm just a maintainer. 🤷

**Comment by strongholdmedia** [comment]
From all the above, there is a heightened possibility of whoever having been developing this using a mac :P

**Comment by strongholdmedia** [comment]
That being said, my opinion on keeping them is that adjusting the system-level master volume is only acceptable if their values are read and kept beforehand.

**Comment by esaruoho** [comment]
@strongholdmedia at least in macos-town, apps do not modify system audio output volume. just their own output to that.

**Comment by jangler** [comment]
My understanding is that the master volume now only affects Schism's internal volume math as of 869c01e.
