### ISSUE TITLE
Crash when playing HPMC-2.XM

### ISSUE THREAD

**Issue by HybridDog** [schismtracker/schismtracker#121]
When playing HPMC-2.XM from https://demozoo.org/music/154941/, schismtracker crashes at some point in time. There's the valgrind output: https://pastebin.com/raw/shKwu0Vp

**Comment by jangler** [comment]
Alright, something's wonky in the conversion. Besides crashing on pattern 11, Schism doesn't load any of the pattern data starting at row 40 (in pattern 11 only).

**Comment by jangler** [comment]
I had a dream about this bug. In the dream, the bug also caused clips from movies to play in the tracker instead of tracker music.

**Comment by HybridDog** [comment]
It sounds interesting. l've made a thumbnailer which puts the bytes of xm, it and mod files into the icon ([screenshot](https://user-images.githubusercontent.com/3192173/29976496-83581142-8f3a-11e7-8a5d-f97c7780bb69.png)).

**Comment by sagamusix** [comment]
> Besides crashing on pattern 11, Schism doesn't load any of the pattern data starting at row 40 (in pattern 11 only).

The file is corrupted, so the emptiness in that pattern is not a broken conversion. However, there are some out-of-range instrument numbers which Schism uses without checking if they are valid. I will look into fixing this.

**Comment by sagamusix** [comment]
Okay please check if the current revision behaves better. :)

**Comment by HybridDog** [comment]
It doesn't crash, thanks.

l'd like to get information on stderr when some corrupted data appears.

**Comment by sagamusix** [comment]
I didn't have a close look but the data that lead to the crash is not corrupted per se, i.e. just because the instrument number is higher than what Schism supports doesn't mean that it's invalid.
