### ISSUE TITLE
MIDI input only uses first instrument

### ISSUE THREAD

**Issue by rebeccaloran** [schismtracker/schismtracker#122]
When attaching a MIDI -> USB cable, instruments/samples are played correctly, however when changing instruments in the pattern editor, only the first instrument is heard/input.

As a workaround I can just select all of that channel and change instrument, but it's pretty annoying. If I want to hear how something sounds I need to go to instrument or sample window.

**Comment by sagamusix** [comment]
As discussed on IRC, page_patedit.c:3014 uses the MIDI channel on which the note was received to set the instrument; MIDI channel 1 writes instrument 1 to the pattern, channel 2 writes instrument 2, etc...
This does not make a lot of sense to me. Can any IT people comment on whether IT does something similar or can this behaviour be removed?

**Comment by sagamusix** [comment]
Behaviour changed in 4d3277746e572ffc42094e53831e6d81b048c236. If anyone really needs the old questionable behaviour, shout here.
