### ISSUE TITLE
Change default key bindings

### ISSUE THREAD

**Issue by HybridDog** [schismtracker/schismtracker#123]
Currently there are key bindings which can only be used with the specific keyboard layout (querty), e.g. {, [, ] and } and some key combinations are used by the window manager (alt+F1 only works after pressing ctrl+d for me).

Here are some key combinations l observed frequently:

Application key combinations
ctrl+o open file
ctrl+r reload file
ctrl+s save file
ctrl+shift+s save to: save with explicitly specifying destination
ctrl+w close window
ctrl+pageup go to next tab
ctrl+pagedown go to previous tab
ctrl+shift+pageup switch tab with next tab
ctrl+shift+pagedown switch tab with previous tab
alt+<number> go to tab
ctrl+n new (e.g. window)
ctrl+z undo
ctrl+y redo
ctrl+c copy
ctrl+x cut
ctrl+v paste
ctrl+shift+u insert unicode character
ctrl+a tag all (e.g. all text in a textfield)
ctrl+left move cursor to previous word
ctrl+right move cursor to next word
shift+left move cursor one character to the left and tag it
ctrl+shift+left move cursor one word to the left and tag it
ctrl+p print
ctrl+f search
ctrl++ zoom in
ctrl+- zoom out
ctrl+0 reset zoom
alt+<letter> access menu bar
tab select next (e.g. next button)
shift+tab select previous
F11 fullscreen mode
ctrl+alt+enter fullscreen mode (seen in wz2100 and schismtracker)
F1 show help
ctrl+q quit
ESC exit something

Window manager key combinations
ctrl+alt+right go to next desktop
ctrl+alt+left go to previous desktop
alt+ESC focus next window
alt+tab focus next window (after releasing alt)
alt+shift+tab focus previous window (after releasing alt)
alt+F2 execute command
ctrl+alt+t open terminal window
alt+F1 open start menu
ctrl+alt+l lock user
ctrl+alt+backspace logout
win+<anything> the windows key should be reserved for the window manager

l think schismtracker could use key combinations which many other applications also use, e.g. ctrl+shift+s to save a file with specifying a name instead of F10 or ctrl+w.
Pattern Editor, Sample List, Instrument List, Info Page, Song Variables & […], Order List and Panning, System Configuration, etc. could be seen as tabs, so pressing ctrl+pageup could be used to go to the next tab. Currently some function keys are used to switch between them, but it's inconsistent, e.g. F3 and F4 show information (select tab) and F6 and F8 are used to play the pattern or stop the song (but don't change a tab).

**Comment by jangler** [comment]
Schism Tracker exists *specifically* to replicate the user interface of a DOS program. If users want a [CUA](https://en.wikipedia.org/wiki/IBM_Common_User_Access)-type interface, they should use OpenMPT instead. See #68 for problems with non-QWERTY keyboard layouts.

**Comment by esaruoho** [comment]
i'm all for having multiple shortcuts to do the same thing, but ctrl-o already writes pattern to sample so why should ctrl-o be open?

**Comment by HybridDog** [comment]
> but ctrl-o already writes pattern to sample

The help page (F1) currently says "F9 Load Module (also Ctrl-L, Ctrl-O)". l've tested it, ctrl+l indeed shows load module, but ctrl+o didn't.

**Comment by jangler** [comment]
Nice catch.
