### ISSUE TITLE
SchismTracker does not multi-wav-render valid WAV files of same length

### ISSUE THREAD

**Issue by esaruoho** [schismtracker/schismtracker#124]
1. Load module
2. Shift-F10
3. Select MWAV
4. Save.

Expected result:
valid WAV files of the exact same length (module is the same length, so multiwavs should be the same length, right?

Current result:
Invalid WAV files (need to be diagnosed, analysed by Sample Manager and then truncated/extended) of varying lengths. - see screenshot.

![untitled](https://user-images.githubusercontent.com/4966687/31047411-e4d01b7e-a612-11e7-87c7-90c5e8ccd774.jpg)

Could you guys please let me know what I should do to get valid same-length wavefiles out of MWAV writer?

**Comment by esaruoho** [comment]
..apart from soloing one channel at a time and using the regular wav writer 20 times.. wouldn't it be cool if MWAV worked accurately too? this has been an ongoing thing for 8-10 years now (MWAV broken)

**Comment by jangler** [comment]
By "invalid" do you just mean that the lengths differ?

**Comment by esaruoho** [comment]
Lengths are not identical, Also each one has to be diagnosed and fixed with a Third party app to actually work so headers are broken too. But Lets focus on the fact that they are not 1:1 the length of the song first and hope the faulty wavfile issue corrects itself when length is songlength.

**Comment by jangler** [comment]
I can't reproduce the broken header problem; every application I try, including Schism Tracker, can use the exported WAV files with no difficulty.

**Comment by esaruoho** [comment]
@jangler can you reproduce the differing lengths problem?

**Comment by jangler** [comment]
Yeah, that one I can reproduce. I'd say that it's not really a problem, but intentionally hanging notes will get cut off if there's no data in that channel for the rest of the orders in the song. I think Schism is trying to be too clever for its own good here.

**Comment by esaruoho** [comment]
is there any chance this could be addressed, so that the wavefiles coming out of schismtracker are the same length as they should be when using shift-f10/MWAV? @jangler

**Comment by jangler** [comment]
I'll take a look at it today.

**Comment by jangler** [comment]
Haven't gotten anywhere with this yet; seems like it's probably handled within the mixer and not in the disk operations logic…

**Comment by esaruoho** [comment]
@jangler is there something i can do to help with this side of this project?

**Comment by jangler** [comment]
Can you link an example of a (short) invalid WAV file exported by Schism?

**Comment by esaruoho** [comment]
@jangler I can link the original file and the wavs, but they won't be short.

**Comment by esaruoho** [comment]
@jangler here's the file: http://amp.dascene.net/downmod.php?index=23064

all i did was shift-f10 on it and save as mwav. that was the result

**Comment by jangler** [comment]
I can't reproduce it though; there's nothing wrong with the WAV files that MWAV exports.

**Comment by esaruoho** [comment]
@jangler when loading this into Sample Manager, I get these types of errors:

<img width="654" alt="screen shot 2018-01-12 at 23 41 18" src="https://user-images.githubusercontent.com/4966687/34896347-253dde18-f7f2-11e7-811a-def6603e580e.png">

then when I use Sample Manager to fix these errors - then Live loads them wrong.

what is weird to me, personally, is that they should be considered "regular size wavs" and "compatible wavs", and sample manager throws this kind of error.

**Comment by esaruoho** [comment]
if i don't fix them with sample manager, ableton live loads them like this:
<img width="1143" alt="screen shot 2018-01-12 at 23 44 08" src="https://user-images.githubusercontent.com/4966687/34896436-8724f1c0-f7f2-11e7-9397-f8cfc4ba2c41.png">
so even then, they are not the same, identical length.

**Comment by esaruoho** [comment]
here's all them files.

<img width="1143" alt="screen shot 2018-01-12 at 23 47 55" src="https://user-images.githubusercontent.com/4966687/34896587-0749f4fe-f7f3-11e7-812e-475bc72b19a9.png">

so, from my point of view, Schism does not save accurate MWAV of identical length - whether or not I touch it with Sample Manager or not.

**Comment by esaruoho** [comment]
what's weird is that each and every file is 55,1mb in length, so it "should be, in theory, same length".

**Comment by jangler** [comment]
OK, so the files Schism is writing are (I think) the same length as a normal WAV export would be, which is sometimes longer than required for a channel. The data subchunk always has the correct length, but the main RIFF chunk has the length of the entire file, implying that there are potential extra subchunks after the data subchunk.

Option 1 would be to correct the chunk size data and truncate the files to the correct length given their content as currently exported. This would save disk space, but it would also make using the files in cases like yours more difficult (since you'd have to manually align them), and I have concerns that Schism is not smart enough to *actually* know the minimum required size for each channel's export. I haven't looked at (or found) the code that determines this.

Option 2 would be to make every WAV file exported by MWAV the length of the entire module, which would also fix the problem with (sub)chunk sizes. I'm inclined toward this option.

**Comment by esaruoho** [comment]
@jangler definitely option 2 would be the way to go :)

**Comment by jangler** [comment]
I think I fixed this in the `mwav-fix` branch. It was more broken than I thought. Can you check to see if you still get any problems?

**Comment by esaruoho** [comment]
hi @jangler - first results:
1. Loading these into Sample Manager no longer reports them as being borken.
<img width="615" alt="screen shot 2018-01-14 at 18 44 35" src="https://user-images.githubusercontent.com/4966687/34918424-057f2518-f95b-11e7-9366-7a48e8d85fe9.png">
2. All the lengths are the same - 312.48 seconds. file sizes are the same, 53.8mb (after loading to Sample Manager). This looks good.
3. Loading them into Ableton Live 10: - perfect. You have hit the nail on the head and to me, SchismTracker now saves accurate multiwavfiles.
<img width="1151" alt="screen shot 2018-01-14 at 18 54 27" src="https://user-images.githubusercontent.com/4966687/34918528-8273774e-f95c-11e7-8025-8b0222e5b006.png">

4. Loading them into Logic Pro X: 
<img width="1038" alt="screen shot 2018-01-14 at 18 57 04" src="https://user-images.githubusercontent.com/4966687/34918554-ba3fe342-f95c-11e7-8083-05280c7a471c.png">



Perfect. I'm giving this the highest LGTM possible. Please do merge this in when you can! :)

**Comment by esaruoho** [comment]
also, great job @jangler !! :)

**Comment by jangler** [comment]
Normal WAV writing for songs, samples, and patterns also still seems to work fine, so I will merge this. Thanks for bringing this issue to my attention—it definitely needed a fix.
