### ISSUE TITLE
No OS X app bundle

### ISSUE THREAD

**Issue by ian128K** [schismtracker/schismtracker#125]
The latest build has an OS X binary file, but there's no app bundle. I tried going back and downloading the build from 20120105, which apparently was a known good OS X bundled build, but all that's available in the Releases page for that build is the source code, which isn't helpful. I'm running OS X 10.11.6 (El Capitan) and need a copy to replace my 20110101 build, which no longer launches.

**Comment by esaruoho** [comment]
I, too, wish for SchismTracker.app (with icon!) instead of ./schismtracker which i need to start from terminal.

**Comment by jangler** [comment]
Oh wow, did I actually set it up to deploy valid macOS binaries? I forgot about that.

Here's the 2012 .app bundle with updated metadata and an updated binary. Does this work for you?

[schism_20170910_macOS_app.zip](https://github.com/schismtracker/schismtracker/files/1424298/schism_20170910_macOS_app.zip)

**Comment by ian128K** [comment]
Thank you! Unfortunately, it doesn't work; I get a crash to desktop on launch. Here's the details from the crash report, if this helps:

> Process:               schismtracker [26502]
> Path:                  /Users/USER/Downloads/Schism Tracker.app/Contents/MacOS/schismtracker
> Identifier:            org.schismtracker.SchismTracker
> Version:               ???
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           schismtracker [26502]
> User ID:               501
> 
> Date/Time:             2017-11-11 00:55:28.211 -0800
> OS Version:            Mac OS X 10.11.6 (15G1611)
> Report Version:        11
> Anonymous UUID:        808C6A9C-55F2-0427-E18D-2FBF13269705
> 
> Sleep/Wake UUID:       4514BACF-7A03-4D41-AA9C-AFC6E6D18A76
> 
> Time Awake Since Boot: 1100000 seconds
> Time Since Wake:       990000 seconds
> 
> System Integrity Protection: disabled
> 
> Crashed Thread:        0
> 
> Exception Type:        EXC_BREAKPOINT (SIGTRAP)
> Exception Codes:       0x0000000000000002, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Application Specific Information:
> dyld: launch, loading dependent libraries
> 
> Dyld Error Message:
>   Library not loaded: /usr/local/opt/sdl/lib/libSDL-1.2.0.dylib
>   Referenced from: /Users/USER/Downloads/Schism Tracker.app/Contents/MacOS/schismtracker
>   Reason: image not found
> 
> Binary Images:
>     0x7fff66180000 -     0x7fff661b7a47  dyld (360.22) <C8E77F6D-CE86-3C5B-8576-2584A799B51E> /usr/lib/dyld

**Comment by jangler** [comment]
Huh, I guess we have to change the build routine to get the executable to look for the dylib in the relative path.

**Comment by esaruoho** [comment]
@ian128K hi are you able to follow the instructions in #132 - I wrote actual step-by-step instructions on getting SchismTracker compiled, and how to update the Schism_Tracker.app with the newest compiled `schismtracker`. Let us know how you get on.

With these instructions, I've been able to run `./schismtracker` and create a functioning `Schism_Tracker.app` without any issues.

**Comment by esaruoho** [comment]
@ian128K when downloading the repo, did you check the sys/macosx folder - which does contain a Schism_Tracker.app?

**Comment by ghost** [comment]
@ian128K you can try installing SDL 1.2 on your system (e.g., via `brew install sdl`) as a temporary workaround. hopefully that will fix your issue but let me know if it doesn't.

i believe the `.app` files being passed around have a problem where they're not locating the bundled SDL dylib. i'm going to try and fix that.

**Comment by ian128K** [comment]
@esaruoho I get to the step where I've entered the schismtracker folder and run autoreconf. This is what I get:

`⑆ autoreconf -i
autoreconf: 'configure.ac' or 'configure.in' is required`

**Comment by ian128K** [comment]
@esaruoho Following the instructions in [#132](https://github.com/schismtracker/schismtracker/pull/132) worked. 👍
