### ISSUE TITLE
Multiple order list columns

### ISSUE THREAD

**Issue by firolightfog** [schismtracker/schismtracker#126]
![2017_11_30_12_24_43_schism_tracker](https://user-images.githubusercontent.com/34127628/33430999-e7d2f8d8-d5d2-11e7-8774-f2cf2d99bcfa.png)
Multiplying the order list (F11) coulmn would greatly enhance the composing work. Having the rythm (drums/percussions) in one of the columns and the melodic part (pads/leads) in the other one would simplify the composing work. I also expect the reduction of number of patterns stored. But it would probably mean some limitation on the number of channels/patterns. (I.e. 64/3~=21 channels.)
Cheers, Andras

**Comment by firolightfog** [comment]
Guys, I didn't find a forum and I don't know where to write this one but founding Schism Tracker recently, I was fighting with my tears. I used to play with Scream Tracker as well as Impulse Tracker but I haven't touched any of them for more than 15 years. Opening this beauty, seeing the old-school layout, remembering the same hotkeys after all those years by heart ... A shocking experience. Feels like home.

**Comment by jangler** [comment]
I think Renoise has this, and a lot of "chip" trackers do this per channel. Unfortunately this paradigm just isn't supported by either of the module types that Schism exports to (IT and S3M), and adding another format, or format extensions, is beyond the scope of this project.

That's really cool that you dig Schism though—if it feels like home for a ST3/IT veteran, then Schism is definitely meeting its goal. Hope you make some neat tunes! :)
