### ISSUE TITLE
Fullscreen video & aspect ratios

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#13]
Hi all,

I've been working on trying to fix fullscreen video, which has never worked right on my machine. I think I've improved the code that gets the fullscreen resolution, and now it gives the native resolution of my monitor. 

However the aspect ratio of my monitor's native resolution (16:10) is Schism's native aspect ratio anyway, so it's not surprising that it's now working for me. More testing is needed.

Would be grateful if y'all could answer this survey (particularly if you use a monitor that isn't 16:10 - and no, changing your desktop resolution doesn't count!):
1. What's your monitor's native resolution?
2. Do old versions (or the current master) give the right aspect ratio, when in fullscreen, for you?
3. Does the fullscreen43 branch give the right aspect ratio, when in fullscreen, for you?

Hoping for the best here but if I broke it for all the rest of you I guess it's back to the drawing board.

**Comment by ghost** [comment]
Might as well answer my own questions:
1. 1680x1050
2. No, it's way too widescreen, almost 2:1
3. Yes (duh)

**Comment by uucidl** [comment]
1. 1440x900
2. Fullscreen has correct aspect ratio
3. fullscreen43 branch gives incorrect result: smaller display area with letter box above and to the left and right

**Comment by ghost** [comment]
Gah! Is it the right shape, at least?

**Comment by jangler** [comment]
What uucidl is seeing sounds like what I was seeing on my desktop (same native resolution, too). Fullscreen just crashes on this computer, but it's a Chromebook so whatever.

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x287
  Serial number of failed request:  153
  Current serial number in output stream:  155
Segmentation fault (core dumped)
```

**Comment by ghost** [comment]
Could you let me know what it says for "Display dimensions: " in the log if you build&run the latest fullscreen43 and load a song (don't have to go fullscreen, it should always try telling you your native res now).

If it's not your native res, we have a problem. If it _is_ your native res we have a different kind of problem.

(Just to clarify, this is nothing to do with the fullscreen43 _option_.  You can leave that off - it's just that trying to add that option made me realise just how broken fullscreen video was for me, and now I'm trying to fix the rest of it.)

**Comment by uucidl** [comment]
The behaviour I noticed depends on runtime & type of display chosen. The letter box I got after closing OpenGL surface and clicking fullscreen in the settings window.

I moved to YUV and pressed fullscreen: still some letter boxing but different.

However after quitting schism tracker on the YUV setting and starting it up again + pressing the key shortcut to move to fullscreen, I have the correct fullscreen with no black borders.

**Comment by uucidl** [comment]
(This was on the branch as of 2016-05-16, not with the latest commits)

**Comment by ghost** [comment]
Thanks for testing! :)

The commits I made this morning change almost everything so it will probably all be different now. I'm now explicitly asking for a surface at native res dimensions, and explicitly calculating what the biggest 16:10 rectangle we can fit on it is. I'm feeling hopeful but god only knows what will happen in reality.

I've only tested with SDL surface so far, because OpenGL and DirectX are both broken on my machine - probably should have tested YUV too! It's interesting that starting in OpenGL and then moving to YUV has different results vs. starting in YUV.

**Comment by ghost** [comment]
Ok, can confirm that starting in OpenGL and then moving out of it gives us the wrong desktop dimensions and ruins fullscreen even if you switch to SDL/YUV. Guess I'll fix that now. Thanks!

**Comment by ghost** [comment]
Moving from OpenGL to another res and then going fullscreen should be fixed now. However OpenGL itself will probably be wrong still - OpenGL is totally broken on my machine, I didn't realise it worked on any Windows machines, so I will probably have no luck fixing that.

**Comment by uucidl** [comment]
The OS I've been testing it on is OSX. Won't try it on Windows until I've finished a basic windows MSVC port. I would think OpenGL should work on there though :)

**Comment by ghost** [comment]
Aha! Didn't know we had another OSXer!

Any chance you could test the latest fullscreen43 if you get any time?

**Comment by 0x5742** [comment]
fwiw I'm strongly against letterboxing in full screen mode, ever. Keep in mind that Impulse Tracker was 640x400 - that's a widescreen ratio (if your pixels are square), and scales to 1920x1200 perfectly. Yet we happily used it on our 4:3 monitors just fine back in the day ;)

**Comment by jangler** [comment]
I think I'm with Storlek on this one. @mb14, why/how is your fullscreen almost 2:1 when both Schism's ordinary resolution and your monitor's native resolution are both 16:10? Is it letterboxed for you?

**Comment by ghost** [comment]
> fwiw I'm strongly against letterboxing in full screen mode, ever. Keep in mind that Impulse Tracker was 640x400 - that's a widescreen ratio (if your pixels are square), and scales to 1920x1200 perfectly. Yet we happily used it on our 4:3 monitors just fine back in the day ;)

Yeah because it was designed for 4:3 and looks better at 4:3. Hence me trying to add the feature! But this isn't about adding a feature anymore. Letterboxing in fullscreen mode happens anyway, nevermind that it's the _wrong_ letterboxing.

> I think I'm with Storlek on this one. @mb14, why/how is your fullscreen almost 2:1 when both Schism's ordinary resolution and your monitor's native resolution are both 16:10? Is it letterboxed for you?

Because it's broken! Which is what I'm trying to fix! It's letterboxed at the top and the bottom but not at the sides, which makes no sense because, as you said, both Schism and my screen are 16:10.

For clarity: I don't really care about 4:3. Exactly 2 of the lines in the latest fullscreen43 have anything to do with 4:3. This is about fixing a (I presume) bug which causes Schism to display at a joke aspect ratio when viewed on my monitor.

If I'm going to put time in to make it work with IRC clients from 2001 or Finnish Mac keyboards, I'm also going to make it work with my own display on my own computer.

**Comment by jangler** [comment]
That's screwed; carry on.

**Comment by ghost** [comment]
Thanks _hug_

It works for me now on the display options that work for me at least, I probably broke it for other stuff though (OpenGL, framebuffer, DirectX) that I'm not able to test - so would appreciate some help testing this.

Though if interest is low because no one can reproduce the bug I'm having, or if we can't find a fix that doesn't just break it for other people instead, I can always just do a stripped down video.c that works for me on the settings I use and patch that in when making builds for personal use. Not an ideal solution, but I guess a bug that only affects me isn't the hill I want to die on.

**Comment by ghost** [comment]
Right!

New branch, `fullscreen-bugfix`. The changes only affect software surfaces so it shouldn't cause any problems for OpenGL, DirectX or YUV. The monitor native resolution is only gotten once, before any video stuff is set up, because that's the only time SDL will report it correctly. Letterboxing is either done or not done based on a variable `want_fixed`, which was already there before I started messing with things and is, I assume, used to decide whether we want a fixed AR or not. There's a commented-out line of code which will give me 4:3 fullscreen because that's how I like it, but I haven't bothered putting the config options in for it since doing that just seemed to confuse people as to what I was up to.

It all works fine here, including changing from OpenGL to SDL and then going fullscreen. Please could some people try it and tell me if it's made things worse for them or not? Thanks <3

You can ignore fullscreen43 now, it is bad code from before I understood what I was trying to do, and I will delete it soon if everything's okay with that. Sorry for being such a pest here.

**Comment by ghost** [comment]
Oh, btw, this is what current master looks like in fullscreen for me at the moment:

![schism_master_fullscreen](https://cloud.githubusercontent.com/assets/19272249/15365652/f65e2ee6-1d18-11e6-9294-096a03895fcb.png)

Which should explain why I care so much about this!

**Comment by jangler** [comment]
Hey you're fine; I'll check this out when I get home tomorrow night.

**Comment by jangler** [comment]
OK, so everything looks fine and pretty much the same here (SDL, YUV, and OpenGL). I'm using a 16:10 monitor and Schism scales to fill the screen.

Although there's a very strange bug regarding switching to OpenGL. If I start in SDL and change to OpenGL, that works, but if I then change back to SDL and back to OpenGL again, the OpenGL change won't stick—the video driver selection remains on SDL, there's no indication that the driver has changed (normally there's a pause and blank screen for a moment when switching drivers), and if I quit and reload, SDL is the driver.

**Comment by ghost** [comment]
Glad I haven't cacked anything up for you!

Yeah, that happens to me as well - that bug is in master too, isn't it (_crosses fingers_)? I thought what was going on was that I couldn't switch to OpenGL if it'd ever been fullscreen, but you might be right. It's weird anyway, I just assumed it was happening here because OpenGL doesn't work fullscreen, but probably not that if it's happening to you too.

**Comment by jangler** [comment]
I'll take a look at the code in `schism/page_config.c` and see if there's any obvious culprit for the OpenGL switchy bug; if not then I think it's obscure enough not to be worth digging into.

Anyway, is this `want_fixed` variable something we should be testing? Is it a hidden config option or what?

**Comment by jangler** [comment]
The second OpenGL switch fails because the corresponding `SDL_SetVideoMode()` fails with error:

> Couldn't find matching GLX visual

I don't really want to investigate why this is happening on subsequent attempts (so I won't).

**Comment by ghost** [comment]
> I'll take a look at the code in schism/page_config.c and see if there's any obvious culprit for the OpenGL switchy bug; if not then I think it's obscure enough not to be worth digging into.
> 
> Anyway, is this want_fixed variable something we should be testing? Is it a hidden config option or what?

I have no idea! 

```
video.desktop.want_fixed = -1;
q = getenv("SCHISM_VIDEO_ASPECT");
if (q && (strcasecmp(q,"nofixed") == 0 || strcasecmp(q,"full")==0
|| strcasecmp(q,"fit") == 0 || strcasecmp(q,"wide") == 0
|| strcasecmp(q,"no-fixed") == 0))
    video.desktop.want_fixed = 0;
```

**Comment by 0x5742** [comment]
As long as you're messing about with that, could I humbly request dumping these internal environment variables to the curb and using, well, pretty much anything else?

**Comment by jangler** [comment]
@mb14 what's the state of this issue?

**Comment by ghost** [comment]
fixed by branch "fullscreen-bugfix" merged 31/7/16 on my machine, no one else was having my issues so can't confirm much, will close this for now
