### ISSUE TITLE
CI: continuous-integration/appveyor/pr — Error parsing appveyor.yml

### ISSUE THREAD

**Issue by esaruoho** [schismtracker/schismtracker#133]
what does this error mean, and could it be fixed somehow?
```
continuous-integration/appveyor/pr — Error parsing appveyor.yml
```

<img width="794" alt="screen shot 2018-01-05 at 11 05 56" src="https://user-images.githubusercontent.com/4966687/34602458-7a1a6c98-f208-11e7-8ab0-cc965f9a944a.png">

**Comment by jangler** [comment]
Good question. It's probably a simple fix. The appveyor.yml hasn't been changed for 6 months, and I'm pretty sure it hasn't always been failing since then. AppVeyor must have changed something?

**Comment by jangler** [comment]
@asbjornu I self-assigned this and plan to look at it soon, but you've been our CI guy so you're also welcome to tackle this issue if you want.
