### ISSUE TITLE
.xi instrument bug involving envelope loops

### ISSUE THREAD

**Issue by smckean** [schismtracker/schismtracker#138]
Actually more of a proposed fix. When Schism Tracker loads any .xi instrument containing volume/panning envelope loops it currently mimics original IT-style behavior: The ending node of the loop is included in the playback rendering on each pass. Testing the behavior of Milkytracker for original XM support, .xi's get loaded whereby the end-loop node is left out of rendering. This creates a difference of one tick per envelope loop between XM/XI files being loaded in FT2/Milky and IT/Schism (I tested IT 2.14 playback in Dosbox as well). This difference is usually not very noticeable, but there are valid XM's that make beautiful use of precise timing in these loops (one good example is Mellow-D's "vb.xm" -> https://api.modarchive.org/downloads.php?moduleid=59444#vb.xm ).

After fiddling with the .xi loading behavior in fmt/xm.c, I found the "problem" could be fixed by shifting the end-loop node back one tick during the file read, as well as any other nodes running up too close behind it. Not exactly optimal, but it works for my purposes nonetheless. I have the patch ready for a commit, but I guess the issue is I'm not too clear on how "origin-precise" Schism Tracker aims to be. I know there are some subtle differences between ST and IT, but also that Schism was built on some heavily-modified libmodplug code in order to provide a very similar look-and-feel experience. I must confess though that I do enjoy pulling up XM files occaisonally in Schism to get some relative exposure.

**Comment by jangler** [comment]
Technically Schism does not support playback of XM files; but it does support loading them like IT files and "translating" them as accurately as is practical. Usually Schism does not aim to be bug-compatible with IT, so if this can be fixed cleanly then I'm all for it, but it sounds like that may not be the case.

So, using the fix you've made, if you load an XI without an envelope loop, and the same XI with an envelope loop, the nodes would be loaded differently into Schism? Wouldn't this cause the opposite problem when the loop is bypassed? I know that's less of an issue, but I'd rather not trade one inaccuracy for another. Or am I misunderstanding something?

I am also curious: does Milky do any conversion when loading IT envelopes?

**Comment by smckean** [comment]
The way I proposed it would affect the precision of the IT envelope in translation. I could instead make it more accurate by creating an extra node one tick behind the end-of-loop node and moving the end there, leaving the original end-node where it was defined.

To be more specific there'd be three test cases at load time:
1) If the loop begins and ends on the same tick (loop length 0 ticks), disable the loop. Same thing happens in FT2, the loop marks are visible but not used.
2) If the loop ends on node N and node N-1 is one tick before, move the loop end to node N-1.
3) If the gap between nodes N and N-1 is larger than one tick, introduce a single node one tick before node N with value correctly interpolated between N and N-1. If the end mark is placed on the new node playback will sound very close to FT2's. The value of the node will be off by at most 0.5 since we are working with integers for nodes and linear interpolation.

Tried loading into Milkytracker; IT songs with instruments will lose all envelope information, loading a single ITI instrument causes a segmentation fault.

**Comment by jangler** [comment]
That sounds sensible to me. And it's always possible to add the node because IT envelopes can have more nodes than XM envelopes, yes?

**Comment by smckean** [comment]
Yep, about twice as many.

**Comment by jangler** [comment]
Fixed by #145.
