### ISSUE TITLE
OSX: Insert / Octaveup/OctaveDn suggestions?

### ISSUE THREAD

**Issue by esaruoho** [schismtracker/schismtracker#14]
Is there any way of enabling some way of using § (left of "1") and < and > (left of z)  for giving us Insert and "octave down" "octave up"? :)

**Comment by ghost** [comment]
I don't know anything about the keyboard code, or macs, or mac keyboards, but I do think we should prioritise some kind of alternative to "insert" for mac users. Is § on all macs in all keyboard layouts? Seems like an obvious key to use for the job if so.

**Comment by esaruoho** [comment]
It seems to be in all keyboard layouts.

**Comment by jangler** [comment]
A quick Google image search for "mac keyboard" brings up results for quite a few different layouts, which are probably dependent on region/language. Some of them look like the en_US layout I'm familiar with, some have the § key where my ` key is, some of them have the § key as shift-3, and some of them have < and > on a single key, as opposed to being shift-, and shift-. (as they are on my keyboard).

In any case, the < and > keys are already bound to sample/instrument switching in the pattern editor (and possibly other places) so we can't change that to make them octave up/down.

**Comment by 0x5742** [comment]
I did a lot of Schism's development in 2006-ish with a Powerbook and the keyboard was just like any other US keyboard aside from the modifier keys.

(I thought all this keyboard nonsense was fixed years ago? At least that's what I was led to believe by all the convoluted stuff going on in keyboard.c)

**Comment by esaruoho** [comment]
@Storlek  naw, keyboard nonsense was always the "yep, just get a full-size keyboard, screw u!" -type of solution ;)

**Comment by jangler** [comment]
Going to close this since it's essentially a duplicate of #24.

**Comment by esaruoho** [comment]
ok, moved requests to #24
