### ISSUE TITLE
Instrument list subpage toggle buttons get stuck down

### ISSUE THREAD

**Issue by vcaputo** [schismtracker/schismtracker#140]
To reproduce this, hit F4 and click on the various General/Volume/Panning/Pitch toggle buttons.

The first time you click each one, things are correct.  Now go back through them all and note how more than one button is depressed.

I wasted a bunch of time tonight being horrified by the widget/togglebutton code but eventually found what is happening is the widget.depressed state is getting stuck down on these togglebutton widgets in their respective per-page instances.  I presume this has to do with the trickery of switching the page to another togglebutton instance while the button is depressed.  So the un-depress is probably happening on the instance in the new page, leaving the old page's instance depressed.

I was able to kludge a fix by making togglebutton_set() clear the depressed field of all the buttons in the group in the same loop it's clearing the togglebutton states in.  That fixes this particular problem, but I suspect there's a more robust and general solution possible in the event handling maintaining the depressed state - one compatible with the togglebutton switcheroo trickery going on in the instrument list.

**Comment by jangler** [comment]
Weird, I never noticed this because I never used the mouse to switch between the pages. I don't like that the code for clicking it is different from the code for keying it…

**Comment by vcaputo** [comment]
That's funny, I never noticed that it worked properly via keyboard!
Clearly I'm not a musician actually creating anything with schism...

**Comment by jangler** [comment]
I just went with the `togglebutton_set()` solution vcaputo mentioned, since I'm not particularly interested in trying to clean up the widget code.
