### ISSUE TITLE
[Linux] JACK-MIDI and JACK-Audio support?

### ISSUE THREAD

**Issue by polyzium** [schismtracker/schismtracker#144]
I want to use Schism with external instruments (like amsynth or VST hosts). ALSA-MIDI's timing is pretty bad, i thought adding JACK-MIDI support would improve the timing a lot and make it sync to Schism's sample playback (also implementing JACK's audio interface for low-latency audio wouldn't be a bad idea, OpenMPT has ASIO support already)

**Comment by trebmuh** [comment]
+1 with the suggestion of adding jack-midi and jack-audio support.

I'd recommend adding jack-transport as well then one will be able to integrate schismtracker as a part of a digital-studio.

**Comment by polyzium** [comment]
Meh, i don't use jack transport tho. But that would result in implementing an actual BPM conversion and something that i will explain it in the following. For 4 steps per beat, some people like to use 6 ticks per row, some people like to use 3 for more resolution. If we, let's say, set schism to speed 006/125, it would display 125 bpm in transport. If we set it to 003/125, (this, obviously, would give more resolution to the playback, but will shrink the length to 2 bars per 64-row pattern), it would display 250 bpm in transport, if you meant the song to sould like 125. That's the problem and i think devs may have problems implementing this. Same for 4/8 ticks per row (3 steps per beat).

**Comment by jangler** [comment]
JACK support in Schism is definitely on my wishlist; in fact, I'm surprised I didn't open a ticket for it already. I know basically nothing about JACK-MIDI, although that's only slightly less than I know about ALSA-MIDI.

And yeah, I remember a debate about the ticks/BPM issue. It gets even hairier if you have tempo/speed change commands, but I think the solution there would be "just don't use them with MIDI, etc".

**Comment by polyzium** [comment]
OpenMPT has an approx. BPM calculation algorithm, maybe you can use that for transport. Or if you want, you can implement JACK-MIDI/Audio first. I don't use JACK transport anyways.
EDIT: Or just use a simple ratio calculation: `tpr:bpm = 6:X` where X is your real BPM

**Comment by polyzium** [comment]
Any update on this?

**Comment by jangler** [comment]
I looked at some of the JACK API documentation and that's about it. I'm not even familiar with how Schism's audio driver code is written yet. This is a feature I want to add, but it's not going to happen in just a few days.

**Comment by jangler** [comment]
(Unless someone more industrious than me makes a PR, of course.)

**Comment by trebmuh** [comment]
In any case it could help, there are some communication channels, such as the #lad IRC channel (lad stands for Linux Audio Developper) or the #jack one both on freenode where some people are able to help. The jack-devel ML as well could help.

**Comment by vcaputo** [comment]
Where does JACK-MIDI support prioritize relative to say... the SDL2 port?

**Comment by jangler** [comment]
I would personally prioritize JACK support over the SDL2 port on the grounds that I'm guessing there would be more direct benefit for less developer time. I should also take a look at davvid's partial SDL2 port to gague the SDL2 issue, though. My impression was that much of it was relatively straightforward, but there are a lot of kinks to iron out.

**Comment by ghost** [comment]
I would second that, having Jack Audio would be awesome.

**Comment by polyzium** [comment]
This issue is 3 months old now, oof... I'm not a C developer unfortunately. Any news?

**Comment by jangler** [comment]
Not really. While I would also like to have JACK support in Schism, implementing new features is honestly pretty low in my personal priorities.

**Comment by Teteros** [comment]
> I would personally prioritize JACK support over the SDL2 port on the grounds that I'm guessing there would be more direct benefit for less developer time.

[SDL2 does have JACK support for output](https://discourse.libsdl.org/t/sdl-now-with-jack-support/22607) again. I've been using JACK via `SDL_AUDIODRIVER=jack` on sdl2-hg in Klystrack without issues, finding out schismtracker is still on sdl 1.2 was a bummer.

**Comment by polyzium** [comment]
Yeah but supporting JACK natively (not through SDL) would be a better idea, for MIDI and transport as well. Plus it always annoys me how SDL (if there are two backends running, in my case JACK+PulseAudio) chooses an audio backend that's "better", so I have to restart the app if I want to force it to use PulseAudio for whatever reason.

**Comment by Teteros** [comment]
@polyzium You can use `SDL_AUDIODRIVER=pulse path_to_app` to force SDL to use PulseAudio and `jack` to force JACK backend.

I don't know any tracker (unless we can count radium) that supports JACK-MIDI, it's pretty niche and I think since migrating to SDL2 would give basic JACK support for free (as long as conversion to JACKs 32-bit floating point conversion is done) that might be the way to go for this issue.

**Comment by jangler** [comment]
869c01e gives us JACK audio (with SDL2), but we're still missing JACK MIDI.

**Comment by polyzium** [comment]
Wow. This issue is 4 years old and I forgot it even existed. Good to hear that progress is being done.

**Comment by mrpapersonic** [comment]
JACK MIDI is fully functional as of 19af89cdbe40604887085ead8c563188c0030d4d (tested in and out with two different physical MIDI devices)
