### ISSUE TITLE
Recent windows binaries?

### ISSUE THREAD

**Issue by zeffii** [schismtracker/schismtracker#15]
The wiki links to the releases but these are all in source form only, I can't find any recent windows builds but would really really love to try some. Any help appreciated (but if I can avoid compiling that's preferable)

(not sure where else to ask this question if this isn't the place for it)

**Comment by jangler** [comment]
Yeah, I've been trying to get a release for Windows / OS X / Linux together, but I'm personally only set up to compile for Linux. @mb14 must have a latest Windows build, but he's on holiday at the moment :)

If a moderately dev-savvy OS X user could compile an OS X build, that would be greatly appreciated. I know it's been done recently, just not with the latest version.

**Comment by jangler** [comment]
Sorry that took so long. :Þ

https://github.com/schismtracker/schismtracker/releases

**Comment by zeffii** [comment]
Thank you very much jangler !

**Comment by zeffii** [comment]
works well btw! Now to relearn the IT kb shortcuts :)
