### ISSUE TITLE
RFC: Song message line delimiters are not normalized

### ISSUE THREAD

**Issue by vcaputo** [schismtracker/schismtracker#156]
Some formats load with the song message being `\n` delimited.  Others, like the IT loader, leave the message `\r` delimited as the format specifies.  Internally, schism tracker is just using the message however the loaders left them - inconsistently.  When someone edits the message, it looks like whatever the input is gets put into the message verbatim.  When the IT file gets written out, whatever the internal representation happens to be is written verbatim, so if the input used `\n` when editing the message, the file will be written with `\n` in the message - which isn't even conformant to the IT format spec.

It seems to me like a delimiter should be standardized on for the internal representation.  Then all loaders should convert, if necessary, to this delimiter.  When saving, it must be converted to the `\r` as specified by the IT spec.  The copy & paste code also probably needs to become aware of what the internal delimiter is and how that relates to the host system, converting if necessary when copying the selection if it's the song message.

As things stand today, even with my selection fixes applied from https://github.com/schismtracker/schismtracker/pull/155, if I select a song message from an IT file and paste it into an xterm running vim, the song message formatting is completely lost.  Studying the clippy code, it's apparent that `\r` is being explicitly dropped in the selection for whatever reason, and no newline is present at all.  So the message becomes one long line.  This should probably be fixed properly.

**Comment by sagamusix** [comment]
Definitely makes sense - OpenMPT does the same, in particular because ChibiTracker uses `\n` rather than `\r` for line endings.

**Comment by jangler** [comment]
Agree; Schism's policy when loading any format (aside from, to some extent, S3M) is "internally convert it to IT". Line endings should be converted to `\r` if that's what IT uses.

> Studying the clippy code, it's apparent that \r is being explicitly dropped in the selection for whatever reason, and no newline is present at all.

That's definitely a bug and should be checked on Windows and macOS too, since the clipboard code is OS-dependent.

**Comment by sagamusix** [comment]
The easiest (least amount of work) approach would be to just replace any \n by \r after the loaders (and not do it in manually in every single loader that manipulates the song message). This does not account for \r\n line delimiters but I have not seen such an abomination in IT files yet.

**Comment by jangler** [comment]
Windows clipboard code copies the message selection verbatim. Not sure if it should be converting `\r` to `\r\n` instead.

**Comment by sagamusix** [comment]
`\r\n` seems the most compatible to me, in particular since pure `\r` linebreaks are extremely uncommon.

**Comment by vcaputo** [comment]
neat!  I've been preoccupied with non-computer stuff for a few months, but nice to see this getting sorted eventually nonetheless, thanks @jangler
