### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [schismtracker/schismtracker#157]
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for schismtracker. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by jangler** [comment]
Sounds like something that will need to be added to .travis.yml. Not sure off the top of my head how to do it, since the current artifacts correspond to operating systems, but I imagine there's a way.

**Comment by asbjornu** [comment]
Isn't the source code provided with every release of Schism Tracker immutable? Have a look at [release 20180513](https://github.com/schismtracker/schismtracker/releases/tag/20180513) for instance – isn't the source code provided there a static download generated at the time of release?

**Comment by fcambus** [comment]
@jangler: if this helps, here is a [commit](https://github.com/jarun/nnn/commit/a5a15b42ebd88bf8e740424ac2f47b0df33158e0) from a repository which is using Travis to build a source release tarball.

@asbjornu: sadly it's not, more info [here](https://marc.info/?l=openbsd-misc&m=153492430016386&w=2).

**Comment by asbjornu** [comment]
@fcambus: Thanks for the information. I was naïvely thinking the source downloads were immutable. Kind of stupid that they aren't, but either way #181 should hopefully fix this.

**Comment by fcambus** [comment]
No worries, and thanks for #181 @asbjornu!
