### ISSUE TITLE
Pitch slides Amiga bug with instrument pitch envelope

### ISSUE THREAD

**Issue by jesus2099** [schismtracker/schismtracker#160]
I have this bug in mind for very long time.

Please download [pslides.zip](https://github.com/schismtracker/schismtracker/files/1979217/pslides.zip) — strip down of my **J2_CLEGO.IT** in [sk_clego.zip](http://ions.fr/shamo/get/sk_clego.zip).

It contains two identical **PSLIDE-A.IT** and **PSLIDE-L.IT** (-A loads as **Pitch Slides: Amiga** while -L loads as **Pitch slides: Linear**).

Listen to them in Schism tracker and you will notice a difference while there are **no differences in Impulse Tracker** (I never remember my version, it's the latest 2.15?, licenced to me) and **no differences in XMPlay 3.8.2.3**.

It's like the pitch slides go in wrong direction:

Pitch slides listening result | PSLIDE-A.IT | PSLIDE-L.IT
------------------------------|-------------|------------
Impulse Tracker 2.1x          | :ok:        | :ok:
Schism Tracker 20180209 win32 | :x:         | :ok:
Schism Tracker 20180209 win64 | :x:         | :ok:
XMPlay 3.8.2.3                | :ok:        | :ok:

Problem is why Amiga mode acts differently for this particular pitch enveloppe in Schism but not in Impulse?
Problem is that my **J2_CLEGO.IT** (how it was saved in 1999) opens in Amiga mode and thus plays badly in Schism.

**Comment by jangler** [comment]
Fixed. There was logic in the arpeggio code accomodating for pitch slide mode, which wasn't present in the pitch envelope code. I want to check sample vibrato too and make sure that's OK in Amiga mode.

**Comment by jangler** [comment]
Yep, the sample auto-vibrato code had the same bug. Fixed now.

**Comment by jesus2099** [comment]
Wow, thanks very much!
I should have taken the time sooner, it has been bugging me for years!
Super great. :bow:

**Comment by jesus2099** [comment]
@jangler thanks again very much for this fix.
I am looking forward to installing the next version. :)

Out of random, I ran my same tune in version 20110101 and it does not have this bug there.
Is it possible?

**Comment by jangler** [comment]
Definitely possible, but that was before I had even used Schism, let alone touched its codebase.

I didn't realize we're pretty much overdue for a new release given the number of commits to master since the last one, so I'll put out a new version tonight or tomorrow.

**Comment by jangler** [comment]
It's out! https://github.com/schismtracker/schismtracker/releases/tag/20180513

**Comment by jesus2099** [comment]
I suggest updating the website: schismtracker/schismtracker.github.io#1. :)
