### ISSUE TITLE
Copying Data From The Message Log Viewer

### ISSUE THREAD

**Issue by ihorn0687** [schismtracker/schismtracker#164]
**I have edited the Schism Tracker code so that it displays the instrument and timestamp in the log viewer.
However, I have no idea whatsoever how to:**

1. Export the logs in a readable file.
_or_
2. Copy and paste messages in the Message Log Viewer

Any help would be gladly appreciated! Thank you.

**Comment by jangler** [comment]
I don't understand exactly what you're doing, but it sounds like the Message Log Viewer is the wrong place to do it. If it's important for you to be able to copy/paste message log text, you've probably modified the message log in a way that's pretty different from how it's intended to be used.

If you've edited the code to display additional log messages, then surely you can just add `fprintf()` instead, or add `fprintf()` to whatever function adds messages to the log. Or even easier, just use `printf()` and redirect the output to a file using the shell.
