### ISSUE TITLE
EQ settings reset when loading a new file or browsing around in the load view

### ISSUE THREAD

**Issue by strongholdmedia** [schismtracker/schismtracker#165]
There is a weird issue that pertains to the equalizer settings.
One configures an EQ setting then saves output configuration (don't know if that does anything or not), with a module loaded and playing (in order to "match" the "expected" settings).
Then one proceeds to load another module (with or without stopping the module currently playing), it loads and playback stops as expected.
Then pressing F5 to play the newly module, it starts, but all the equalizer settings get reset.
*This is only for the voice*, though; every fader remains in their last position configured, and *as soon as one is moved a bit*, the equalizer settings got applied immediately.

I originally thought it is such a "simple" issue of "accidentally resetting" the EQ settings when loading a module, but then found out that *in the load module view*, going to any number of different folders, no change, but *as soon as getting back to the folder the module being played resides in*, the equalizer settings (as per those applied to the engine, not the fader states) reset as well.

**Comment by strongholdmedia** [comment]
It seems that our problem is three-fold.
1. The EQ is not actually "disabled". It is just the scale of 0-127 represents a dynamic scale between **120Hz** and SAMPLE RATE.
2. For some awkward reason, in _csf_reset, SAMPLE RATE is initialized to 4000Hz.
3. For some even more awkward reason, _csf_reset (along with the whole initialization) gets called **8 times** during a module load, and the same number of times during browsing the folder.

Now setting sample rate to 44100 does solve the issue with me.
But I am reluctant to offer that as a solution, due to:

- There seems to be some arcane OPL (AdLib?) quirk that the previous guy who left the comment did not understand that is related to this 4000Hz thing in a way or two, and that may break

- There are some devices that do support 48000Hz and only that, e.g. no 44100Hz nor anything else (this may be solved with using values from the config)

- There may be some obscure or legacy platforms that top out at say, 22050Hz, and their support would cease this way (this may again be solved partially by using the config stuff)

Still, I think it would be cleaner to find out if a "player reset" is really needed this many times. Perhaps the findings could be combined with the above for an acceptable solution.

**Comment by strongholdmedia** [comment]
Basically, it would be the most helpful if anyone could elaborate on any possible OPL3/AdLib/etc support, status, quirks, or anything.

**Comment by jangler** [comment]
For starters, even "global volume" on the F12 screen doesn't affect AdLib instruments. I see the comment you're talking about. I do a lot of AdLib in Schism and can test whether setting the SAMPLE_RATE to something else messes with that. Why on earth would it be set to 4000 Hz in the first place, though?

**Comment by jangler** [comment]
OK, yeah, this is wrong… based on `_csf_set_wave_config()` it's initialized to 4000 initially, then to whatever sample rate SDL_Audio gives. Then if you load a module, it's set to 4000, then to whatever sample rate SDL_Audio gives… then to 4000 again?

Edit: What I'm seeing doesn't match the behavior you describe, though, because calling `_csf_reset()` 8 times would set the sample rate 8 times, and I'm not seeing that. Just once, and not when browsing, just loading.

**Comment by strongholdmedia** [comment]
It doesn't.
Some parts are actually called when either sampling rate, bits, or channel count is changed.
But it is changed like 3-4 times out of 8 only.
But then again, for me it only happens when browsing to a specific folder (in which my old tracks reside).
I try and debug this issue further. Though, for me, _csf_reset() - with setting sampling rate or without - does get called 8 times at every track load. Are you using "pulse on sdl"?

**Comment by jangler** [comment]
Yes, I'm using "pulse on sdl". What are you referring to by "it doesn't"?

**Comment by strongholdmedia** [comment]
With the default 4000 hard-wired to 44100, this is what I have on a module load (debug output code added by me):
```
[DEBUG] csf_set_wave_config(): channels: 64 0; rate: 44100 0, bits: 16 0
[DEBUG] csf_init_player(); reset: 1
[DEBUG] EQ tables: 127 120 13 1195 73 8032 107 14310 
[DEBUG] csf_reset()
[DEBUG] csf_set_wave_config(): channels: 64 64; rate: 44100 44100, bits: 16 16
[DEBUG] csf_init_player(); reset: 0
[DEBUG] EQ tables: 127 120 13 1195 73 8032 107 14310 
[DEBUG] csf_reset()
[DEBUG] csf_set_wave_config(): channels: 64 0; rate: 44100 0, bits: 16 0
[DEBUG] csf_init_player(); reset: 1
[DEBUG] EQ tables: 127 120 13 1195 73 8032 107 14310 
[DEBUG] csf_reset()
[DEBUG] csf_set_wave_config(): channels: 64 64; rate: 44100 44100, bits: 16 16
[DEBUG] csf_init_player(); reset: 0
[DEBUG] EQ tables: 127 120 13 1195 73 8032 107 14310 
[DEBUG] csf_reset()
[DEBUG] csf_set_wave_config(): channels: 64 0; rate: 44100 0, bits: 16 0
[DEBUG] csf_init_player(); reset: 1
[DEBUG] EQ tables: 127 120 13 1195 73 8032 107 14310 
[DEBUG] csf_reset()
[DEBUG] csf_set_wave_config(): channels: 64 64; rate: 44100 44100, bits: 16 16
[DEBUG] csf_init_player(); reset: 0
[DEBUG] EQ tables: 127 120 13 1195 73 8032 107 14310 
[DEBUG] csf_reset()
[DEBUG] csf_set_wave_config(): channels: 64 0; rate: 44100 0, bits: 16 0
[DEBUG] csf_init_player(); reset: 1
[DEBUG] EQ tables: 127 120 13 1195 73 8032 107 14310 
[DEBUG] csf_reset()
[DEBUG] csf_set_wave_config(): channels: 64 64; rate: 44100 44100, bits: 16 16
[DEBUG] csf_init_player(); reset: 0
[DEBUG] EQ tables: 127 120 13 1195 73 8032 107 14310 

```

**Comment by strongholdmedia** [comment]
It is apparent that csf_set_wave_config is called with 0 as bits and 0 as sample rate. Perhaps this is what is called "reset" (but even then it is wrong and should be changed).

**Comment by strongholdmedia** [comment]
> Yes, I'm using "pulse on sdl". What are you referring to by "it doesn't"?

Sorry, I meant "sample rate isn't always "changed" in the regular sense when _csf_reset() gets called".

**Comment by jangler** [comment]
Fixed in ba69339 (I think); see #102.

**Comment by strongholdmedia** [comment]
Whoa.
Look who's got the free time. :D
Let me check it.

**Comment by strongholdmedia** [comment]
The situation is two-fold.
* Once the equalizer set, it is _indeed working_ now, that is, the settings are not reset anymore. Thanks for that.
* Apparently, however, while the positions of the equalizer "sliders" are saved and displayed properly, _on startup_, the equalizer settings are not applied. I need to manually move one or another for the settings to be applied.
(Then again, all is ok until restarting/exiting the program.)

I am not quite certain this belongs to this issue (or not), I've just written it here, since it is _apparently_ done by the same code.

**Comment by jangler** [comment]
Different code; `set_eq_gains()` is only ever called by `song_init_eq()`, which is only ever called by the preferences page. For some reason. As far as I can tell, `song_init_eq()` should be called in `csf_init_player()` instead of `initialize_eq()`. I'll just fix that now instead of opening a new issue for it.

**Comment by strongholdmedia** [comment]
Wow. It works a treat. Thanks for that.
