### ISSUE TITLE
Carbon Component Manager (OS X)

### ISSUE THREAD

**Issue by ian128K** [schismtracker/schismtracker#166]
I was just going through the steps to compile Schism Tracker on OS X, and when testing it from the command line, I got the following notification:

```
2018-06-27 13:25:32.848 schismtracker[5143:21372909] 13:25:32.847 WARNING:  140: This
application, or a library it uses, is using the deprecated Carbon Component Manager for hosting
Audio Units. Support for this will be removed in a future release. Also, this makes the host
incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
```

The app still ran okay, but I thought I'd pass this along. (I'm running OS X 10.11.6.)

**Comment by jangler** [comment]
Yeah, known issue. It's a problem in SDL1.2, so an SDL2 port is required to fix it; see #33.
