### ISSUE TITLE
unsupported mod files

### ISSUE THREAD

**Issue by Peter4711** [schismtracker/schismtracker#167]
hello

i tried to play some mod files from my old cds and found a few files that dont't play with schismtracker.

schismtracker said : unsupported file format in the info box

these mod files play with all other dos and windows mod players that i tried without a problem.

(i tried: impulse tracker, cubic player, visual player, xtc, inertia, mpxplay with modplug xmms and foobar2k with libopenmpt.)

impulse tracker 2.1.4 says: "Old Amiga-Mod format ?" and plays them
foobar2k with libopenmpt said these files are created with:
ultimate soundtracker, master soundtracker, sound tracker 2.0. and d.o.c. sound tracker II
may be this info helps a bit.

would be nice if support for these old files could be added.

here some of these files to test

https://www99.zippyshare.com/v/c92V4VSt/file.html

greets
peter

**Comment by jangler** [comment]
These files don't have any 4-byte tag identifying the tracker they were made in, which makes file format identification annoying.

I imagine the way to deal with this would be, after checking for every other supported file type. to try to load the data in the old MOD format and see if it makes sense.

**Comment by Peter4711** [comment]
would be great if (one of) the next release(s) could play these old files.

foobar2k with libopenmpt can somehow identify the tracker ( and show it under properties) but thats not that important.
main thing is that they are playable.

foobar2k with openmpt and asio output may offer best sound quality for playing mod files over a usb dac but it looks boring :-)

 these old amiga mod files are classic 4 channel mod files so should't be too complex :-)

**Comment by jangler** [comment]
Fixed in https://github.com/schismtracker/schismtracker/commit/3302e8e8564ae6b2489cc1d6029a1358739ba6e6.

**Comment by Peter4711** [comment]
thanks  this are good news :-)

(time to wait for next release :-) )

**Comment by sagamusix** [comment]
Please note: 15-sample MODs are not just ProTracker MODs with less samples. There are multiple variants of the format with (very) different pattern interpretations, and SchismTracker just does the bare minimum to *load* those files - it will not *play* many of them correctly, though. The OpenMPT code could be used as a starting point for detecting and correctly loading these sub-formats. But keep in mind that if you just want to listen to those files, SchismTracker is currently really not a good tool for that.

**Comment by jangler** [comment]
It seemed to work fine on the modules Peter provided at least. I was using https://www.aes.id.au/modformat.html for reference, which mentioned untagged files but not any pattern format deviations; I'll make a note to browse the OpenMPT code when I get a chance.

But Saga makes a point that I should have made, which is that Schism Tracker *really* only has one playback routine, which is for the IT format (plus AdLib instruments for S3M files). Other module formats are essentially converted to IT when loaded, with varying degrees of lossiness depending on how incompatible the formats are and how thoroughly the programmer implemented the conversion.

So yes, if you want to make sure you're playing MOD files back correctly, use another tool, like probably anything using libopenmpt.

**Comment by Peter4711** [comment]
thx for the info

your homepage says "... The player is based on a highly modified version of the ModPlug engine..."
so i thought it has the same playback engine as openmpt.
i was a bit surprised that it could not play these old mod files. i thought it should have the same compatibility and playback quality as openmpt.

seems best way to play mod files are openmpt123 (no gui makes it uncomfortable)
or foobar2k with openmpt (sounds good but looks super boring :-) )

**Comment by jangler** [comment]
Despite the name, OpenMPT isn't the same as ModPlug. Schism and OpenMPT are *both* based on the ModPlug engine (which is/was not very accurate; see the [player abuse tests](https://github.com/schismtracker/schismtracker/wiki/Player-abuse-tests)) and diverged in different directions. OpenMPT opted to fully implement playback routines for the more popular module formats, while Schism focused mainly on IT, since its main purpose was to be a clone of the original Impulse Tracker.

I can understand the confusion, though. Probably a common misconception. 😛

**Comment by Peter4711** [comment]
"Schism focused mainly on IT" okidoki

it sounds not too bad when you compare schism with other players/trackers

ult files (gus ultra tracker) sound better with schism compared to ultra tracker and gus.
open cubic player adds a strange filter (which cannot be disabled) to the playback.
sounds very bad especially with headphones. 
the old impulse tracker also had some bugs (with soundblaster 16 the interpolation is not very good and with gus there are some cracks with some files.


why you add support for many other mod formats when its only desigend for it and plays other formats not accurate ?

**Comment by sagamusix** [comment]
> why you add support for many other mod formats when its only desigend 
> for it and plays other formats not accurate ?

Most of this support comes from the ModPlug engine (but was rewritten at 
some point, so it's actually more accurate than ModPlug in many cases), 
but the much more important thing is that it's not necessarily meant to 
have "perfect" playback in Schism - it's more intended so that you can 
import those old files in various formats, mess around with them, but 
not necessarily play them 100% correctly.

**Comment by Peter4711** [comment]
do you have a release date already for next version ( with the fix) ?
even when playback is not 100% accurate its still very good :-)

atm i use inertia player and impulse tracker with gus.
but gus can keep 44,1 khz only with 14 channels or less and with 32 channels it goes down to 16khz.

**Comment by jangler** [comment]
Yeah, I guess we can do a new one now. I'm making a note but I might not get to it immediately.

**Comment by jangler** [comment]
Sorry it took a while—the new release is out.

https://github.com/schismtracker/schismtracker/releases/tag/20180810

**Comment by Peter4711** [comment]
cool :-)
time to play some mods.

btw: on your homepage only the 32 bit version for windows is shown.
