### ISSUE TITLE
Resizing window messes up the color palette

### ISSUE THREAD

**Issue by asbjornu** [schismtracker/schismtracker#170]
When the Schism Tracker window is resized on macOS 10.12.6, the color palette is messed up and everything turns to a blue tint.

![Schism Tracker with messed up color palette](https://user-images.githubusercontent.com/12283/43248328-cfa323fa-90b7-11e8-9289-9ff8db20c27e.png)

**Comment by PeeHaa** [comment]
Dupe of https://github.com/schismtracker/schismtracker/issues/168 ?

**Comment by asbjornu** [comment]
Yep.
