### ISSUE TITLE
macOS version requirement

### ISSUE THREAD

**Issue by asbjornu** [schismtracker/schismtracker#172]
The latest build of Schism Tracker for macOS claims to require macOS 10.13 or later. I'm not sure why this is, because in Travis we specify macOS image from `beta-xcode6.1` up to `xcode8` which according to [Travis documentation](https://docs.travis-ci.com/user/reference/osx/#os-x-version) should mean we compile on nothing newer than macOS 10.11.

![screen shot 2018-08-16 at 11 10 43](https://user-images.githubusercontent.com/12283/44199685-0d22cd00-a145-11e8-9ecb-adf431ad5494.png)

However the case may be, [the solution might be](https://stackoverflow.com/a/39688949/61818) to add the `-mmacosx-version-min=10.11` flag to `gcc` when compiling on macOS. Is this going to cause any problems when compiling on other platforms or will the flag be ignored then?

The strangest thing about this is that I'm unable to reproduce the problem locally. Every build I do of Schism Tracker on my Mac works.

**Comment by sagamusix** [comment]
It is indeed correct to specify `MACOSX_DEPLOYMENT_TARGET=10.11` (environment variable) or `-mmacosx-version-min=10.11` (compiler option), and that way you shouldn't even need to use an outdated xcode image.
