### ISSUE TITLE
macOS release build not including SDL

### ISSUE THREAD

**Issue by syneryder** [schismtracker/schismtracker#175]
Hi everyone,

When launching the release build for macOS (I'm using 20180810), Schism Tracker crashes immediately:

```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/sdl/lib/libSDL-1.2.0.dylib
  Referenced from: /Applications/Schism Tracker.app/Contents/MacOS/schismtracker
  Reason: image not found

```

I tried installing SDL 1.2.15 from the SDL website (ie the Framework file from SDL-1.2.15.dmg) in case that's what I was meant to do, but I still get the same error on launch.

I'm running macOS 10.13, if it makes a difference.

**Comment by jangler** [comment]
Maybe it makes a difference that Schism is (for some reason? apparently?) looking for libSDL-1.2.0 instead of 1.2.15? brew might honestly be the best bet for installing Schism on macOS; people seem to have had success with that and I think the available package is at least reasonably up to date. I can't offer much specific help because I really don't know much about macOS (and I don't think the other organization members do, either).

**Comment by syneryder** [comment]
Ahh, I missed that there hasn't been a Mac developer on the team for a while.  I've found a workaround, and have a few clues to share if someone decides to try debugging it later:

* I also have an old copy of 20120105 for macOS, and it runs. It had sdl.dylib included in the Contents/MacOS folder of the executable - no external SDL install was required.  But that version assigns the audio to "dummy", and when loading a song it reports "Failed to start CoreAudio: AudioUnitSetProperty (kAudioUnitProperty_SetInp"

* [This github thread](https://github.com/FrozenSand/UrbanTerror4/issues/295) helped me a lot. When I downloaded the specific libSDL-1.2.0.dylib compiled for the ofxUrgDevice project linked on that page, and used it to replace the sdl.dylib in the executable of that old 20120105 version of Schism Tracker (renaming it to sdl.dylib), it now detected the CoreAudio device (ie the built-in sound on macOS) and played audio.

* The same dylib file from ofxUrgDevice also works with Schism Tracker 20180810, but I have to manually create a /usr/local/opt/sdl/lib/ folder on my machine, and copy the libSDL-1.2.0.dylib there.  The executable seems to be hard coded to look in that specific folder for that filename. But once I do that, the latest 20180810 version runs on macOS 10.13.

Anyway, hope that maybe helps someone!

**Comment by woutgg** [comment]
The path is indeed hard-coded into the executable (and can be inspected using `otool -L /Applications/Schism\ Tracker.app/Contents/MacOS/schismtracker`).

You can actually change this path. For instance to get it to work with libsdl installed using MacPorts, I ran this: `install_name_tool -change /usr/local/opt/sdl/lib/libSDL-1.2.0.dylib /opt/local/lib/libSDL-1.2.0.dylib /Applications/Schism\ Tracker.app/Contents/MacOS/schismtracker` and then the program runs fine.
This also works with the dylib @syneryder found if you place that under the 'Contents' directory of the app bundle and change the path accordingly: `install_name_tool -change /usr/local/opt/sdl/lib/libSDL-1.2.0.dylib @executable_path/../libSDL-1.2.0.dylib /Applications/Schism\ Tracker.app/Contents/MacOS/schismtracker`.

Trying the same with the framework downloaded from the libsdl website did not work, I think their build is not compatible anymore (at least with OSX 10.14).

The nicest way to solve this I think, would be to include the sdl framework or single dylib in the application bundle and set the path using `@executable_path` like described here: https://www.mikeash.com/pyblog/friday-qa-2009-11-06-linking-and-install-names.html.

I'd be happy to test a new version, or maybe even have a look at fixing the build if needed.

Btw, the brew version does not work for me: it opens a blank window and populates the menu bar but nothing beyond that.

**Comment by jangler** [comment]
That sounds viable, although it is strange that the dylib provided by libsdl.org doesn't work, since they are both SDL 1.2.15. I'll get to this sometime this week, although I can't test whether the end result "works" myself.

**Comment by woutgg** [comment]
It seems the 'compatibility_version' in their dylib is incorrect (perhaps the same cause as discussed [here](https://bugzilla.libsdl.org/show_bug.cgi?id=2915) if anyone is interested). It is set to '1.0.0', while in the one provided by brew it is '12.0.0', which is what the schismtracker binary expects.

I think building against the one provided by libsdl.org would work fine though, but would of course require users to manually install it.

When you've got a new build, I can give it a go if you like.

**Comment by jangler** [comment]
So obviously I didn't get to this yet, but I haven't forgotten about it…

**Comment by jangler** [comment]
https://github.com/schismtracker/schismtracker/releases/tag/issue-175.0

Anyone want to test this? Since I don't have a macOS environment myself, I'm pretty much shooting blind.

**Comment by syneryder** [comment]
I have bad news, but also good news! The bad news is that this build crashes on launch with this error:

```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../libSDL-1.2.0.dylib
  Referenced from: /private/var/folders/*/Schism Tracker.app/Contents/MacOS/schismtracker
  Reason: image not found
```

The good news? You just need to remove that extra ../ after the @executable_path when loading SDL. If I move the SDL library out of the Contents/MacOS folder and up a level (ie into Contents only), everything works on macOS 10.13! But the SDL dylib library is meant to be in that MacOS folder, so it's just the extra ../ that needs to be removed wherever the library is getting loaded, don't move the actual dylib.

Thank you so much for working on this!

**Comment by jangler** [comment]
How about https://github.com/schismtracker/schismtracker/releases/tag/issue-175.1 ?

**Comment by syneryder** [comment]
Brilliant! This works for me out-of-the-box on macOS 10.13.

Now the other bug is that I don't see a "Buy me a beer / coffee" button on the Schism Tracker website to say thanks :)

**Comment by woutgg** [comment]
I can confirm, it works fine now. :)
Thank you for your work on fixing it!

**Comment by jangler** [comment]
Great, I'll publish a "real" release then and update whatever macOS documentation exists.
