### ISSUE TITLE
Fix keyboard layout for schism tracker for laptops

### ISSUE THREAD

**Issue by babatunde3** [schismtracker/schismtracker#180]

**Comment by esaruoho** [comment]
Meaning what, @babatunde3 ?

**Comment by babatunde3** [comment]
well...i used f# keys, but it adds notes. that's why it's broken.

**Comment by jangler** [comment]
Operating system? Picture of keyboard layout?

**Comment by esaruoho** [comment]
Dude PLEASE be more informative than u have been thus far. 

What is:
Schismtracker version. 
Operating system. 
Laptop make and model. 
OS language. 
Keyboard layout (picture and OS configuration).
@babatunde3

**Comment by babatunde3** [comment]
Windows 10
an hp 16.3 laptop 17-by0061st
A laptop keyboard layout
i'm using the latest version.
I don't want notes on the fn keys.
OS Language: English
