### ISSUE TITLE
Badly displayed characters

### ISSUE THREAD

**Issue by trebmuh** [schismtracker/schismtracker#184]
In this image (where I removed some folder names for a better understanding), I have 3 directories with French accents : "Modèles", "Téléchargements", and "Vidéos", but the accentuated characters are wrongly displayed:

![schism-caracteres-bizarres](https://user-images.githubusercontent.com/8705846/50388633-be9dc480-071c-11e9-83e0-a3f6b288eec3.png)

**Comment by sagamusix** [comment]
Duplicate of issue #67. Long story short: It's not trivial at all to fix this due to Schism Tracker essentially emulating a DOS VGA screen. It cannot just display arbitrary characters outside of the ASCII range.

**Comment by trebmuh** [comment]
Thanks for redirecting to the relevant issue.
Sorry for the duplicate.
