### ISSUE TITLE
Tutorial on MIDI

### ISSUE THREAD

**Issue by firolightfog** [schismtracker/schismtracker#185]
Hi,
I'd love to watch a tutorial on MIDI usage. 
I just can't make a single tune playing the instruments of the enabled MS GS Wavetable Synth even. I'd like to use Schism Tracker to control external MIDI (or even eurorack?) devices but I'm just not lucky/clever enough. :(
Regards, Andras

**Comment by esaruoho** [comment]
color me interested. have you tried external midi devices? and have you gone to the last tab in F4 to set the midiexternal channels etc?

**Comment by firolightfog** [comment]
Hi,
I tried to control a Korg Volca Sample and also the internal MS GS Wavetable Synth. I 'enabled' some fields in Shift-F1 screen and I was fooling around with the F4/Pitch MIDI section with not luck. I don't feel I know what I'm doing. (See the famous "infinite monkey theorem".) :(
Cheers, A.

**Comment by vcaputo** [comment]
The MIDI.TXT fie included with impulse tracker, the program schismtracker attempts to replicate, has some instructions i've included below:

```
Enabling MIDI
=============

To enable MIDI output, you must first have IT on Instrument control mode
rather than Sample control mode. To do this, press F12 to go to the Song
Variables screen and switch control to 'Instruments' if you haven't already
done so.


MIDI & Instruments
==================

MIDI Channel
------------

New to the Pitch section of the Instrument screen (press F4 and select the
"Pitch" button) are the sliders "MIDI Channel", "MIDI Program" and "MIDI
Bank". Once the MIDI Channel value for that instrument is set to a value
other than zero, IT will send out MIDI data whenever that instrument is
encountered in a pattern, on that particular MIDI Channel. What data IT
actually sends through the MIDI port will be a note on command, although
this will be discussed in more detail later.

MIDI Program/MIDI Bank
----------------------

The MIDI Program and MIDI Bank sliders work in a similar manner to each
other. If they have a value set to -1, IT will not transmit a program change
message nor a bank change message for that instrument. If you specifically
set a MIDI Program for that instrument, IT will send a 'program change'
message along with the 'note on' message.

The MIDI Bank instrument setting is also the same; IT will not send a bank
change message if the MIDI Bank slider is set to Off (ie: has a value of
-01). If the MIDI Bank setting is active for that instrument, IT will send
it along with the note on message as well.

Summary
-------

IT will always send a 'note on' command for a particular MIDI channel
whenever a MIDI instrument is encountered in the pattern. (A MIDI instrument
is simply an instrument where the MIDI Channel value has been set to
something other than "Off"). IT will also send a program change command and/or
a bank change command along with the note on command if they are set active.
```

Grab a copy of the impulse tracker zip yourself, there's more information in the bundled MIDI.TXT file.

I've only done rudimentary MIDI testing using schismtracker, when I was improving the MIDI support.  So I can't speak to how much of what's described in the advanced sections of MIDI.TXT apply directly to schismtracker.  There are probably more bugs, based on what I experienced testing the basics (it was largely unusable).  But they probably won't get fixed until people try using it and report them.

**Comment by firolightfog** [comment]
Thanks guys. MIDI.txt did help a lot. I already hear something. I'm getting closer to what I want. (Still not there though. :)) 
Cheers, A.
