### ISSUE TITLE
source code release tarball lacks configure script

### ISSUE THREAD

**Issue by rofl0r** [schismtracker/schismtracker#186]
please provide future release tarballs with a pre-generated configure script, so source users don't need to have autoconf/automake installed. thanks!

**Comment by rofl0r** [comment]
i also noticed the configure script (after i generated it myself) checks for python and then uses it to generate some intermediate files. it would be nice if those files could be generated and shipped as part of the source tarball, and only generated if missing/outdated, in order to remove the build dependency on python.

**Comment by rofl0r** [comment]
thanks, much appreciated, even after 5 years wait. unfortunately the python dependency is still there. maybe i can be bothered to update your CI job for the release with putting the generated files into the tarball at some point.

**Comment by mrpapersonic** [comment]
would something like perl be better instead of python? we only really need it to build the help text:
https://github.com/schismtracker/schismtracker/blob/master/scripts/genhelp.py

it's possible to do this with shell scripting but since I want the build system to be as portable as possible that's not really on the table (i.e. `iconv` isn't guaranteed to support UTF-8 nor CP437)

**Comment by rofl0r** [comment]
that would be overkill. imo it's best to just create auxiliary files with dependencies during the "make dist" workflow when preparing a release tarball and then at configure time:
- check if the dependency (python) exists
- if yes, proceed as usual
- if not, and the pre-generated file exists, touch(1) it, so it has a newer timestamp than its input files, and then make will automatically skip rebuilding it.

i did the same for tinyproxy, so users dont need the framework for generating manpages installed (at first it was requiring "a2x" which pulled in like 100mb of dependencies on debian, meanwhile we switched to pod2man which is installed together with perl).
so maybe tinyproxy's configure.ac/Makefile.am can serve as an example here.
