### ISSUE TITLE
No audio when importing a MIDI file

### ISSUE THREAD

**Issue by JesseTG** [schismtracker/schismtracker#190]
It is entirely possible I'm not using schismtracker correctly.  But searching for "schismtracker no audio" gets me no results on Google, so here I am.

I'm trying to import [this MIDI file](https://github.com/schismtracker/schismtracker/files/2857919/The_Entertainer.mid.gz) and play it using [this sample](https://github.com/schismtracker/schismtracker/files/2857923/YM2413_03_PIANO_011.wav.gz).  However, when I try to play it, I hear no audio.  I don't otherwise experience any errors, crashes, or other unusual behavior.

Here's some relevant information:

- The MIDI file and sample are attached with `gzip` compression
- This is on Ubuntu 18.10, with schismtracker built on August 14, 2018.
- The MIDI file and sample are both valid, and are correctly imported by other software (including LMMS and SunVox)
- I am not having other problems with my audio; I can cue up music in other software (including audacious) without any difficulty.
- I've tried playing the MIDI with both the stock instrument and the provided sample.  Same result either way.
- My installation is using the `pulse` audio driver.

I don't know how to get relevant information about my audio drivers, but if you need it I can provide it.

Any thoughts?

**Comment by jangler** [comment]
Looks like MIDI import is broken; I don't see any note data being loaded.

**Comment by JesseTG** [comment]
Do you get that problem with other MIDI files?  (I'm not near a computer where I can check right now)

**Comment by jangler** [comment]
No, I've never tested MIDI import thoroughly, but import has worked *okay* when I've used it.

**Comment by JesseTG** [comment]
Can you post a MIDI file that works for you?  I want to see if I can import it and play it.  I tried
[another file](https://github.com/schismtracker/schismtracker/files/2861828/The_Entertainer_-_Scott_Joplin.mid.gz), same results.

**Comment by jangler** [comment]
This one works relatively well—but MIDI import in general is pretty poor and minimal, it manages to butcher something about just about every file.

[crt_monitor_lizard.zip](https://github.com/schismtracker/schismtracker/files/2861956/crt_monitor_lizard.zip)

**Comment by JesseTG** [comment]
The MIDI you provide **does** produce audio when imported on my machine.  So it's not a driver issue or anything.

**Comment by JesseTG** [comment]
Actually, the first MIDI I imported has data on Channel 8.

**Comment by jangler** [comment]
Yeah, only note off commands.

**Comment by sagamusix** [comment]
This was caused by a faulty implementation of meta events. The file loads fine now.
