### ISSUE TITLE
that audio playback, 

### ISSUE THREAD

**Issue by Atekuro95** [schismtracker/schismtracker#191]
it's sounding a little...off, I tried the windows edition of fasttracker 2, it sounded accurate, but when I tried schism tracker, it's the sound chip in this impulse tracker clone, I can't explain it.

**Comment by esaruoho** [comment]
is there like any chance you could provide .wav proof or even mention a song? without any context, well, there's no context!

p.s. please attach a song, or provide a link, or take a ft2 wav and a schismtracker wav or even mention the format of the module?! @BradRedden

**Comment by Atekuro95** [comment]
[Bandicam.zip](https://github.com/schismtracker/schismtracker/files/2907815/Bandicam.zip)
hear them closely.

**Comment by jangler** [comment]
Schism Tracker is an Impulse Tracker clone and only supports playing IT modules. It will load and internally convert XM to IT with some degree of accuracy, but it makes no guarantee that playback will match that of FT2.
