### ISSUE TITLE
macOS 20181223 White Screen on Boot

### ISSUE THREAD

**Issue by craben20** [schismtracker/schismtracker#193]
When launching the application, no warnings are received in the terminal, but only a white/grey screen is presented on boot:

![Schism Tracker White Blank Screen](https://user-images.githubusercontent.com/44365857/57941198-333cef80-78c6-11e9-97d8-10c24765671b.png)

The application also seems to lock up.

**Comment by jangler** [comment]
Sounds like the issue woutgg mentioned in https://github.com/schismtracker/schismtracker/issues/175, but I'll leave this open for now since the solutions / conditions for closing might not necessarily overlap.

**Comment by woutgg** [comment]
Note that this only happened with the build installed by homebrew, the new app bundle @jangler built works like a charm.

I'm not sure what's going on/wrong with the brew version, it just seems to hang somewhere. It doesn't react to the quit key (cmd-q) either. It definitely finds SDL though, as just breaking from within lldb shows SDL_main somewhere within the stacktrace.

**Comment by jangler** [comment]
I don't have anything to do with the brew formula and the problem seems to be fixed in the latest app bundle, so I'm closing this. Grab the 20190614 version from http://schismtracker.org/ when it becomes available (later today?).
