### ISSUE TITLE
Panning view (Alt+V) *

### ISSUE THREAD

**Issue by zeffii** [schismtracker/schismtracker#20]
in the F1 there's a star beside this command, what does that mean?

I recall that the volume track had a secondary panning view, which used differently colored digits to indicate you were editing a track panning. Is my brain deceiving me or is this function not implemented in schism / put under a different shortcut.

**Comment by jangler** [comment]
Nah, it's the same as in Impulse Tracker. In the Pattern Edit Keys helptext there's:

```
`                Note off (═══) / Panning Toggle
```

… The character hardly shows up here, and it's easy to miss in the Schism/Impulse help, but it's the backquote character (which shares a key with ~ on my keyboard).

Regarding the `(*)`, this is also documented in the Pattern Edit Keys helptext:

```
Ctrl-Backspace   Undo - any function with  (*) can be undone
```

It would be nice if the helptext were searchable. Maybe that's another feature to implement…

**Comment by zeffii** [comment]
OK! sweet! backtick! :)  

``` python
`
```

apologies for asking this stuff. [i'm too excited.](http://www.buzztunes.org/music/zeffii/first-schizm)
