### ISSUE TITLE
Instrument / sample pan should not override channel pan

### ISSUE THREAD

**Issue by sagamusix** [schismtracker/schismtracker#200]
Relevant OpenMPT test case: [PanResetInstr.it](https://wiki.openmpt.org/Development:_Test_Cases/IT#PanResetInstr.it)
Relevant OpenMPT code revision: [11856](https://source.openmpt.org/browse/openmpt?op=comp&compare[]=%2F@11855&compare[]=%2F@11856)

It turns out that instrument and sample pan should not change the channel panning. For example, consider instrument 1 has panning = 64, instrument 2 has no panning. Channel panning at the start of the pattern is 32 + surround.
```
... .. <-- pan = 32 + surround
C-5 01 <-- pan = 64
C-5 02 <-- pan = 32 + surround
```
Any panning commands undo this mechanism as they are applied to the channel panning.

OpenMPT already had the relevant mechanism in place to deal with pan swing (in a different way than Schism does), but I think Schism is lacking this code, so porting the fix over won't be quite as simple as just copying everything.

**Comment by jangler** [comment]
How do panning slides and panbrello interact with this?

**Comment by sagamusix** [comment]
Panning slides are like regular panning commands, i.e. they set the channel panning.
Panbrello is an offset on top of the current note panning and is always reset on the next note. If you applied panbrello on the second line of the example above, only that row would change, but if you applied a pan slide to that row, it would change the panning of the following row.
