### ISSUE TITLE
Can't change NNA selection etc on F4 page using keyboard

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#204]
Only the mouse works. Maybe introduced by f4c945a.

**Comment by vcaputo** [comment]
Indeed, reverting  https://github.com/schismtracker/schismtracker/commit/f4c945aee8aa8ade11945b538f3792e1ad8e4c33 seems to restore keyboard NNA selection.

**Comment by vcaputo** [comment]
I did a quick test with just https://github.com/schismtracker/schismtracker/commit/f4c945aee8aa8ade11945b538f3792e1ad8e4c33#diff-b352bb4c44acd757250df56e4d309a3aR425 removed, and it seems to work.

Unfortunately I don't seem to have any of my old code where I experimented with fixing this last year, but ISTR it was just a matter of clearing the existing depressed state - I wasn't setting it for anything afterwards.

The `p_widgets[widget].d.togglebutton.state = 1` is already there, and just glancing at the results of a `grep -r depressed` it appears `n` is assigned, `1` is never assigned, it doesn't appear to be a boolean but an index.

So I don't think your assignment of `1` to depressed is correct.

**Comment by jangler** [comment]
Still doesn't work for me with that line removed.

**Comment by jangler** [comment]
Removing both lines does fix the problem, but of course it also reintroduces #140. Guess I'll need to find a more specific way of fixing that.

**Comment by vcaputo** [comment]
That's strange, I just retested here again and simply removing that line from HEAD seems to make everything work properly.  Seems unlikely that we'd see such different outcomes with this particular code.

**Comment by jangler** [comment]
`depressed` is always set to 0 or 1 in the code; in the `widget->depressed = n` lines, `n` is just a poorly named variable assigned things like `(k->state == KEY_PRESS) ? 1 : 0`. I agree that seeing different results is strange, yet here we are…

**Comment by laamaa** [comment]
I tested also and reverting the commit fixed the problem for me as well - the menu works as should w/ mouse and keyboard (on Linux)

**Comment by jangler** [comment]
I just reverted the commit, since this has gone on for too long and having functioning buttons is more important than the appearance when clicked.
