### ISSUE TITLE
Exported file size displayed incorrectly for mono exports

### ISSUE THREAD

**Issue by Abc120** [schismtracker/schismtracker#205]
When I use "Export..." from menu (Shift+F10), sometimes mono files are being generated,
sometimes stereo ones. It seems like a bug because the modules I tested surely have more than
one channel. I thought it has something to do with not being IT-format, so I converted them to IT using "Save As..." (F10), but the result was the same to the latest bit. It's really disappointing,
because while Schism Tracker sounds the best of all, it cannot be used as a player (correct me if
I'm wrong), and I have to export to WAV for listening to it in another program. I attached the
sample module which results in mono WAV.
    P.S.: BTW, Schism shows the size of stereo file when exporting, but it's half that size actually.
[4 Guinevere's theme.zip](https://github.com/schismtracker/schismtracker/files/3490104/4.Guinevere.s.theme.zip)

**Comment by jangler** [comment]
Mono WAV files will be written if "Playback" on the F12 screen is set to mono, as this particular S3M happens to be. You can export stereo by changing the setting.

- Schism Tracker can be used as a player. F5 is the "play song" hotkey.
- Mono/stereo doesn't have anything to do with the number of channels in a module. Panning is the relevant factor.

You're right though; exported file size is displayed incorrectly for mono exports.

**Comment by Abc120** [comment]
Thank you for quick response! "Playback" setting does the trick. What do you think, which one sounds more natural, mono or stereo, for this module?
And yes, F5 can be used to play the song but it doesn't stop in the end, it's being repeated indefinitely. The typical player would start playing the next module in the list which is the desired behavior for me.

**Comment by sagamusix** [comment]
If you are interested in external players, give [players based on libopenmpt](https://wiki.openmpt.org/Libopenmpt#Players) a try - libopenmpt and Schism Tracker originate from the same code so playback will sound very similar (but more accurate for S3M, because Schism Tracker only focuses on IT playback)

**Comment by Abc120** [comment]
Thanks for your suggestions! I think, however, Schism is still superior for IT modules:)
