### ISSUE TITLE
Playback gets stuck on Sustain Loop point when Multichannel Playback enabled

### ISSUE THREAD

**Issue by zoikkis** [schismtracker/schismtracker#207]
On Instruments page: If you have volume envelope active, Sustain Loop active, Multichannel playback enabled and then play some chords, played notes often get stuck at Sustain Loop point and F8 has to be pressed to stop the stuck notes from playing infinitely.

I'm using a version that has been built from the latest code with the exception that I reverted f4c945a to get rid of "Can't change NNA selection etc on F4 page using keyboard #204"). This because I only use keyboard with Schismtracker.

**Comment by mrpapersonic** [comment]
~5 years later... :)

Looks like this isn't relevant anymore, the original commit was reverted on master ages ago.
