### ISSUE TITLE
Filter settings are not reset when changing instrument

### ISSUE THREAD

**Issue by zoikkis** [schismtracker/schismtracker#209]
In Instruments page, if you are playing an instrument that has some default cutoff and resonance settings applied, and then change to some other instrument that has default cutoff and resonance set to "off", the cutoff and resonance settings from the previous instrument apply to the instrument that has them turned off.

This can be prevented if you press "F8" after changing the instrument, but the cutoff/resonance settings should probably be resetted automatically when you change the instrument.

**Comment by sagamusix** [comment]
Should be fixed finally...
