### ISSUE TITLE
New schism tracker feature Request: Convert stereo samples to mono samples

### ISSUE THREAD

**Issue by babatunde3** [schismtracker/schismtracker#210]
Can you add "Convert Stereo samples to Mono samples?"

**Comment by esaruoho** [comment]
@babatunde3
proposal: please change issue title to "New feature request: Convert stereo samples to mono samples"

**Comment by jangler** [comment]
You can already do this via Alt-Shift-D on the sample list.

**Comment by babatunde3** [comment]
alt+shift+d is deleting samples

**Comment by jangler** [comment]
Incorrect; Alt-D deletes samples. Make sure you're using the latest version of Schism Tracker; this was implemented in July.
