### ISSUE TITLE
MacOS blank window

### ISSUE THREAD

**Issue by fuzzy76** [schismtracker/schismtracker#211]
When I start the current macOS build I get a blank window, and non-working menus. The only thing that works is closing the window which quits.

**Comment by esaruoho** [comment]
@fuzzy76 which macOS version are you running, and which Schism Tracker build are you running, please?

**Comment by fuzzy76** [comment]
macOS Mojave 10.14.6 (latest stable)
Schismtracker installed using homebrew: https://github.com/Homebrew/homebrew-core/blob/master/Formula/schismtracker.rb

It seems to use the latest release (20190805).

**Comment by jangler** [comment]
We used to recommend Homebrew for macOS, but some users were reporting serious problems like this one (and we didn't make the formula). Try the latest macOS build from https://github.com/schismtracker/schismtracker/releases instead.

**Comment by fuzzy76** [comment]
That worked great! I thought the homebrew package used your release, but it installs as a commandline version, and not as a full app like your release contains. Thanks! I'll report this to homebrew.
