### ISSUE TITLE
SchismTracker version number discussion

### ISSUE THREAD

**Issue by sagamusix** [schismtracker/schismtracker#212]
It's exactly one year and one week (2020-10-28) until SchismTracker version numbers, as stored in the IT and S3M file headers, will overflow. 2020-10-28 will be version 0xFFF, which is considered to be a reserved version number for anything past 2020-10-27.

The way I see it, there are four possibilities:

1. Reserve another tracker ID (the highest nibble in the cwtv value) and continue using the same version scheme. We will be running out of values again 11 years later (to quote the version number handling code: "assuming Schism Tracker still exists then"). There are only 16 of them and many are already used, so I think this idea doesn't scale.
2. Reserve another tracker ID and use a versioning scheme that is more conservative in number usage, such as using month-accurate versions rather than day-accurate versions. Not a very desirable solution either.
3. Write 0xFFF in the cwtv field and offload the exact version number to another place. This place could for example be the 32-bit "reserved" field in the IT header. Currently SchismTracker doesn't use it for anything and just puts 0 there. IT actually uses it for storing the total edit time, but nobody else does that. OpenMPT uses it to indicate whether a file was saved with compatibility export or not. I think this should be the preferred option as it doesn't modify the file structure in any way. The S3M header also has 8 consecutive reserved bytes so the approach works for both formats.
4. Same as 3, but write the exact version information in a different place (e.g. after MIDI macros).

For sake of simplicity (i.e. code reuse), I suggest that the format of the new field follows that of cwtv, minus the tracker ID in the high nibble obviously, and *maybe* without adding 0x50 to the value.

**Comment by jangler** [comment]
3 is definitely my preferred option as well.

**Comment by sagamusix** [comment]
Note that even a 16-bit field would be enough (0xFFFF would in the year 2189), but since there is only one reserved field in the IT file header, and it's a 32-bit field, I think we can ignore that and have version numbers that will last for a few more millenia!

**Comment by sagamusix** [comment]
Here's a first draft: 7357b8e73974a969284b14e08f431331d3778e00

I figured out that IT saves its edit timer in those reserved bytes in the S3M header; Interestingly the edit timer is stored in the "middle" four bytes, while the first two and last two bytes are unused. I thought it would be nice to potentially have both the edit timer and extended version information without any layout changes, so I opted for only using the first two reserved bytes in S3M (as mentioned above, this is save until the year 2189).

If we decide not to care about those two values overlapping, I would suggest to place the version info with the same 2-byte offset, to simplify code that can handle both this extended version info and IT's edit timer.

**Comment by jangler** [comment]
Although no module will have both a correct edit timer and a new Schism version number, I'd like to preserve edit timer data anyway – so this approach sounds good.

**Comment by jangler** [comment]
Just from reading over the draft, I don't see any issues. Do you think there's anything else that needs to be done or checked before merging this?

**Comment by sagamusix** [comment]
It's complete but it I didn't test it yet; I will do that tonight. If everything works as intended, I can commit it to master.

**Comment by sagamusix** [comment]
I verified that it works for dates starting from 2020-10-28 and also cross-checked by implementing the same thing in OpenMPT. I will merge this to master!

**Comment by sagamusix** [comment]
Example files that should decode as Schism Tracker 2020-10-29 for anyone who wants to implement this in their own tracker / player:

[20201029.zip](https://github.com/schismtracker/schismtracker/files/3763851/20201029.zip)
