### ISSUE TITLE
Crash in first pattern of 02 - hallway 2_.it

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#213]
Module attached. Haven't looked into why yet.

[hallway2.zip](https://github.com/schismtracker/schismtracker/files/3757771/hallway2.zip)

**Comment by sagamusix** [comment]
Seems to be related to some MIDI channel bits being set. The file was made with an old version of OpenMPT, and the instruments are configured to send their output to some VST plugins that were actually removed; still the reference to those plugins is still stored in the MIDI channel output variable of the IT instrument headers.
