### ISSUE TITLE
Initial resolution in config doesn't work with OpenGL Graphics Context

### ISSUE THREAD

**Issue by JamesC01** [schismtracker/schismtracker#217]
If you set the width/height in config, it doesn't work if you use the OpenGL Graphics Context. It flashes to the right size for a moment, then reverts to the default 640x400.

**Comment by jangler** [comment]
OpenGL crashes for me currently, so I'll need to look into that first… I might remember looking into this issue a long time ago and not getting anywhere.

**Comment by jangler** [comment]
No longer applies given 869c01e.
