### ISSUE TITLE
No option for turning off texture filtering when using SDL video driver.

### ISSUE THREAD

**Issue by JamesC01** [schismtracker/schismtracker#218]
There's no option to turn off the filtering/blurring that occurs when you use a window size bigger than 640x400 for the SDL video driver.

**Comment by jangler** [comment]
I think can be done in SDL2 via SDL_HINT_RENDER_SCALE_QUALITY; not sure how/if it can be done in SDL 1.2 using surfaces (as opposed to OpenGL).

**Comment by JamesC01** [comment]
@jangler While you're here, is there anyway to set the default directory that schism starts in? If I want to load a module, it starts me in documents, which is no where near where my files are.

**Comment by jangler** [comment]
F12, "Directories" section.

**Comment by JamesC01** [comment]
> F12, "Directories" section.

Thanks!

**Comment by sagamusix** [comment]
FWIW, using the "YUV Video Overlay" results in crisp, non-filtered upsampling (at least on Windows), albeit with slightly different colors.

**Comment by JamesC01** [comment]
@sagamusix I already figured that out, but thanks anyway! I actually quite like the different colours.

**Comment by jangler** [comment]
Resolved by 869c01e.
