### ISSUE TITLE
[Docs] Build help: macro AM_PATH_SDL not found in library

### ISSUE THREAD

**Issue by Fordi** [schismtracker/schismtracker#22]
During autoreconf, I get the following warning:

```
configure.ac:58: warning: macro 'AM_PATH_SDL' 
```

Later, this crops up as an error in ./configure:

```
./configure: line 5134: syntax error near unexpected token `1.2.10,'
./configure: line 5134: `AM_PATH_SDL(1.2.10, , as_fn_error $? "*** SDL version >= 1.2.10 not found." "$LINENO" 5)'
```

Under Debian-based systems (Ubuntu, Debian, Raspbian), this can be solved thusly:

```
$ sudo apt install libsdl1.2-dev
$ autoreconf -vif
$ ./configure
```

After successfully building the library, I was able to use ldd and apt-file to get a list of debian packages that provide the necessary set of dev dependencies:

```
libselinux1-dev
libasound2-dev
libasyncns-dev
libcaca-dev
libdbus1.0-cil-dev
libflac-dev
libgcrypt11-dev
libghc-bzlib-dev
libghc-libxml-sax-dev
libgpg-error-dev
libjson-c-dev
liblzma-dev
libncursesw5-dev
libogg-dev
libpcre2-dev
libpulse-dev
libsdl1.2-dev
libslang2-dev
libsndfile1-dev
libsystemd-dev
libtinfo-dev
libvorbis-dev
libwrap0-dev
libxau-dev
libxcb1-dev
libxdmcp-dev
libxext-dev
```

This will also install the library dependencies for runtime.  If you just need the runtimes, chop off the '-dev' portion.

Additionally, (in case this is anyone's first build) for the build system, you'll need:

```
autoconf
build-essential
```

Apt one-liner, for the lazy:

```
sudo apt install build-essential autoconf libselinux1-dev libasound2-dev libasyncns-dev libcaca-dev libdbus1.0-cil-dev libflac-dev libgcrypt11-dev libghc-bzlib-dev libghc-libxml-sax-dev libgpg-error-dev libjson-c-dev liblzma-dev libncursesw5-dev libogg-dev libpcre2-dev libpulse-dev libsdl1.2-dev libslang2-dev libsndfile1-dev libsystemd-dev libtinfo-dev libvorbis-dev libwrap0-dev libxau-dev libxcb1-dev libxdmcp-dev libxext-dev
```

**Comment by asbjornu** [comment]
@Fordi Isn't this already mentioned in the [Linux build instructions](https://github.com/schismtracker/schismtracker/blob/master/docs/building_on_linux.md)?

**Comment by Fordi** [comment]
Not in a complete way, no.  The apt install list in that document did not, in fact, install all the packages I'd listed there, either directly or through dependencies.

**Comment by asbjornu** [comment]
@Fordi A pull request with an updated package list would probably be appreciated, then. :smiley:

**Comment by jangler** [comment]
All I had to do on Debian sid was to apt-get make, autoconf, and libsdl1.2-dev. I suppose I had things like build-essential installed from the start.

**Comment by ghost** [comment]
Honest, and maybe stupid, question: if `apt install libsdl1.2-dev` worked for you, what is that long list for?

**Comment by jangler** [comment]
I'm looking at the Linux build instructions and libsdl1.2-dev is explicitly in the list of dependencies for Debian-based systems. If installing libsdl1.2-dev fixed the issue, then I see no reason for this issue to remain open.
