### ISSUE TITLE
`schismtracker` is on `scoop`

### ISSUE THREAD

**Issue by shytikov** [schismtracker/schismtracker#222]
I have added `schismtracker` to `scoop-extras` bucket.

So right now Windows' users could install `schismtracker` by simply typing:

`scoop install schismtracker`

and it will not only provide them global `schismtracker` console command, but will also add shortcut `Schism Tracker` that could be accessed from Windows menu.

Not sure should that be mentioned in the documentation, waiting for your input on that, if you would consider that and important information that will help on-board Windows' users I will gladly submit PR with changes to the documentation.

**Comment by jangler** [comment]
Thanks for adding Schism Tracker, but in the documentation we generally recommend downloading the latest "official" release rather than using package managers (etc).
