### ISSUE TITLE
Question on sync

### ISSUE THREAD

**Issue by firolightfog** [schismtracker/schismtracker#224]
Hi, 
I've read the FAQ and I understand that implementing MIDI sync would be a hassle.
Though I am curious if there's any other simple way for another solution.
Korg Volcas sync with a 5V 15ms trigger. Could SchismTracker listen and receive this through the mic jack? 
Alternatively one (or more) channels could be sent through the Ethernet port to a [Doepfer A-180-9](http://www.doepfer.de/A1809.htm) eurorack module. Would that be possible from program design point of view?
Best regards, Andras

**Comment by firolightfog** [comment]
Hello,
Actually beside sending a trigger through the ethernet cable of [Doepfer A-180-9](https://www.modulargrid.net/e/doepfer-a-180-9) to an eurorack system it could be used to send audio of various channels to separate 3.5mm jack outputs. (Although there are some [quality](https://www.muffwiggler.com/forum/viewtopic.php?t=215539&highlight=) issues there.)

**Comment by sagamusix** [comment]
From the very same FAQ entry:

> This is somewhat tricky to implement, since tracked modules generally have a very different concept of speed and tempo from MIDI, and most effects are dependent on the song's speed.

This applies to *any* external clock, not just to MIDI ticks. It doesn't matter if it's a MIDI tick or something from the Eurorack  world - all of those concepts work very differently from tracker ticks.

**Comment by firolightfog** [comment]
Kind of sad that 'sync in' is that complicated.
But I still secretly hope to find a way for 'sync out'.  Let's say sending the output of channel #32 to a separate output. Depending on the (single cycle?) instrument on that channel its output could act as a kind of trigger/clock.
IProbably I had to let it go. Simehow I feel too engaged with the good old ST/IT/Schism environment... :)
Cheers, A.

**Comment by sagamusix** [comment]
If you would be comfortable with deviating from the IT environment a little bit - you could give OpenMPT a try - I implemented proper MIDI out syncing there (but it works completely differently from how Schism does it so I couldn't simply copy the code to Schism and it would magically work). It does have no MIDI-In synchronization just like Schism, though.

**Comment by firolightfog** [comment]
Sounds good. I have a look. Thanks Saga Musix
