### ISSUE TITLE
MIDI composition and volume commands

### ISSUE THREAD

**Issue by kitchen-ace** [schismtracker/schismtracker#228]
Hi, I'd like to use schismtracker to make MIDI files in conjunction with OpenMPT's MIDI exporter. Most things work fine in 'tracker semantics' mode. However in this mode, setting the volume in the volume column affects the channel volume, rather than the note velocity. In 'IT semantics' mode, this isn't the case, but a lot of other features are missing in this mode. 

(Of course exporting works fine but the idea is to have the exported file match what gets played in schism.)

Is this intentional? Can it be changed? If this is going to disrupt other people's workflow, I don't mind changing it for myself for my own local version of schismtracker, but I haven't been able to figure out how.

**Comment by jangler** [comment]
Late reply, but I would imagine this is intentional. In general, it makes more sense to map the volume column onto channel volume rather than note velocity, mainly because note velocity can't be changed after a note is triggered, but IT and MIDI channel volume both can.
