### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by asbjornu** [schismtracker/schismtracker#23]
After upgrading to OS X 10.11.5, Schism Tracker has started crashing on launch. Here's the relevant bits from console:

```
08.07.2016 00.48.41,669 schismtracker[71999]: CPSGetCurrentProcess(): This call is deprecated and should not be called anymore.
08.07.2016 00.48.41,669 schismtracker[71999]: set_foreground_operation_state(): This call is deprecated and should not be called anymore.
08.07.2016 00.48.47,462 schismtracker[71999]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.5 instead of 10.11.5. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
08.07.2016 00.48.47,462 schismtracker[71999]: 0   CarbonCore                          0x9b1c4e3d ___Gestalt_SystemVersion_block_invoke + 135
08.07.2016 00.48.47,462 schismtracker[71999]: 1   libdispatch.dylib                   0x997e283f _dispatch_client_callout + 50
08.07.2016 00.48.47,462 schismtracker[71999]: 2   libdispatch.dylib                   0x997e271b dispatch_once_f + 78
08.07.2016 00.48.47,462 schismtracker[71999]: 3   libdispatch.dylib                   0x997e3fa5 dispatch_once + 31
08.07.2016 00.48.47,462 schismtracker[71999]: 4   CarbonCore                          0x9b1408e1 _Gestalt_SystemVersion + 1047
08.07.2016 00.48.47,462 schismtracker[71999]: 5   CarbonCore                          0x9b14008a Gestalt + 154
08.07.2016 00.48.47,462 schismtracker[71999]: 6   sdl.dylib                           0x001b347b SDL_SoftStretch + 22203
08.07.2016 00.48.47,473 schismtracker[71999]: Warning once: This application, or a library it uses, is using NSQuickDrawView, which has been deprecated. Apps should cease use of QuickDraw and move to Quartz.
08.07.2016 00.48.47,523 schismtracker[71999]: 00:48:47.523 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
08.07.2016 00.48.47,598 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x100001ad.schismtracker[71999]) Service exited due to signal: Illegal instruction: 4
08.07.2016 00.48.48,576 ReportCrash[72001]: Saved crash report for schismtracker[71999] version 20120105 (20120105) to /Users/bitbear/Library/Logs/DiagnosticReports/schismtracker_2016-07-08-004848_BitMac.crash
```

And [here's the crash log](https://gist.github.com/asbjornu/e3abab61a73f452fd599a52e34ec12b5).

**Comment by jangler** [comment]
Help wanted from someone who can actually do OS X dev ;(

**Comment by HybridDog** [comment]
> Version: 20120105 (20120105)

It's not fixed in the new schismtracker version, is it?

**Comment by jangler** [comment]
I know people have successfully built and run recent (2016) Schism Tracker versions on OS X. I don't know anything about this particular version of the OS.

**Comment by asbjornu** [comment]
If I knew how to build it, I could help. Having continuous integration set up in this repository with AppVeyor and Travis would also be helpful.

**Comment by ghost** [comment]
Have you looked at the docs? I don't know how good they are but it's probably a good starting point. https://github.com/schismtracker/schismtracker/blob/master/docs/building_on_osx.md
https://github.com/schismtracker/schismtracker/blob/master/docs/building_on_linux.md

It'd be really helpful to have someone who could help with OSX stuff - I don't think there's much chance of me or jangler ever getting a mac so things like this are unfortunately just impossible to even get started on at present. :(

**Comment by asbjornu** [comment]
@mb14 Yes, I've looked and can't get anything to work. It stops at the very beginning with both OS X and Linux instructions trying to execute `../configure` which doesn't exist. I've figured out that I should use `autoconf` to convert `configure.ac` into a `configure` file, but when executing the result from that, it fails with the following exception:

``` sh
./SchismTracker/configure: line 2180: syntax error near unexpected token `-Wall'
./SchismTracker/configure: line 2180: `AM_INIT_AUTOMAKE(-Wall subdir-objects)'
```

Ideas on how to proceed would be warmly welcomed.

When I figure out how to build this from scratch, I can hopefully provide a [Travis](https://travis-ci.org/) build script that can automate the build on Linux and OS X and perhaps also a script that can automate the build for Windows on [AppVeyor](http://www.appveyor.com/).

**Comment by jangler** [comment]
Can you attach your entire configure script?

**Comment by asbjornu** [comment]
@jangler Sure, [here it is](https://gist.github.com/asbjornu/970905863e1630bf0d2b35e665048277).

**Comment by ghost** [comment]
Do you have automake installed as well and are you using that? There are a bunch of steps to the autotools process:

```
aclocal 
autoconf
autoheader
automake
```

although `autoreconf -i` should run them all at once. It's in the linux build docs though maybe "getting the source" is the wrong section for it.

Hopefully this helps!

**Comment by jangler** [comment]
Yeah, looks like that AM_INIT_AUTOMAKE macro (?) isn't being expanded. I don't know a lot about autotools but I would make sure that 1) you have all the requisite software installed (sometimes autoconf and automake are packaged separately) and 2) you ran `autoreconf -i`.

**Comment by asbjornu** [comment]
It would help a lot if this project had a `build.sh` I could just run, that took care of all of this. I have no idea where to start, tbh. I've never used autotools before. :smiley:

**Comment by ghost** [comment]
The point of autotools is that they easily manage the creation of build scripts for different platforms - as the build process is slightly different on different platforms it's not possible to do a build.sh that _just works_ (see e.g. the Windows build docs). Autotools plus a bit of fudging around on different platforms is as good as it gets. Glad you figured it out now though! Nice to have you on board! :)

Thank you for setting up the Travis integration, that's great work.

**Comment by asbjornu** [comment]
@mb14 Yea, I'm starting to understand it. But it seems like the `build.sh` I've created in #29 works on OS X and Linux at least. Would be cool to get the built artifacts from Travis published somewhere. The next logical step from there would be to create an [AppVeyor](http://www.appveyor.com/) build for Windows that also published its artifacts somewhere. Then we'd be in a good place, imho. 😄

**Comment by asbjornu** [comment]
Now that I've successfully built my own `schismtracker` executable on OS X, I'll close this. But let's please continue the thought of having a continuous integration pipeline with automatic releases on i.e. every `git tag` on `master` ([Mainline development](https://gitversion.readthedocs.io/en/latest/reference/mainline-development/)), every feature merge on `master` ([GitHubFlow](https://guides.github.com/introduction/flow/)) or something similar.

**Comment by esaruoho** [comment]
@asbjornu can you check the PR #132 for macOS/OSX documentation on creation of `./schismtracker` and `Schism_Tracker.app` with the newest build. Let me know if you can follow the instructions and get it to work..

**Comment by asbjornu** [comment]
@esaruoho: Thanks for figuring this out, it works flawlessly on my macOS Sierra 10.12.6.
