### ISSUE TITLE
Is the Stable Build broken on Mac Catalina?

### ISSUE THREAD

**Issue by ferro4prez** [schismtracker/schismtracker#231]
Consistently getting:

Using dummy on [sdl,yuv, opengl]

Everything worked perfectly right before upgrading to Catalina.

Thanks!

**Comment by ferro4prez** [comment]
Any updates?  Haven't been able to use SchismTracker since Catalina :(

**Comment by jangler** [comment]
Sorry, I have no idea about Mac-specific things. Can you provide any more info about the problem?

**Comment by ferro4prez** [comment]
This is the splash screen when launching.  Normally it would say "using xyz" when it correctly initialized a sound card, but instead it uses "dummy".
![image](https://user-images.githubusercontent.com/28815173/88952799-872ebc80-d25d-11ea-8088-f83f850583e2.png)

This is what happens when trying to load/play a module:
![image](https://user-images.githubusercontent.com/28815173/88952903-b6ddc480-d25d-11ea-8fe8-bee0dfbfda1a.png)

notice Failed to start CoreAudio error.  This happens with any module.

**Comment by ferro4prez** [comment]
Anything guys?  Anything I can do to help?

**Comment by jangler** [comment]
@ferro4prez, I know it's a bit late, but do you want to test with https://github.com/schismtracker/schismtracker/suites/6335965951/artifacts/228102064 and see if that fixes your problem?

**Comment by ferro4prez** [comment]
Hi! Thanks for the response, yes it did fix it!
