### ISSUE TITLE
Error compiling source on MacOS Catalina

### ISSUE THREAD

**Issue by pedrohex** [schismtracker/schismtracker#234]
Hi, cannot build from source on macos catalina:

	gcc -DHAVE_CONFIG_H -I. -I..  -D_USE_AUTOCONF -D_GNU_SOURCE -I../include -I.  -I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE   -DUSE_NETWORK  -DHAS_YM3812=1 -DHAS_Y8950=0 -DHAS_YM3526=0    -g -O2 -MT fmt/mod.o -MD -MP -MF $depbase.Tpo -c -o fmt/mod.o ../fmt/mod.c &&\
	mv -f $depbase.Tpo $depbase.Po
../fmt/mod.c:112:9: error: implicit declaration of function 'fmt_mod_load_song' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        return fmt_mod_load_song(song, fp, lflags, 0);
               ^
../fmt/mod.c:112:9: note: did you mean 'fmt_mid_load_song'?
../include/fmt-types.h:100:16: note: 'fmt_mid_load_song' declared here
READ_INFO(mid) LOAD_SONG(mid)
               ^
../include/fmt.h:84:37: note: expanded from macro 'LOAD_SONG'
#define LOAD_SONG(t)            int fmt_##t##_load_song         PROTO_LOAD_SONG;
                                    ^
<scratch space>:132:1: note: expanded from here
fmt_mid_load_song
^
../fmt/mod.c:119:9: error: implicit declaration of function 'fmt_mod_load_song' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        return fmt_mod_load_song(song, fp, lflags, 1);
               ^
2 errors generated.
make[1]: *** [fmt/mod.o] Error 1
make: *** [all] Error 2

**Comment by jangler** [comment]
It's true that that's invalid in C99. On Linux with gcc 10.1.0 and autoconf 2.69 I have this in my `config.log`:
```
configure:4053: checking for gcc option to accept ISO C99
configure:4202: gcc  -c -g -O2  conftest.c >&5
configure.4215: result: none needed
...
ac_cv_prog_cc_c99=
```
What do you have?

In any case those declarations should just be fixed; they're valid in C89/C90 but I think Schism is intended to be C99-compatible.

**Comment by vcaputo** [comment]
I don't have OSX here to test, but I suspect https://github.com/schismtracker/schismtracker/pull/235 fixes this.

**Comment by pedrohex** [comment]
well, this is the result :

configure:4086: checking for gcc option to accept ISO C99
configure:4235: gcc  -c -g -O2  conftest.c >&5
configure:4235: $? = 0
configure:4248: result: none needed

interesting..

**Comment by jangler** [comment]
Does vcaputo's branch compile for you?

**Comment by pedrohex** [comment]
Success, vcaputo's branch is compiling. 

can you or vcaputo explain the changes ? thanks

(edited)

just noticed.. its an older version 2017xx

I use schism to track , never developed anything or looked into the code.
However, if I can help somehow please let me know. I will try to understand what is done and contribute if possible.

Anyway, i would need the latest version compiling... I'll try to.

**Comment by jangler** [comment]
The change is just to move the calls to the function `fmt_load_mod_song` after its definition in the file. Using a function before its definition is allowed in some C standards, but not others. Not sure why your GCC and mine are doing different things, though. ¯\\\_(ツ)\_/¯

**Comment by vcaputo** [comment]
neat

Edit:

@pedrohex I don't understand what you mean re: it being an older version, the branch containing the fix was on top of upstream master, it wasn't 3 years old like my master branch on github was.

In any case, my fix is kind of obviously correct, if you still have problems with upstream master we can address them.
