### ISSUE TITLE
Key shortcuts not working instrument/samples menu

### ISSUE THREAD

**Issue by pedrohex** [schismtracker/schismtracker#236]
Cannot select any of the options using the keyboard at the instruments/samples page.

Using Windows 10 64bit, schism tracker 32bit 20190801

To reproduce:
- press F4 (instrument list)
- use tabkey to navigate to any of the options below "General" tab. 
- try to select "Not Cut" or "Continue" or "Note Off" or "Not Fade" using the enter key

Note: It works using the mouse and Keyboard apparently works ok in other pages.

**Comment by jangler** [comment]
Are you using [the latest version](https://github.com/schismtracker/schismtracker/releases/tag/20200412)? This bug was introduced in f4c945a, but that commit was reverted before the last release.

**Comment by pedrohex** [comment]
> Are you using [the latest version](https://github.com/schismtracker/schismtracker/releases/tag/20200412)? This bug was introduced in [f4c945a](https://github.com/schismtracker/schismtracker/commit/f4c945aee8aa8ade11945b538f3792e1ad8e4c33), but that commit was reverted before the last release.

**Comment by pedrohex** [comment]
I’m using the latest available build for windows in schism site.

Using Windows 10 64bit, schism tracker 32bit 20190801

**Comment by jangler** [comment]
ok i need to look into why appveyor decided not to build that one

**Comment by jangler** [comment]
see #237
