### ISSUE TITLE
[RFC] SDL2 port decisions

### ISSUE THREAD

**Issue by vcaputo** [schismtracker/schismtracker#240]
Assuming an SDL2 port is worthwhile, after some casual attempts at the port myself, I see at least two basic decisions that must be made:

1. What to do about the existing pile of video backends schismtracker implements from YUV planes to OpenGL support

2. What to do about the removal of the .unicode member of keyboard events.

For 1, I'd like to propose just throwing out everything schismtracker implements for video stuff in favor of always using an SDL2 SDL_Renderer, use an SDL_Texture as the equivalent of the current OpenGL driver's framebuf, and basically always operate as if it were an OpenGL backend with bpp=4, but using SDL_Renderer API to upload the vgamem to the SDL_Texture framebuf, and copying that texture to the SDL_Renderer every update.  No more direct OpenGL API usage, no more YUV support, just deprecate all that cruft and expect people who still want to use that to just use an SDL1.2 old schismtracker version.  See https://wiki.libsdl.org/MigrationGuide#If_your_game_just_wants_to_get_fully-rendered_frames_to_the_screen for more information.  Basically we'd just lean entirely on SDL2's SDL_Renderer implementation to handle all the details schism's existing legacy video driver mess tries to do currently. 

For 2 I'm not sure what's best to do.  There's direct support for IME handling in Schismtracker, but SDL2 has deprecated the .unicode member in favor of a new TEXTINPUT event type which brings in a UTF-8 string having potentially multiple characters in a single event.  It really doesn't align with the existing input model of schismtracker, but there's no trivial way to get back the .unicode equivalent on SDL2.   See https://wiki.libsdl.org/MigrationGuide#Input for more information.  It's possible we could try synthesizing the .unicode value on keypresses from the keycode and modifier states, and ignore the new TEXTINPUT stuff, continuing to rely on schism's builtin IME features exclusively.  I think otherwise rearranging the input handling to fit the TEXTINPUT events would be a pretty invasive change, though it might provide better non-english input handling.  Maybe something along the lines of what's done here https://github.com/MrAlert/sdlcl/blob/master/events.c makes sense to pull into schism for producing 1.2-style unicode input.

Rather than just try make these decisions myself in isolation and submit an SDL2 port PR nobody actually likes and never merges because we never came to a consensus on throwing out a pile of legacy code beforehand, I'm hoping we can decide what to do here in discussion before attempting to merge SDL2 support.

I'm also curious if perhaps we should just ignore SDL2 and expect people to use a compatibility layer like https://github.com/MrAlert/sdlcl to run schism atop SDL2.

**Comment by sagamusix** [comment]
At least on Windows, I currently prefer YUV over SDL as it doesn't use interpolation for upscaling. As long as that's possible with the new backend, I personally see no issue with dropping YUV (although I don't know why it existed in the first place, so I cannot reason about technical aspects, just personal preference). I know some projects maintain compatibility with both SDL2 and SDL1.2 but it might not be worthwile for Schism Tracker (again I'm the wrong person to ask though as I don't use it on systems that are no longer supposed by SDL2).

I remember Schism Tracker could directly output to textmode. Is that part of SDL1.2 or was that a separate driver? If it's the latter, there would definitely be a good reason to keep supporting more than one driver. If more than one driver will be kept in the end, I would suggest to split them up into different implementation files to clean up video.c.

**Comment by jangler** [comment]
SDL2 supports "nearest", "linear", and "best" scaling options via the `SDL_HINT_RENDER_SCALE_QUALITY` hint.

By "textmode" I think you mean the Linux framebuffer, which isn't supported by SDL2 as far as I can tell.

**Comment by jangler** [comment]
> …just deprecate all that cruft and expect people who still want to use that to just use an SDL1.2 old schismtracker version.

My vote is to do this instead of to maintain parallel SDL2 and SDL1.2 implementations. I'd much rather prioritize e.g. macOS support over Linux framebuffer support.

Unfortunately I don't know enough to contribute to the Unicode/IME conversation.

**Comment by vanfanel** [comment]
@jangler SDL2 does support running without an X11 server, using KMS/DRM directly.
Which in practice results in "running on the Linux framebuffer" (in fact, it's the opposite: the legacy Linux framebuffer emulation, previously known as FBDev, runs on KMSDRM).

In fact, I always run Schismtracker, using an SDL2 fork, on KMSDRM (ie: on the text console, no X11).

**Comment by jangler** [comment]
> we could try synthesizing the .unicode value on keypresses from the keycode and modifier states, and ignore the new TEXTINPUT stuff, continuing to rely on schism's builtin IME features exclusively.

Looking at this again, I do think this is the way to go. To me it seems like the most realistic path toward getting a fully functional SDL2 build. SDL2 has been on the wishlist for (at least) 5 years already, and I'd rather it not get bogged down further by drastically changing our input model.

I was going to take a shot at adding JACK support today, but #144 reminded me that SDL2 has built-in support for JACK audio (but I'm guessing not MIDI), so by using SDL2 we'd get that "for free", so maybe I'll focus on this instead…

@vcaputo did you ever make any progress toward a port?
@vanfanel what SDL2 fork are you using?

**Comment by vcaputo** [comment]
I have an SDL2 branch I was working on when I created this issue.  It at least built and worked well enough for me to run and play songs in, but there was still a bunch of messy junk/commented out code to make it build.  I'll try find time later to dust it off and push it to my fork on github, it might be useful to bootstrap from since I did make some effort to organize all the changes cleanly into separate commits with references to the migration guide explaining the changes.  Most the stuff is straightforward, it just comes to a grinding halt at the YUV/IME details IIRC, with a final junk drawer commit of #if 0's and other kludges to make it build.

Edit: it also might be worth revisiting the state of compatibility layers, it'd sure be less work if schism could just continue being an SDL1.2 program built with some out of tree compat glue servicing all legacy SDL programs to run on SDL2-preferred platforms.

**Comment by strongholdmedia** [comment]
>  It's possible we could try synthesizing the .unicode value on keypresses from the keycode and modifier states, and ignore the new TEXTINPUT stuff, continuing to rely on schism's builtin IME features exclusively.

Sorry it's me again :D I figured I'd chime in.
I am not quite certain _how_ the "IME handling" is currently implemented in `schism`, but as far as I am concerned I am not quite sure this approach would be optimal.

> I think otherwise rearranging the input handling to fit the TEXTINPUT events would be a pretty invasive change, though it might provide better non-english input handling.

In fact, for e.g. French people, who have an "AZERTY" keyboard, you would make them quit with their A key (in addition to Ctrl) in the former  preferred choice, that does not seem quite wieldy.

Still, one'd get keypresses from the TEXTINPUT but only in some cases - Alt(nonGr)+letters/numbers, function keys etc. have no unicode value and would not appear at all in a pure TEXTINPUT approach. So one would have to both support the scancode array and the TEXTINPUT stuff.

There is also the "distant" possibility of forgoing SDL2 input stuff altogether and link that part statically from SDL1.2, or even merging its source code.
While this may sound ugly or obtrusive, this would work quite well, and given that SDL1.2 is EOL, it would not pose quite much of a problem.
(SDL1.2 keyboard handling is ~30k binary, linux-amd64, plus a few extras, and as `schism` is GPL, it wouldn't pose much of a legal problem either.)

Even more remote is to link against both SDL and SDL2 statically, and use compiler dead-code elimination to remove all the unwanted kruft from the binary. While this would work great for gcc and clang, I am not quite certain for the same on other supported platforms.

The "correct" approach would, in any case, be implementing TEXTINPUT and merging it in an event hander that handles both scancodes and "unicode input", with filters. But I understand that may be overkill.
On the other hand, I think the next best possibility is "borrowing" SDL1.2 input handling completely at the source level.
(After all there is already a heavily modified modplug engine, innit.)

**Comment by jangler** [comment]
vcaputo didn't specifically suggest doing text input based on solely on scancodes; both SDL1.2 and SDL2 support "keysym"-based input that accounts for the user's active keyboard layout rather than just the physical location of the key pressed. In my tracker that uses SDL2 for input, keysyms are used for keyboard shortcuts and scancodes are used for the musical keyboard layout. A quick `git grep` of the Schism codebase indicates that it also uses both.

**Comment by strongholdmedia** [comment]
Excuse me, I only reviewed the audio code before. Thanks for clarification.
So basically the "only" problem would be where actual typing is taking place (sample/instrument/file names, songdoc, etc.)?

**Comment by mrpapersonic** [comment]
Sorry for not checking in here before making decisions in my own branch, but WASAPI "native" master volume support is basically out the window, I've looked through the code for it and there doesn't seem to be a very clear way to do it.

So in my PR I completely removed all of the old OS-specific master volume stuff in favor of just normalizing the output from the player. (https://github.com/schismtracker/schismtracker/pull/292/commits/1b5e20f1601da2e12cbc6bb3fcad6c7b9c83b2a5).

IMO this is the best way to go, but I'd like to hear y'all's thoughts on it.

**Comment by vcaputo** [comment]
Playing catchup on long-ignored GH notifications here, and just getting reminded that this actually landed and schism is on SDL2 now.  Never thought I'd see that happen.

Great work @mrpapersonic @jangler
