### ISSUE TITLE
HELP! MacOS Big Sur: Schism Tracker won't load

### ISSUE THREAD

**Issue by pkingsbury** [schismtracker/schismtracker#242]
Since upgrading to Mac OS Big Sur, I cannot get Schism Tracker to load. I tried re-installing the 3 latest builds and all give a blank, white screen. Sometimes I can quit the Application other times I need for force quit.

I presume a new build is needed to run on their new OS.

![image](https://user-images.githubusercontent.com/76780553/103355956-9e2c4180-4a7d-11eb-85be-03930e06c2ea.png)

**Comment by jangler** [comment]
Schism seems to have been broken on (some versions of) macOS since at least June (#231), but none of the regular devs are macOS users, so we can't really troubleshoot it. I guess there's a chance that macOS is finally dropping support for deprecated APIs that SDL 1.2 uses.

One thing to try would be to change the video backend in the config file. You should have a text file named `config` in `~/Library/Application Support/Schism Tracker`; try opening it and changing the `driver=sdl` line in the `[Video]` section to `driver=yuv` or `driver=opengl`.

**Comment by pkingsbury** [comment]
driver=opengl did the trick.

Took me a while to figure out how to access the config file, as I usually run Windows.

**Thanks for the help!!!** Much appreciated.

**Comment by jangler** [comment]
Closing this but noting that `driver=opengl` should probably be the default on macOS now.

**Comment by esaruoho** [comment]
@jangler how would you go about making `driver=opengl` be default on macOS?

**Comment by jangler** [comment]
I looked into it briefly yesterday but it wasn't readily apparent to me.

**Comment by vcaputo** [comment]
I think OSX defines `__MACH__` so the usual #ifdef dance could be used for defaulting opengl there

**Comment by jangler** [comment]
Yeah, I just meant that I don't know where the default is set regardless of platform.

**Comment by vcaputo** [comment]
Oh, yeah, I see what you mean, video.c is a veritable mess.

I haven't tested to verify, but at a glance maybe the conditional preprocessor chain starting @ https://github.com/schismtracker/schismtracker/blob/master/schism/video.c#L490 amounts to the platform-specific defaults?

**Comment by esaruoho** [comment]
ok, changed it to opengl and got it to display on Big Sur.

**Comment by playinmyblues** [comment]
It was not running from a source code install. I downloaded the file for the macOS 64-bit build. Even after copying the app to the Applications directory and restarting my computer, there is no file or that directory to be found.

If I try opening up Schism Tracker.app > Contents > MacOS > schismtracker I get a file with lots of symbols. The word "driver" is all over the place but it does not look like a file I should be editing.

Maybe there is a special editor that I can use to access the information in the schismtracker file in that directory so I can change the settings?
