### ISSUE TITLE
Graphic freeze after minimizing, then un-minimizing window (20200512 build)

### ISSUE THREAD

**Issue by KungFuFurby** [schismtracker/schismtracker#243]
Hello! I just tried out the 20200512 build running macOS Catalina Version 10.15.7. I haven't done a manual compilation yet, as I'm still adapting to the new OS after many years on Snow Leopard, including what updated components I should acquire.

I ran into a complication when minimizing and un-minimizing the window: when un-minimized, the entire window is graphically frozen. It still appears to run normally, just that the graphics freeze on me.

**Comment by jangler** [comment]
Does this solution work? https://github.com/schismtracker/schismtracker/issues/242#issuecomment-752693009

**Comment by KungFuFurby** [comment]
All three options are affected. And switching between the drivers in the System Configuration menu doesn't work either.

**Comment by jangler** [comment]
I have a feeling this was fixed by Schism's change over to SDL2, but I can't test. If someone could try to reproduce this on macOS using the latest build, I'd appreciate it!

**Comment by KungFuFurby** [comment]
The graphical freeze no longer exists as of the SDL2 port... in referral to the case I mentioned with minimizing and un-minimizing.
