### ISSUE TITLE
Why is ST asking for firewall exceptions? - Fixed thanks using --no-network command in PowerShell

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#244]
redacted

**Comment by ghost** [comment]
eh forget it ill move to OpenMPT

**Comment by vcaputo** [comment]
It shouldn't be, that's unexpected, where is this executable from?

**Comment by ghost** [comment]
http://schismtracker.org/

**Comment by ghost** [comment]
[schismtracker-20190805-win32.zip](https://github.com/schismtracker/schismtracker/files/5825197/schismtracker-20190805-win32.zip)
[schismtracker-20190805.zip](https://github.com/schismtracker/schismtracker/files/5825198/schismtracker-20190805.zip)

**Comment by ghost** [comment]
I extract it with 7zip to a folder then run schismtracker.exe, I should do a Wireshark capture

**Comment by vcaputo** [comment]
Oh! There's support for MIDI over IP.

Maybe try running it with --no-network?

**Comment by ghost** [comment]
ah i see does it use MDNS?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/69438439/104824354-f81f5c00-581e-11eb-9328-2d2a340fff60.png)
