### ISSUE TITLE
Color palette not saved

### ISSUE THREAD

**Issue by lverona** [schismtracker/schismtracker#245]
My assumption is that palette should be saved after I exit the app. However, it doesn't seem to do that. I tried a 2018 and 2019 Linux build, I also tried the 2019 win32 build through WINE - same effect: palette settings are not saved.

**Comment by cs127** [comment]
If you go to the variables screen (F12) and click "Save all preferences" after changing the colors, the colors should be saved, and they will not reset when you exit the app.

**Comment by brandflake11** [comment]
Wow, this actually works. I thought it just wasn't possible to save the palette, but this is how you do it. Thanks @cs127
