### ISSUE TITLE
Show note data?

### ISSUE THREAD

**Issue by GhbSmwc** [schismtracker/schismtracker#247]
Impulse tracker has this viewer: https://www.youtube.com/watch?v=KywFQaahO0I

I was wondering if schismtracker has this. I tried using this version for windows: http://schismtracker.org/

**Comment by vcaputo** [comment]
Hit PgUp/PgDwn many times once on the info page (F5) to cycle through the visualizations

**Comment by GhbSmwc** [comment]
Thanks!
