### ISSUE TITLE
Amiga M.K. 4-channel mod saving capability

### ISSUE THREAD

**Issue by retrohun** [schismtracker/schismtracker#248]
Is there a chance to merge a future PR with my corresponding modifications here: https://github.com/retrohun/schismtracker/commit/0e8c0dbda361edcab4fa6fb90b6e9117045fae45

Can saves 4-channel modules only. Opened some well-known modules, saved them. Only major differences I've recognized is that pads sample text with (char)0 instead of spaces. No further tests had been performed yet, volunteers are appreciated and kindly welcome as always!

**Comment by retrohun** [comment]
Actually it works if anyone is interested.

**Comment by jangler** [comment]
Closing this since we have the PR now!
