### ISSUE TITLE
Increasing window size makes schism look blurred

### ISSUE THREAD

**Issue by HybridDog** [schismtracker/schismtracker#25]
Default window size: https://cloud.githubusercontent.com/assets/3192173/16713724/e03bc094-46b0-11e6-8f83-ef37c418a984.png

~double window size: https://cloud.githubusercontent.com/assets/3192173/16713728/01abbfa4-46b1-11e6-8208-87697393b857.png

Is there a setting to disable the interpolation when scaling?

l'd like to have that scale2x upscaling, or even that: https://github.com/nagadomi/waifu2x
l'm not sure if waifu2x is capable of upscaling in realtime
https://cloud.githubusercontent.com/assets/3192173/16713769/ce7c1678-46b1-11e6-98b1-6a040e747c8f.png

**Comment by jangler** [comment]
Huh! I never even thought about scaling sans interpolation, but it would definitely be nice to be able to double or triple the window dimensions that way.

No external library would be needed; SDL supports this internally (although I'm not sure about how the other video modes might mess with this, if at all).

I imagine this would best be implemented as a config option.

**Comment by ghost** [comment]
IIRC from my adventures in the video code it does attempt to look at whether the aspect ratio matches the original before deciding whether to interpolate... maybe! 
YUV mode doesn't interpolate for me here but YYUVMMV

**Comment by jangler** [comment]
Haha, all the video modes interpolate for me.

**Comment by jangler** [comment]
Regardless of aspect ratio. Note that 1440x900 should interpolate but it might be nice if 1280x800 didn't (since it's exactly double the original dimensions).

**Comment by HybridDog** [comment]
How about dithering?

**Comment by ElectricKeet** [comment]
An alternative to worrying about tweaking interpolation modes (or in conjunction with) might be pixel-doubling options. You know, scale the output frame without interpolation to 3200×2400, then let the video system do its own interpolated downscaling to your actual window size (if you even need to, dang kids and your fancy HiDPI displays). Then you get all the good and none of the rotten: the proper aspect ratio (since it always looks vertically squashed otherwise) and nice crisp pixels with just enough interpolation so you don't get funky rows from non-integer scaling. You know... oversampling.

I should simply have said "oversampling" there, shouldn't I?

**Comment by HybridDog** [comment]
so upscale it without interpolation with the factors sy `= ceil(height/orig_height)` and sx `= ceil(width/orig_width)` and then downscale it to the window resolution?

**Comment by ElectricKeet** [comment]
That'd be the simplest way. That, or some algorithm to give the same effect without having to generate thirty times the needed pixels. (I am not a coder. I am a visual-and-musical sort with enough technical knowledge to make me a pain in the butt. Apologies.)

**Comment by HybridDog** [comment]
lm wondering what would happen if those factors were used and the window size is smaller than the original one

**Comment by HybridDog** [comment]
no, ceil makes…

**Comment by jangler** [comment]
If you consider 4:3 – or any other aspect ratio – to be the "proper" one, then you'll only get that if your window is scaled that way. Scaling the back buffer won't change that.

Could just have an option to disable interpolation. I'll assign this to myself.

**Comment by ElectricKeet** [comment]
The real purpose to the oversampling is not for the sake of the aspect ratio as it is to make sure that only the edges of pixels are blurred when scaling up, so every pixel is effectively as sharp as it can be while maintaining the appearance of even scaling. For reference: http://libretro.com/forums/showthread.php?t=4971 (and there's eevn an image further down in that thread to demonstrate!)

It works best when either width or height are an integer multiple of the original, so at least one dimension will be ultra-crisp. That can probably be managed by the user specifying target (inner) window size via config file. That would allow for other ratios to be chosen, not just 4×3. Bonus!

**Comment by jangler** [comment]
OK, after playing around with fake prescaling, I definitely like the effect. If we automatically prescale the surface just until it's larger than the actual window size, then we can decimate instead of interpolating. If we're at an exact multiple of the original aspect, we don't have to resample at all.

Looks like three config options to me:
1. prescale
2. window_width
3. window_height

**Comment by ElectricKeet** [comment]
Sounds good! I'd love to help test. If that means setting up enough of an environment that I can compile a Windows binary, I'll just have to do that, eh?

**Comment by jangler** [comment]
Pretty hard to test otherwise ;)

If you're not comfortable doing that, though, then don't worry 'bout it.

**Comment by ElectricKeet** [comment]
The directions were easy enough – especially once I followed them properly. **grin**

So, yes, I have successfully compiled a working (mostly*) Schism Tracker executable from the current codebase, so I'm ready to go.

*: Everything seems fine except for numeric displays. All of them are left-aligned – there's no zero/space padding. What ought to be " 15" will show up as "15■", that square being a cell filled with colour index 2.  (The third in the first column.) But so far, that seems to be the only issue.

**Comment by HybridDog** [comment]
ls it possible to download travis' compilations?

**Comment by jangler** [comment]
Can you provide a screenshot? I can't think of any places in Schism where numbers are supposed to be space-padded; they're all zero-padded AFAIK.

**Comment by ElectricKeet** [comment]
In the light of morning, and with testing a bit more involved than simply loading a track and checking to see if it plays... I have come to the conclusion that something's wrong with my environment. There are other major issues. I'll try to troubleshoot things and see if I can't get it all working. Sorry 'bout that.

**Comment by jangler** [comment]
Bluh, there are video dimension numbers in dozens of places and I don't know what they all mean. Will take another look at this later…

**Comment by HybridDog** [comment]
Could you add a setting to change the interpolation method between the current one, which makes schism look blurred, and disabled interpolation, which makes some lines thicker than other ones. Oversampling can be added as setting value later.
If you scale schism by a factor >= 3, disabled interpolation looks better than the current blurry one.

**Comment by jangler** [comment]
Oh, I guess I was thinking of OpenGL when i was talking about built in linear versus nearest scaling. Anyway, new config option `gl_bilinear` under `[Video]`. If it's set to zero, then you'll get nearest-neighbor scaling when using OpenGL.

**Comment by HybridDog** [comment]
thanks

**Comment by jangler** [comment]
Alright, my plan for this is to implement those config options I mentioned earlier. `prescale` would be a natural number option, defaulting to 1, that would determine by what factor the video output will be scaled before being rescaled to fit the window. We'll see if this plan survives contact with the video code.

**Comment by jangler** [comment]
Added config options `width` and `height` under `[Video]`.

Edit: Unassigning because I actually don't mind the current interpolated scaling and would rather prioritize other issues. I still think oversampling is a good idea, though.

**Comment by alugarius** [comment]
I see no difference

**Comment by aphexetwine** [comment]
Pixel-perfect upscaling is a must. I see no point in using this tracker if I have to squint at the screen. And no sane person can keep up with the blurred upscale. Am I missing something or has this not been implemented yet? sounds obvious.

**Comment by vcaputo** [comment]
My guess is nobody willing and able to do the work is suffering from use on a hidpi/retina display.

You're welcome to get your hands dirty and submit a PR, this project is generally pretty receptive to quality contributions.

**Comment by ghost** [comment]
> Pixel-perfect upscaling is a must. I see no point in using this tracker if I have to squint at the screen. And no sane person can keep up with the blurred upscale. Am I missing something or has this not been implemented yet? sounds obvious.

Have you tried the OpenGL video mode? (see [Jangler's comment](https://github.com/schismtracker/schismtracker/issues/25#issuecomment-236453944)) 

Anyhow, never had a problem with interpolation myself and I _think_ I'm sane (?!)

**Comment by jangler** [comment]
Resolved by 869c01e.
