### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sagamusix** [schismtracker/schismtracker#255]
I just noticed that there's a release from April 2020 tagged on GitHub, but schismtracker.org still points at the last 2019 release... given that there have been quite a few bugfixes since April 2020, I think it's time for a new release, rather than just fixing the release link on the frontpage. ;)

**Comment by jangler** [comment]
I agree. Probably just going to manually compile on Windows rather than fix AppVeyor for now.

**Comment by jangler** [comment]
(This has been delayed because of MSYS2 issues.)

**Comment by jangler** [comment]
Made new release and built on Windows but seems like Travis CI is broken/gone now @_@

**Comment by jangler** [comment]
#272 and c4c2c50 resolve the builds issue. Did another release with builds for all major platforms.
