### ISSUE TITLE
Broken mod: broken tone porta 

### ISSUE THREAD

**Issue by retrohun** [schismtracker/schismtracker#258]
During playback, effect+value GF0 sets invalid frequency on sample 2, line 1, channel 1, pattern 3, order 4.
Shown frequency became "-12335168"

Affected module is an 8-channel one.
- online: https://ftp.*******.com/pub/modules/Octalyser/505/newocta.mod
- magic id at offset 1080L: CD81
- cksum and size: 1319020519 285068 newocta.mod
- md5sum: 53608720918e1f374ee4179754b5beef  newocta.mod

Used builds:
- commit id: 89e3b0b "Merge pull request #257 from laamaa/alsa-oss-midi-fix"
- commit id: c0f349b
- host OS: linux

Four commits earlier, built a binary from commit c0f349b. That mutes the affected sample after GF0, which is also wrong.
Needs confirmation. Thanks in advance!

**Comment by sagamusix** [comment]
Good catch! Fixed in latest.
