### ISSUE TITLE
Use csf_get_num_patterns in fmt_mod_save_song

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#259]
The MOD writer currently only writes patterns up to the highest-numbered pattern in the order list, unlike the IT and S3M writers, which write all patterns up to the highest-numbered non-empty pattern. Patterns that do not appear in the order list are currently lost when writing MOD files.

**Comment by sagamusix** [comment]
It's not so simple with MOD... the main difference is that IT and S3M have explicit header fields declaring the number of patterns. MODs don't have that, the number of patterns to read is inferred from the order list contents instead. You can in theory put "hidden" patterns past the end of the order list to bump the number of the highest used patterns, but of course that only works if there is space left in the order list (i.e. you use less than 128 orders in your track), and not every MOD player may handle this correctly. Only writing up to the highest pattern number found in the order list is the safest thing to do with MOD.

Edit: OpenMPT warns the user in this situation that these patterns won't be saved. Schism could do the same.

**Comment by jangler** [comment]
OK, I'll add a warning in that case.
