### ISSUE TITLE
combine velocity and volume bars

### ISSUE THREAD

**Issue by HybridDog** [schismtracker/schismtracker#26]
Currently you can press v to switch between volume and velocity bars.
Instead of that both could be shown at once by using more colours instead of just yellow.
The volume could keep the colour yellow and the velocity could use e.g. purple.
The colours are mixed where both bars are overlapping each other.
![2016-07-10-153002_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3192173/16713852/e329f85e-46b3-11e6-8e43-9cc2525b08b4.png)
Instead of mixing the colours, the upper part of those studs can get one colour and the lower part the other one.
![2016-07-10-153002_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3192173/16713885/cb793476-46b4-11e6-8f61-916c8be84fc5.png)

**Comment by HybridDog** [comment]
draw_vu_meter is at the end of schism/draw-misc.c
How exactly does it work?

**Comment by jangler** [comment]
Your guess is as good as mine :)

**Comment by HybridDog** [comment]
Sorry, this was off topic.

**Comment by jangler** [comment]
I wouldn't optimize anything that hasn't been identified as a problem! That's honestly not even worth looking into.

**Comment by HybridDog** [comment]
> I wouldn't optimize anything that hasn't been identified as a problem! That's honestly not even worth looking into.

l'd like to try ```$ gcov```, but l don't know how it works. gcov can be used to test the performance of the code at specific places, can't it?

**Comment by JosepMaJAZ** [comment]
I have doubts that this can be achieved.
Following from the ideas in Scream Tracker and Impulse Tracker, many of Schismtracker's drawings are characters, and this includes the vu-meters (In schismtracker, the envelopes are drawn, but in impulse tracker they were made in realtime with text too).

The vu-meter drawing code is in : schism/draw_misc.c , line 76:
void draw_vu_meter(int x, int y, int width, int val, int color, int peak)

**Comment by HybridDog** [comment]
JosepMaJAZ, the character draw code is in draw_char.c
Maybe there a function could be added which puts characters with top and bottom colours.

Edit: see below

**Comment by JosepMaJAZ** [comment]
I remember that I modified the master vu meters to show in dB. I think the channel vus are in dB too but I don't remember and don't have the code in front right now.  Whit that I want to say that logaritmic representation is not needed.
Maybe i missed to do it for velocity.

**Comment by HybridDog** [comment]
>Whit that I want to say that logaritmic representation is not needed.

It's convenient.
Anyway, l tried to solve it myself:
```
a^b means exp(ln(a) * b)

2^5 studs, 0 <= v < 2^8
0 <= vumeter_val < 2^8

val(v) = a*ln(b*v) + k

val(2^8) = 2^8 = a*ln(b*2^8) + k; ← full before means full after executing
val(2^7) = 2^7 = a*ln(b*2^7) + k; ← half … half …
val(2^3) = 2^3 = a*ln(b*2^3) + k; ← 1 stud … 1 stud …

I, II
(a*ln(b*2^8) + k) *.5 = a*ln(b*2^7) + k
.5*a*ln(b*2^8) = a*ln(b*2^7) +.5k
.5*ln(b*2^8) = ln(b*2^7)+.5k
ln(b*2^8) = 2*ln(b*2^7) + k
k = ln(b*2^8) - 2*ln(b*2^7)
k = ln(b) + 8ln(2) - 2*ln(b) - 14ln(2)
k = -ln(b) - 6ln(2)

II, III
a*ln(b*2^7) + k = (a*ln(b*2^3) + k) * 2^5
a*ln(b*2^7) = a*ln(b*2^3) * 2^5 + k * 2^5 - k
a * (ln(b*2^7) - ln(b*2^3) * 2^5) = k * 2^5 - k
a * (ln(b*2^7) - ln(b^32 * 2^(3*32))) = k * 31
a * ln(1 / (b^31 * 2^89)) = k * 31
a * -ln(b^31 * 2^89) = (-ln(b) - 6ln(2)) * 31
a * ln(b^31 * 2^89) = 31ln(b*2^6)
a = 31ln(b*2^6) / ln(b^31 * 2^89)
a = 31ln(b) + 186ln(2) / (31ln(b) + 89ln(2))
a = 1 + 97ln(2) / (31ln(b) + 89ln(2))

III
2^3 = ln(b*2^3) * (1 + 97ln(2) / (31ln(b) + 89ln(2))) - ln(b) - 6ln(2)
2^3 = ln(b*2^3) + ln(b*2^3) * 97ln(2) / (31ln(b) + 89ln(2))) - ln(b) - 6ln(2)
2^3 = ln(b*2^3) * 97ln(2) / (31ln(b) + 89ln(2)))  - 3ln(2)
2^3 = (ln(b) + 3ln(2)) * 97ln(2) / (31ln(b) + 89ln(2)))  - 3ln(2)
2^3 = (ln(b) * 97ln(2) + 3ln(2) * 97ln(2)) / (31ln(b) + 89ln(2)))  - 3ln(2)
2^3 = (ln(b) * 97ln(2) + 291ln(2)^2) / (31ln(b) + 89ln(2)))  - 3ln(2)

(ln(b) * 97ln(2) + 291ln(2)^2) / (31ln(b) + 89ln(2)))
= 97ln(2)/31 + (291ln(2)^2 - 89ln(2) * 97ln(2)/31) / (31ln(b) + 89ln(2))
= 97ln(2)/31 + (291ln(2)^2 - 8633/31*ln(2)^2) / (31ln(b) + 89ln(2))

2^3 = (97/31)*ln(2) + (291ln(2)^2 - 8633/31*ln(2)^2) / (31ln(b) + 89ln(2))  - 3ln(2)
2^3 = (97/31 - 3)*ln(2) + (291ln(2)^2 - 8633/31*ln(2)^2) / (31ln(b) + 89ln(2))
(291ln(2)^2 - 8633/31*ln(2)^2) / (31ln(b) + 89ln(2)) = 2^3 - (97/31 - 3)*ln(2)
(31ln(b) + 89ln(2)) / (291ln(2)^2 - 8633/31*ln(2)^2) = 1 / (2^3 - (97/31 - 3)*ln(2))
31ln(b) + 89ln(2) = (291ln(2)^2 - 8633/31*ln(2)^2) / (2^3 - (97/31 - 3)*ln(2))
31ln(b) = … - 89ln(2)
ln(b) = (… - 89ln(2)) / 31
b = exp((… - 89ln(2)) / 31)
b = ~0.1400884291887

k = -ln(b) - 6ln(2)
k = ~-2.1934016646503

a = 1 + 97ln(2) / (31ln(b) + 89ln(2))
a = ~89.447092535116
```
but l assume l did a mistake somewhere, see the test
Can you tell me where l did the mistake?

result tested in $ lua:
```
> function t(v)
>> print(89.447092535116 * log(0.1400884291887 * v) + -2.1934016646503)
>> end
> t(1)
-178
> t(8)
7.9999999999978
> t(255)
317.64991308525
> t(128)
256
> t(64)
194
```

**Comment by jangler** [comment]
This hasn't progressed and isn't likely to; the potential utility of this enhancement appears to be outweighed by the implementation cost. Closing.

**Comment by HybridDog** [comment]
Is there documentation about the implementation of the bars and the other graphical related things?

**Comment by jangler** [comment]
If there is documentation, it's in the code itself, so you could search there. Might not be, though; some of the code isn't super well-documented.
