### ISSUE TITLE
duck modulator

### ISSUE THREAD

**Issue by coderofsalvation** [schismtracker/schismtracker#261]
![image](https://user-images.githubusercontent.com/180068/120279742-1ca04000-c2b7-11eb-821e-467ad6f4beff.png)

I've noticed this in the help, and it's something which got me thinking.
Let me start with the good news: the ultimate per-sample ducking is already possible..but the question is whether there CAN be something more simple than this:

```
string         kick
====        |  ====
c-5 00 Dx0  |  c-5 64             <-- manual ducking using volume slide up (already implemented)
       Dx0  |
       Dx0  |
```

> the downside of this is that it takes up quite some fx-rows

# IDEA: multiply (other) instrument (inversed) envelope to final envelope

* effect S99 select the envelope of the current instrument as modulator envelope
* effect S9A applies the last selected INVERSED modulator envelope to the current instrument
* effect S9B applies the last selected modulator envelope to the current instrument

```
string          kick
====         |  ====
c-5  S9A     |  c-5 S99             <-- kick could even be an sample-less instrument with just an envelope
```

This would be a simple expander:

```
string          kick
====         |  ====
c-5  S9B     |  c-5 S99             <-- kick could even be an sample-less instrument with just an envelope
```

TOO COMPLEX: an envelope bus
=========================

for automated ducking we could specify 'mod send / modulate' for each instrument:

```
string          kick
====         |  ====
c-5          |  c-5              <-- pattern-agnostic ducking effect
```

Basically specifying per instrument which:

* volume to (not) send to the modulator channel (`0-64`)
* how to apply the modulator: 
  * `2` no master output, apply modulation
  * `1` master output, apply modulation   
  * `0` master output, no modulation
  * `-1` master output, apply modulation (with inverted envelope
  * `2` no master output, apply modulation (with inverted envelope)

### Kick instrument settings
* mod send / modulate: 64 / 1

### String instrument settings (sidechain ducking example)
* mod send / modulate:  0 / -1

### String instrument settings (50% compressionexample)
* mod send / modulate:  32 / -1

### peak management of master output (using silent kick e.g.)
* mod send / modulate:  32 / -2

> I would advice against this approach, as i'm sure it will kill productivity, compared to the age-old slide up/down effects.

**Comment by jangler** [comment]
Sooo unfortunately it looks like S99 was added to the help text in 2009 as a joke (see commit 2bdc94c). It's not an Impulse Tracker effect command, and OpenMPT uses it (and S9A, and S9B) for something different, so I'm just going to remove that line from the help text…
