### ISSUE TITLE
[Feature request] Support loading OPL instruments from MPTM files

### ISSUE THREAD

**Issue by cs127** [schismtracker/schismtracker#263]
I know MPTM is not exactly supported, but MPTM files are basically just IT but with more features, and most MPTM files can be opened with Schism Tracker, they will just sound a bit wrong because of not supporting the MPTM features.

Schism Tracker already supports loading S3M files with OPL instruments, so would it be possible to also support loading OPL instruments from MPTM/IT files?

**Comment by jangler** [comment]
> most MPTM files can be opened with Schism Tracker

Where are you getting this info? I tested just now, and MPTM files aren't even displayed in the Load Module list in Schism. MPTM isn't mentioned once in the source code either.

**Comment by cs127** [comment]
> > most MPTM files can be opened with Schism Tracker
> 
> Where are you getting this info? I tested just now, and MPTM files aren't even displayed in the Load Module list in Schism. MPTM isn't mentioned once in the source code either.

They don't appear in the list, but they can still be opened as IT files, because they **are** IT files, but with more features.

Again, I know that MPTM files (or their non-IT features) aren't really supported, but I was thinking that because Schism Tracker already supports OPL instruments in S3M files, it would be possible to support them in MPTM/IT files.

This page in the OpenMPT wiki might be helpful:
https://wiki.openmpt.org/Development:_OpenMPT_Format_Extensions#OPL_Instruments

**Comment by sagamusix** [comment]
Yeah, it would be fairly easy to support them in SchismTracker, and only being able to read them (but not write them in IT files) should be a fairly non-controversial addition.
