### ISSUE TITLE
A00 commands in MOD (but not XM) should be ignored

### ISSUE THREAD

**Issue by cs127** [schismtracker/schismtracker#265]
Schism Tracker converts A00 commands in MOD/XM to D00, but they actually should be ignored in MOD files.

**Comment by jangler** [comment]
I believe this should also be the case for the arpeggio, portamento up/down, fine portamento up/down, retrigger, and fine volume slide up/down commands.

**Comment by cs127** [comment]
Yes, I forgot about those ones.
Also, isn't arpeggio with a parameter of 00 (000) already ignored?

**Comment by BKVad1m** [comment]
1st type
![image](https://user-images.githubusercontent.com/76803825/193764782-3d4fc85d-8e97-4420-8b96-1347a6cd82d9.png)
this code in player/effects.c
2nd type
	case FX_SPEED:
		if ((csf->flags & SONG_FIRSTTICK) && param > 0x00) {
			csf->tick_count = param;
			csf->current_speed = param;
		} if (param == 0x00) {
			song_stop();
		}
		break;
