### ISSUE TITLE
Setting AUDIODEV= before running schismtracker has no effect

### ISSUE THREAD

**Issue by vcaputo** [schismtracker/schismtracker#270]
I wanted to instruct schism to use my USB MBox when attached by simply telling it to via the SDL AUDIODEV variable.

After wasting way too much time trying to understand why ALSA was being uncooperative, it turns out schism is actively unsetting this variable @ https://github.com/schismtracker/schismtracker/blob/20210525/schism/audio_playback.c#L1241

By simply commenting out the _audio_set_env_vars() call @ https://github.com/schismtracker/schismtracker/blob/20210525/schism/audio_playback.c#L1280  I am finally able to get my `plughw:MBox,0,0` used properly via `AUDIODEV=plughw:MBox,0,0 ./schismtracker`.

Not clear what should be done to fix this, but it seems totally user-hostile to be throwing out user-specified SDL1.2 env vars

**Comment by jangler** [comment]
Yeah, unsetting the env vars without any stated rationale is very weird. Schism does look like it has a way around this via the `--audio-driver` command-line option and equivalent `driver` config file option. Do those also work for you?

**Comment by vcaputo** [comment]
It does appear I can work around this by specifying `--audio-driver=alsa:plughw:MBox,0,0`, and I suppose I should have been able to discover this via reading `configuration.md`.

But I think there's arguably a bug here in how schism is silently interfering with otherwise established SDL1.2 environment variables.

If schism insists on unsetting and mangling these, it'd be better to at least detect if they were set a priori and say something in stderr/message log about their being ignored+overridden.  Perhaps mentioning instead put what you'd normally put in AUDIODEV=, after `$driver:` in --audio-driver/config::Audio::driver.

Thanks for the quick response.

**Comment by jangler** [comment]
Ran into this while testing the SDL2 port; it also ignores `SDL_AUDIODRIVER`, which isn't great either. If I had explicitly specified an `--audio-driver` or put a `driver=` line in the `[Audio]` section of my config file, that'd be one thing, but I didn't do those things, and overriding env vars with an implicit default is not something that should be happening.

**Comment by mrpapersonic** [comment]
Ok, I've taken a shot at this. [This](https://github.com/mrpapersonic/schismtracker/actions/runs/2879256129) build checks if the vars are already defined or not. If they aren't, it tries sets the drivers that are listed in the config, and *then* tries the defaults.
