### ISSUE TITLE
Crash on Mac OS Catalina because of a library not found error

### ISSUE THREAD

**Issue by KungFuFurby** [schismtracker/schismtracker#273]
Courtesy of Mac OS Catalina 10.15.7 (this is from the build that was provided via Github Actions CI on 11/15/21 via commit f2d8f759fc850758182a3f40d7e0d1878db6ffa0)...

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/sdl/lib/libSDL-1.2.0.dylib
  Referenced from: /Volumes/VOLUME/*/Schism Tracker.app/Contents/MacOS/schismtracker
  Reason: image not found
```

The build I have from 4/12/20 used `@executable_path/libSDL-1.2.0.dylib` instead, as indicated in the binary.

It looks like travis.yml had the right approach with the `install_name_tool -change /usr/local/opt/sdl/lib/libSDL-1.2.0.dylib @executable_path/libSDL-1.2.0.dylib ./schismtracker/Schism\ Tracker.app/Contents/MacOS/schismtracker` command, since a copy of libSDL-1.2.0 is included with the application distribution. Executing that exact command allows me to boot Schism Tracker right up.

**Comment by jangler** [comment]
Does this artifact work for you? https://github.com/schismtracker/schismtracker/suites/4372428403/artifacts/115029287
Excuse the fact that there's a zip inside a zip.

**Comment by KungFuFurby** [comment]
Certified working on my end, since it boots up and runs successfully.

**Comment by jangler** [comment]
Fixed in new release then.
