### ISSUE TITLE
Broken app bundle version number in MacOS download

### ISSUE THREAD

**Issue by suschizu** [schismtracker/schismtracker#275]
Hello!
The version number shows 'CFBundleShortVersionString' instead of 20211116 in download https://github.com/schismtracker/schismtracker/releases/download/20211116/schismtracker-20211116-macos.zip

<img width="233" alt="Screen Shot 2021-11-17 at 16 27 37" src="https://user-images.githubusercontent.com/16004333/142219180-fa718115-055b-4b06-9efb-97c7330cc03f.png">

**Comment by jangler** [comment]
I see from looking at Info.plist that CFBundleVersion is also a placeholder.

**Comment by jangler** [comment]
Fixed for future releases in be9c051.
