### ISSUE TITLE
Opening Scream Tracker 3 modules results in warped panning

### ISSUE THREAD

**Issue by mrpapersonic** [schismtracker/schismtracker#278]
When opening a normally fine S3M file, the panning gets warped from 32 to 34.
This effect can be replicated within Schism Tracker itself by saving a module with channel panning set to 32. Upon reopen, it gets warped to 30.

**Comment by jangler** [comment]
The panning resolution in ST3/S3M is lower than in IT, so not all values can be saved and loaded accurately. Impulse Tracker and OpenMPT seem to behave the same as Schism does in this regard.

**Comment by sagamusix** [comment]
Indeed it's expected that IT's 65 distinct pan position somehow have to be mapped to ST3's 16 pan positions. So unless you mean that you saw a file being imported with a panning of 34 but after resaving it shows up as 30 instead, there's no bug. Loading and saving the same S3M file should result in exactly the same value being loaded and saved.
