### ISSUE TITLE
Mono multitrack exporting seems glitchy

### ISSUE THREAD

**Issue by ZoeB** [schismtracker/schismtracker#280]
Hi!  Great program.  It's been a real blast tracking again.

I may have found a bug: If I have a mono .it file, and try to export it to multitrack .wav, the result seems glitchy and slow sounding, as if it's still sending stereo information or something.  Making the module stereo and re-exporting the multitrack .wav works around the issue.  Exporting a single .wav works fine in mono or stereo.  It's just the mono module, multitrack export combination that seems to have an issue.  (I'm using macOS.  I don't know if the issue's OS specific or not.)

Thank you for your time!

**Comment by jangler** [comment]
Reproduced, not OS-specific. Problem exists for MAIFF as well as MWAV.
