### ISSUE TITLE
MAIFF export sometimes exports files that are too short

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#281]
When exporting the attached file via MAIFF, the sound file for the first channel is only 8 seconds long. It should be 29 seconds, like the other 3 channels. Whether the module is mono or stereo does not matter. MWAV does not have this problem.

[schism_issue_281.zip](https://github.com/schismtracker/schismtracker/files/7721327/schism_issue_281.zip)

**Comment by sagamusix** [comment]
Was #124 only fixed for WAV and not for AIFF export maybe?

**Comment by jangler** [comment]
Yes, good catch. I had completely forgotten about that issue. The same fix worked for MAIFF.
