### ISSUE TITLE
adlib instrument not displayed correctly on sustain ?

### ISSUE THREAD

**Issue by fabbricius** [schismtracker/schismtracker#284]
Hello,

I'm trying to use adlib instrumenst, and I noticed that one of the parameters in the two OPL2 operators is not displayed correctly.
I've downloaded adlibtracker2 SDL, it is bundled with songs, and among them there are some s3m modules that are built only with adlib instruments (that's why they are included I guess). 
I compared the instruments between AD2 and schismtracker, and noticed that the SUSTAIN parameter is in fact displayed as its complement to 15. For instance, if the sustain parameter is set to 15 in AT2, it is displayed as 0 in schismtracker. If it's set to 5 in AT2, then it will be shown as 10 in schism. I've checked in OpenMPT and the value seems to be in line with AT2, although the way it's presented is different (it's a cursor on a bar).

To investigate, I've checked the S3M format. I found two documents:
[http://www.textfiles.com/programming/FORMATS/stracker.pro](http://www.textfiles.com/programming/FORMATS/stracker.pro)
[https://github.com/lclevy/unmo3/blob/master/spec/s3m.txt](https://github.com/lclevy/unmo3/blob/master/spec/s3m.txt)

The Sustain parameter is described like this in the second doc I've mentionned:

 **D06=[15-sustain]*16+[release]	=D07**

(D06 concerns the modulator, D07 is for the carrier)
The [15-sustain] could explain the value. 
I'm not an expert at all on adlib, so I might be wrong!

Cheers, and keep up the good work on schismtracker, it rocks!

**Comment by jangler** [comment]
Schism's OPL interface is based on Scream Tracker 3's, which displays the sustain parameter the same way. ~~I believe this is also the way the values are represented in actual register writes to the sound card.~~ So this is working as intended.

**Comment by jangler** [comment]
Correction for future reference: the values as stored in ST3 modules and instruments are the same as register writes; the "15-sustain" editor value is displayed differently, as you mentioned.

**Comment by fabbricius** [comment]
ok, I get it, thanks for the clarification !
