### ISSUE TITLE
disabling midi output and tracker crashed

### ISSUE THREAD

**Issue by BKVad1m** [schismtracker/schismtracker#286]
https://user-images.githubusercontent.com/76803825/158575461-6757308a-d533-45a4-bb86-8d38df25e3a8.mp4

**Comment by jangler** [comment]
Seems like a duplicate of https://github.com/schismtracker/schismtracker/issues/51

**Comment by vcaputo** [comment]
@Vad1mCSO2 confirm by reproducing the crash running schism from a terminal.

You should see output like https://github.com/schismtracker/schismtracker/issues/51#issuecomment-355833573 if it's the same problem.

We never worked on an automated buffer size enlargement when too small for the assertion, and didn't remove the assert().  You can probably work around it manually by setting a larger buffer size in the config, if it's the same problem.  But it has been a while, my recollection of the details is fuzzy.  IIRC A bug was fixed surrounding the buffer size arithmetic, but it didn't change the fact that a too-small buffer could still hit the assert.
