### ISSUE TITLE
Feature request: advanced rows (1-1024) per pattern in pattern editor options like Impulse Tracker PREMIUM [Default 32-200]

### ISSUE THREAD

**Issue by BKVad1m** [schismtracker/schismtracker#295]
![image](https://user-images.githubusercontent.com/76803825/174476538-1d8024c4-52e3-4ff5-a2c4-212f1e4ac205.png)
I'm saving 1024 rows in MPT and load schism tracker
I'm saving 1024 rows in Schism tracker and can be saved like impulse tracker premium
![image](https://user-images.githubusercontent.com/76803825/174476582-f61c4b26-8d37-46b7-ae15-31df57acd3e5.png)
MPT hack = **Schism Tracker Hack**

**Comment by sagamusix** [comment]
Yes, SchismTracker can load such files, but SchismTracker is an Impulse Tracker clone first and foremost - so while it can load and play some files extending the original IT limits, I don't think it's a good idea to allow these non-standard extensions to be available from the GUI by default.
