### ISSUE TITLE
Bug crash: loading some file and tracker crashed

### ISSUE THREAD

**Issue by BKVad1m** [schismtracker/schismtracker#296]
loading some files in module library and my schism tracker crashed!

**Comment by jangler** [comment]
Can you attach the file or files that Schism crashed on?

**Comment by BKVad1m** [comment]
> Can you attach the file or files that Schism crashed on?

any

**Comment by sagamusix** [comment]
Well, it seems like you were able to load at least XM and MPTMs file in #297 and #298 respectively, so "any file" is obviously not true. Please provide the files you are having issues with, otherwise there is nothing that can be done here and we'll have to close the issue.
