### ISSUE TITLE
[Concept module format] .bkm based as MPT can be loaded as impulse tracker with adlib

### ISSUE THREAD

**Issue by BKVad1m** [schismtracker/schismtracker#298]
https://youtu.be/rW-xIbXjDXQ
request to add feature to save .bkm module format

**Comment by jangler** [comment]
You *really* need to include more information in the issues you open. Like, for example, any detail at all on what ".bkm module format" is, other than MPTM files you've renamed for some reason (???). I've never heard of that format, and I don't get any useful results for the usual Google searches.

**Comment by BKVad1m** [comment]
NOTE: This is experemental module format
