### ISSUE TITLE
Red and blue video channels swapped when resizing the window

### ISSUE THREAD

**Issue by cs127** [schismtracker/schismtracker#301]
When resizing or maximizing the Schism Tracker window, the red and blue channels of the GUI colors are swapped.
However, this only happens if the video driver is set to SDL Video Surface or OpenGL Graphic Context in the System Configuration screen. YUV Video Overlay is not affected.

I'm using Arch Linux, with Schism Tracker 20220506 installed from the AUR. I also have an Nvidia graphics card I'm using the proprietary drivers.

**Comment by jangler** [comment]
Same issue here on Fedora, with or without `SDL_VIDEODRIVER=x11`.

**Comment by jangler** [comment]
Are you by any chance using Wayland?

**Comment by cs127** [comment]
> Are you by any chance using Wayland?

No, X11

**Comment by cs127** [comment]
Also, this probably isn't related to the issue, but the video driver setting is reset to SDL after I close and reopen the program (even after clicking "Save All Preferences" in the variables screen). How do I fix that?

**Comment by jangler** [comment]
Not sure, but I can reproduce that issue with whatever version Fedora ships as well.

**Comment by illettante** [comment]
Blue colour issue occurs on MacOS too, SDL only.

**Comment by jangler** [comment]
Fixed in 869c01e.

**Comment by cs127** [comment]
thanks!
