### ISSUE TITLE
Feature Request: highlight row [000] in info page like scream tracker 3

### ISSUE THREAD

**Issue by BKVad1m** [schismtracker/schismtracker#302]
![image](https://user-images.githubusercontent.com/76803825/177090010-3b053785-503c-420b-9ab6-58d2aa49525e.png)

**Comment by esaruoho** [comment]
that would be pretty neat, sure

**Comment by jangler** [comment]
Schism is an Impulse Tracker clone, so if IT doesn't do this it would be inappropriate to do by default, and it doesn't seem worth another config option.

**Comment by esaruoho** [comment]
@jangler hey, what makes you think IT doesn't do it?

**Comment by jangler** [comment]
The title of the issue
