### ISSUE TITLE
macOS file loading seems to be broken

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#308]
On macOS, after the SDL2 update, file loading seems to be broken. It asks for file permissions an extreme amount of times, every file it loads in a folder. Plus, the config seems to not work either.

Some examples:
Despite resolution being set to 1280x800 in the config, it still loads at its default resolution.

![image](https://user-images.githubusercontent.com/46719718/184735242-cef75295-6a6f-4ae2-9f63-a2e2cf0de1dd.png)

Opening a folder takes a while with all of these popups.

https://user-images.githubusercontent.com/46719718/184735708-f78513b3-134e-49a0-9b57-ef9b5c90d19c.mp4

**Comment by jangler** [comment]
Are any other config options broken? Or just the display resolution? Asking since video was one of the largest changes in the SDL2 update; it would make more sense to me for just the resolution option not to work rather than the entire config not working.

**Comment by ghost** [comment]
The general config does still seem to work.
![image](https://user-images.githubusercontent.com/46719718/184788425-4dff13fd-e26a-42d9-8510-8f62c0d02a14.png)

**Comment by ghost** [comment]
Also, I tried enabling full disk access under the privacy settings, but the permission popups still occur.

**Comment by mrpapersonic** [comment]
The resolution config is easy to solve, it's on line 258 and 259 of video.c, just replace NATIVE_SCREEN_HEIGHT and NATIVE_SCREEN_WIDTH with cfg_video_height and cfg_video_width.

Are you running Schism from the Desktop/Documents/Downloads? From a quick search moving it to `/Applications` may be the fix for the directory issue.

**Comment by ghost** [comment]
I moved it to `/Applications` and it still happens.

**Comment by illettante** [comment]
This issue doesn't seem to occur for me (2019 Intel MacBook Pro, macosx12.5.1, SIP enabled), in either the binary release or building from source. That's probably not helpful for @evynhh specifically, but hopefully more information is better than less, generally speaking? 
Also thanks @mrpapersonic, Schism ignoring the config height and width was vexing me.

**Comment by ghost** [comment]
I tried the new September build, and it's still occurring for me. Should probably mention I'm on an M1, also running macOS 12.5.1.

**Comment by digistorm79** [comment]
You can't load files from the Finder anymore since version 20220807. It just opens the file dialog. So shell integration is also broken.

**Comment by jangler** [comment]
@digistorm79, can you open a new issue for that?

**Comment by Q-mii** [comment]
Yeah, I've been having problems here too.

**Comment by jangler** [comment]
Today's release has some macOS-related changes in it. Can someone test and let me know whether these issues are still present?

**Comment by digistorm79** [comment]
Shell integration is working again. Browsing on external and network volumes is also working fine. This was tested on macOS 13 Ventura with a M1 Pro mac.

**Comment by ghost** [comment]
After updating to macOS 13 (and updating Schism), it seems to be working fine now.
