### ISSUE TITLE
Can't run Schismtracker SDL2 because it fails to use the audio driver

### ISSUE THREAD

**Issue by vanfanel** [schismtracker/schismtracker#309]
Hi,

I have just built Schismtracker from latest GIT sources today.
My system has working ALSA audio, and SDL2 on top of that, so all programs using ALSA directly OR using SDL2 work fine, except Schismtracker.

I  see this when trying to run it:

```
~/src/schismtracker# ./schismtracker 
Audio target 'dummy' not available
Couldn't initialise audio!
Segmentation fault
``` 

Specifying driver=alsa on the [Audio] section of the config file, I see this;
```
~/src/schismtracker# ./schismtracker 
alsa: Audio target 'dummy' not available
Audio target 'dummy' not available
Couldn't initialise audio!
Segmentation fault
```
So, what's going on here? Any ideas, please? Programs should simply use the defaults, be it ALSA or SDL2...

**Comment by jangler** [comment]
Not sure; this hasn't happened to me. Can you post the contents of your `~/.schism/config` and the output of `env | grep SDL`?

**Comment by vanfanel** [comment]
@jangler Yes, of course. This is my **~/.schism/config** file:

```

[Audio]
sample_rate=44100
bits=16
channels=2
buffer_size=1024
master.left=31
master.right=31
[Mixer Settings]
channel_limit=128
interpolation_mode=1
no_ramping=0
surround_effect=1
[EQ Low Band]
freq=0
gain=0
[EQ Med Low Band]
freq=16
gain=0
[EQ Med High Band]
freq=96
gain=0
[EQ High Band]
freq=127
gain=0
[Video]
interpolation=
fullscreen=0
mouse_cursor=0
lazy_redraw=0
[General]
vis_style=2
time_display=1
classic_mode=0
make_backups=1
numbered_backups=0
accidentals_as_flats=0
meta_is_ctrl=0
altgr_is_alt=1
midi_like_tracker=0
```

And since I haven't any SDL env variables, `env | grep SDL` is empty.

**Comment by vanfanel** [comment]
@jangler 

Found the problem.
It's exactly in this code section in `_audio_open()`:
```

        if ((driver_name = SDL_GetCurrentAudioDriver()) != NULL && !strcmp(driver_name, "alsa")) {
                char *dev = getenv("AUDIODEV");
                if (!dev || !*dev)
                        put_env_var("AUDIODEV", "hw");
        }
```

What you do here is: if SDL audio driver is alsa, use an alsa device name starting with "hw", which isn't the default audio device used by SDL2 but a forced hardware device.
I am all for using hardware devices, but let SDL2 decide (and the user, based on his /etc/asound.conf).

Commenting out that piece of code, schismtracker works here.

**Comment by jangler** [comment]
Thanks for looking into the problem! I agree that Schism should use the configured environment instead of overriding it with its own configuration (see also #270). I just wonder if I need to worry about breaking people's configs if this is changed.
