### ISSUE TITLE
Aspect ratio option?

### ISSUE THREAD

**Issue by vanfanel** [schismtracker/schismtracker#311]
Hi,

Even if Impulse was originally 640x400, fullscreen should have an option to be aspec-corrected on modern 16:9 screens: it originally filled 4:3 monitors.

It's very easy to do, using https://wiki.libsdl.org/SDL_RenderSetLogicalSize

You seem to be doing ratio correction here already:
https://github.com/schismtracker/schismtracker/blob/26066177bfdb53913534ac412ed3ffff7b70370f/schism/video.c#L277

..but you do it using the host screen size. An solution could be that `SDL_RenderSetLogicalSize()` in **video_resize()** uses 4:3 if the hypothetical aspect ratio option is ON.

For now, I will force 4:3 on my own builds :)

**Comment by vanfanel** [comment]
@jangler Did you consider this?

**Comment by jangler** [comment]
It's a fine suggestion; I just haven't had much time for Schism dev lately. I would be happy to merge a PR that introduces such an aspect ratio option.
