### ISSUE TITLE
OS support question and missing wiki

### ISSUE THREAD

**Issue by cyberluke** [schismtracker/schismtracker#313]
I beg your pardon, but could not find this information on your wiki and could not find any contact information either and don't have enough knowledge to understand what SDL 2 means in terms of OS requirement.

You mention Windows support. As your software is based on a historical software, I would like to use it on the oldest machine possible, together with other retro audio hardware (PCI based or ISA based).

Which Windows version you require? I guess it will work in Windows XP, right? What about Windows 98 SE?

There are some SDL apps ported to FreeDOS as well. But I guess this is not automatic.

I think that SDL 2 does not work on Windows 98 (not sure). But you mention some rewrote from SDL 1 to SDL 2.

It would be nice, for retrogaming community, that there would be this information listed in README.md and on top of it a link to your latest commit or branch with SDL 1 support (as well as binary download - that would be a cherry on top).

On wiki, I did not find the advertised compilation instructions for other platforms either.

Ok, now I found it here: https://github.com/schismtracker/schismtracker/blob/master/docs/building_on_windows.md ...it is difficult to find, and it would be nice to have custom paragraph on wiki. Not just one hypertext link - it is difficult to find.

And when you update these instructions for SDL 2, as mentioned in TODO, could you please create a separate document for that? 

It is historically important to preserve knowledge and it is very valuable for us, who want to backport or support opensource truly as we should as united community. 

Thank you very much and good luck! Great job so far!

**Comment by sagamusix** [comment]
https://wiki.libsdl.org/FAQWindows says Windows XP. I wouldn't be surprised if previous SDL1-based builds already required Windows XP since many toolchains simply require NT APIs that are not present on Win9x.

On Windows 98, you are better off running Impulse Tracker directly. Impulse Tracker can actually make much better use of your retro hardware than a clone that was written to be used on systems *not* supported by Impulse Tracker.

**Comment by cyberluke** [comment]
The FAQ says requirements SDL2 is for Windows XP. 

**About SDL1:**
I could not find any requirements on libsdl.org, but SDL 1.2 is normally compiled on Windows 95 even: https://www.vogons.org/viewtopic.php?t=46693

**Current state of Windows 98 in retrogaming community worldwide:**
There is game CyberDogs remake in SDL1 and I got it working on Windows 98SE. With KernelEx. Nowadays Win9x is not the same as 1998. I even play Trackmania Nations (XP only game) online on W98 and have 4GB Ram available on W98 and got it running on Core2Duo.

**Note**
Just preserve SDL1 documentation as well, please and perhaps create SDL1 branch. It can be community supported by people like me. I do not ask anything more, I understand your team might not be willing to spend any time with it and that is perfectly ok.

**Comment by cyberluke** [comment]
I don't know how old are you, I am born 1987 and I remember SDL was "the thing" back in 1998 and here is official repo that still is updated occasionally with critical stuff: https://github.com/libsdl-org/SDL-1.2

The current version supports Linux, Windows CE/95/98/ME/XP/Vista, BeOS, MacOS Classic, Mac OS X, FreeBSD, NetBSD, OpenBSD, BSD/OS, Solaris, IRIX, and QNX. The code contains support for Dreamcast, Atari, AIX, OSF/Tru64, RISC OS, SymbianOS, Nintendo DS, and OS/2, but these are not officially supported.

**Comment by cyberluke** [comment]
So while SDL2 might fix JACK audio in Linux, it kills half of the platforms that were supported before. My goal will be to preserve that. It would be nice to seperate that in your SDL1 branch and update Readme.md accordingly. That would be enough.

**Comment by sagamusix** [comment]
> It can be community supported by people like me.

If you want to maintain an up-to-date SDL1 branch, go for it. The fact that SchismTracker switched to SDL2 without leaving SDL1 as a fallback is precisely because *nobody* wanted to do the hard work of maintaining both SDL1 and SDL2 support at the same time. You can still run old SchismTracker versions on systems no longer supported by SDL2, but don't expect that other people will do the extra work required to maintain suppport for these platforms on newer builds.

> it kills half of the platforms that were supported before

Virtually noone was running SchismTracker on these platforms. If you have very scarce resources for maintaining a project (like SchismTracker does), you have to spend those resources where the users are, and that is somewhat modern Windows/macOS/Linux systems in the case of SchismTracker. Again, Impulse Tracker is the logical choice to run on Windows 98.

**Comment by cyberluke** [comment]
Yes, and while that sounds reasonable, I only ask for a little bit of more precision when doing breaking changes. Even SDL themselves have v1.2 in separate repo. They did not glue it on top. That's how Microsoft develop :-) and it is not a good habbit.

And I did not say these two branches must be kept in sync. It is just for preservation, so who want to try older SDL1 version or do something with it, he has the freedom and opportunity.

There is no pressure. Only be a little bit more precise and preserve the last working SDL1 commit either in separate repo or in separate branch. It is also for people to be easier to find because I don't want to fork every github project like that and then make Youtube with instructions about it.

I will make Youtube with instructions (probably next year), but it would be better if it would be located here, so people can easily find it. Also you are organization while I am a single person, if something happens to me, it might be more difficult.

This preservation thing started for me personally during first COVID lockdown, that time I bought 386 + 486 + Pentium again and I start to talk with similar people and I found tens of people jump on that wave at that time. So it seems during pandemic, people start to be less consumerism influenced. Of course it is not the mainstream and never will be.

Maintainer should only say: "We did this breaking change here and you can find last old build here and last source here in this branch. It is up to community to take care of it" - something like that - just a simple gesture of good will and not spaghetti style of work.

**Comment by jangler** [comment]
> Which Windows version you require? I guess it will work in Windows XP, right? What about Windows 98 SE?

I think you're vastly overestimating the development resources we have, to think we might be testing new versions on Schism on every version of Windows ever released to make sure it still works.

You know the operating systems and library versions you're talking about haven't been supported by their own vendors in quite some time, right? Building on top of that kind of foundation was never a goal for Schism, at least as far as I was aware.

Anyone who needs a pre-SDL2 version for a niche operating system is free to download it from the releases page.

**Comment by vcaputo** [comment]
Not to mention both the releases and tags pages already reference their respective commits for anyone who wants to checkout the relevant state of the source tree.

It couldn't hurt to toss a mention in the docs somewhere to the last SDL1.2-utilizing release though.  It's only going to become less clear at which point they diverged as more releases accumulate.  And it's probably sane to throw up an appropriately named tag pinning the last SDL1.2 commit.  It's not like that's a commitment to maintaining an SDL 1.2 branch up here.  It at least simplifies the task of identifying where exactly the former world ended should anyone need to do so.

**Comment by cyberluke** [comment]
Yes, guys. Can you just put the fucking info and be like senior developers pretty fucking please? Why I need to discuss so much? It should be normal. Just create SDL1 branch and don't care. That's it. Talk like kids really.

Someone come here a year later and it will get lost.

It is basic professionalism to only document it somewhere and I will send some pull request in SDL1 branch in 4 months.

**Comment by vcaputo** [comment]
> Yes, guys. Can you just put the fucking info and be like senior developers pretty fucking please? Why I need to discuss so much? It should be normal. Just create SDL1 branch and don't care. That's it. Talk like kids really.
> 
> Someone come here a year later and it will get lost.
> 
> It is basic professionalism to only document it somewhere and I will send some pull request in SDL1 branch in 4 months.

That's entirely inappropriate, and speaking of professionalism try practicing what you're preaching.

**Comment by cyberluke** [comment]
The amount of polite characters I wrote here  crossed the threshold and triggered bad AI. Also it might be health condition, if someone is too smart on the border with slight autism, it might be more difficult to communicate and even with that in mind I think I tried to explain it here professionally enough.

**Comment by 8bitbubsy** [comment]
I can't possibly understand how you have the audacity to attack the developers for not supporting OSes that are over _two decades_ old. Remember; these are non-profit projects, worked on by people in their spare time. By phasing out old OSes over time, you are potentially simplifying the workflow. Also in some cases it allows you to think forward instead of having to make compromises.

**Comment by cyberluke** [comment]
I don't understand how you cannot simply read what I wrote:
- I don't ask for support
- I don't ask for support
- I don't ask for support
- I don't ask for support
- I don't ask for support
- I don't ask for support

Is it clear now?

Do you know what I ask for?

**Comment by cyberluke** [comment]
I am the one, who is willing to make the work. The only thing I ask for is:
- Be more precise in documentation
- Don't think that in one or two years someone will find some commit in history and connect the dots
- Instead of mentioning that you have some commit X from year Y, separate that now to branch SDL1. Put in readme: DEPRECATED and UNSUPPORTED 

That is all I'm asking. Separate & preserve.

**Comment by cyberluke** [comment]
Added the fork here: https://github.com/cyberluke/schismtracker/tree/SDL1 - that was the minimum you could do in three mouse clicks. (I will need to revert the HEAD when I'm near computer)

I'm busy now on some other project, but plan to get back to it in 4-5 months.

In the meantime I will do the following (that was on plan from my side):
Set up Github Actions custom pipeline with automatic builds of incoming commits from `master` branch to `SDL1` branch. Commits that will contain keyword 'SDL2' on any line will be automatically skipped.

It is not rocket science, just little bit of sensible software engineering.

Next year I will promote SDL1 branch and perhaps will have time to record some Youtube video as well.

I don't say you are not skilled coders here, but it is strange that you lack some kind of common sense / clean code / project management skills (sorry to say that, but so far it looks like that - I can change my opinion in the future though), when nobody asks you for support, just creating a branch, so it is easier for people to find it. And I came here right when I discovered this breaking change. It happened on May, so would not even trust that you know your userbase - how everyone is using it. I think ordinary user will not come to Github or open some issue.

**Comment by 8bitbubsy** [comment]
I don't think lack of common sense and sensible software engineering is the problem here, but rather priorities. With your attitude, it's even easier to lose interest in a hobby project.

**Comment by ghost** [comment]
Would it suffice to replace the paragraph in the readme that reads:

Where Impulse Tracker was limited to i386-based systems running MS-DOS, Schism Tracker runs on almost any platform that [SDL](http://www.libsdl.org/) supports, and has been successfully built for Linux, Mac OS X, Windows, FreeBSD, AmigaOS, BeOS, and even [the Wii](http://www.wiibrew.org/wiki/Schism_Tracker). Most development is currently done on 64-bit Linux. Schism will most likely build on _any_ architecture supported by GCC4 (e.g. alpha, m68k, arm, etc.) but it will probably not be as well-optimized on many systems.

with something like: 

Where Impulse Tracker was limited to i386-based systems running MS-DOS, Schism Tracker runs on almost any platform that [SDL 
 2](https://www.libsdl.org/index.php) supports. Currently builds are provided for Linux, Mac OS X, and Windows. Most development is currently done on 64-bit Linux. Schism will most likely build on _any_ architecture supported by GCC4 (e.g. alpha, m68k, arm, etc.) but it will probably not be as well-optimized on many systems.

and then remove, or mark as deprecated, the build instructions from the wiki for the platforms that are unlikely to work anymore?

edit: I have done it here #314

edit2: You can find 2011-2015 builds for Windows, Linux and Mac here if that's helpful to you:
https://ftp.modland.com/pub/software/trackers/Windows/Schism%20Tracker/
https://ftp.modland.com/pub/software/trackers/Linux/Schism%20Tracker/
https://ftp.modland.com/pub/software/trackers/Mac/Schism%20Tracker/

**Comment by jangler** [comment]
I've added a `sdl1` tag set to `20220807^` (the last commit before the SDL2 PR was merged). IMO a branch is semantically inappropriate since development on SDL1 is not meant to continue. I'm not convinced that linking unsupported versions in the README is appropriate either, nor do I think we should keep old build instructions in the current tree (once the instructions are actually updated, of course). You need to check out an older version of the tree to build an older version of Schism, anyway.

And @cyberluke, in case it's not clear to you, your first post did in fact make it sound like you expected support for very old versions of Windows.

**Comment by cyberluke** [comment]
Yes, first post: I had to clarify what is current status first. Because I am not primarily SDL developer. I did not expect to unpack a loads of problems and waste everyone's time.

It's a good practice to separate and preserve something in the branch. You still don't get it and I don't have resources to convince you. But I tried to point that even SDL, the framework you use, does this. So I was hoping it will be something close to your way of doing things with the respect of best practices of framework developers you look up to.

I also found out that forking your github project does not preserve tags, which is unfortunate. These are the little bits that you only break due to lack of utilising tools properly.

I don't want to be a critical, even I am often critical here, I just try to point out why the decision is not good. 

Stale branch does not always mean something bad.

Apprentice follows the rules blindly => Master knows when to break some rule (I hope it does not sound arrogant and you know this phrase - it means that first you learn the rules of programming language and tools and then you know when not to follow these rules - basically a common sense)

Well, the tags can be synced: https://stackoverflow.com/questions/70678073/how-do-i-sync-tags-to-a-forked-github-repo ...but I don't know why Github button does not do it by default. I was doing it on the road, will need to redo it. Thank you.

So Alea Iacta Est, be it here: https://github.com/cyberluke/schismtracker/tree/SDL1
