### ISSUE TITLE
JACK not working on new SDL2 port. Schism tries to use ALSA no matter what I do.

### ISSUE THREAD

**Issue by fuck-shithub** [schismtracker/schismtracker#316]
Hello. Today I found out schismtracker has finally switched to SDL2, so I expect JACK to finally work. In fact, I ported JACK to SDL 1.2 literally so I could get schismtracker working.
If you want said port, here's the patch: https://gist.github.com/fuck-shithub/47f60ac0ad01ab78506b9cce2011ccb2

But now schismtracker is using SDL2, so I would expect better than ever JACK support. But it is the contrary. Upon launching schismtracker, I get this:
Using dummy on SDL2
And the message log says this:
ALSA: Couldn't open audio device. Device or resource busy

Why is schism using ALSA? This makes no sense. SDL_AUDIODRIVER is set to jack, and even after removing schism's config file, it keeps trying to use ALSA. What's going on?

**Comment by jangler** [comment]
Sounds like #270 / #309. Basically, some developer made the bad design decision to ignore env vars by default, so for now, if you want to set Schism's audio driver, you'll need to use the `--audio-driver` option or the config file. But enough people have (justifiably) complained about this that I'd like to change the behavior in the next release.

**Comment by fuck-shithub** [comment]
`--audio-driver=jack` works, and adding `driver=jack` to the config file in the `[Audio]` category also works. Thank you
