### ISSUE TITLE
Duplication when typing a digit in the pattern editor

### ISSUE THREAD

**Issue by Zenoth** [schismtracker/schismtracker#317]
Hi. In the last two releases, in the pattern editor when you enter a digit in the volume or effect column, the digit is entered twice (it is repeated in the next column or if it is the second column it is repeated below).

Example:   
C-501  00  O33  <-- When typing the first "3", a second 3 is automatically typed next to it 

C-501  00  O03  <-- In this case, when a 3 is entered in the second column, a 3 is automatically entered below.
                    30

**Comment by jangler** [comment]
Looks like this was introduced in dbf0f1b, seems like SDL text input is "turned on" when it shouldn't be. Similar problems exist in a lot of other places in the UI.

**Comment by jangler** [comment]
@mrpapersonic can you explain the text input related changes in that commit? I'm asking because reverting it fixes this issue for me without introducing any other problems that I've noticed.

**Comment by mrpapersonic** [comment]
> @mrpapersonic can you explain the text input related changes in that commit? I'm asking because reverting it fixes this issue for me without introducing any other problems that I've noticed.

It changes the text input whitelist from being page-based to widget-based. Fixing this is a simple check for `k->is_synthetic` in the order/pan list key handler. I've already fixed this locally; I'll post the patch tonight when I get home.

**Comment by mrpapersonic** [comment]
```patch
--- a/schism/page_orderpan.c
+++ b/schism/page_orderpan.c
@@ -363,7 +363,8 @@ static int orderlist_handle_char(struct key_event *k)
 	default:
 		c = numeric_key_event(k, 0);
 		if (c == -1) return 0;
-		if (k->state == KEY_RELEASE)
+		if (k->state == KEY_RELEASE
+			|| !k->is_synthetic)
 			return 1;
 
 		status.flags |= SONG_NEEDS_SAVE;
```
This is effectively the same way I handled it here:
https://github.com/schismtracker/schismtracker/blob/b87702282138896c7f998c0bb75d8ee764747649/schism/widget-keyhandler.c#L771-L775

**Comment by jangler** [comment]
That fixes the note column in the pattern editor (why does it do that?) (edit: and the order list), but not the instrument column, the volume column, the effect parameter column, or the Instrument List note translation widget.

**Comment by Zenoth** [comment]
Hi. I wanted to ask if this problem will be fixed in the next release? And do you have a date when it could be? I thank you in advance, for me Schism Tracker is the best tracker around, and I'm glad you keep updating it.

**Comment by mitchvreed** [comment]
Hello, I am having this issue, so I searched here and I see others have the same. Please let me know if there is an update, I love Schism Tracker.
