### ISSUE TITLE
Shell integration on macOS no longer working since version 20220807

### ISSUE THREAD

**Issue by digistorm79** [schismtracker/schismtracker#320]
When clicking on a file in the Finder that is associated with Schismtracker, the file is no longer loaded. Schismtracker will launch, but just with the welcome screen. In previous versions, Schismtracker would launch and then automatically load the file that was clicked.

Old behavior:
<img width="752" alt="Schermafbeelding 2022-09-20 om 20 57 14" src="https://user-images.githubusercontent.com/45852917/191341840-aba7e40b-c66f-4794-a169-02e9c9eae601.png">

New behavior:
<img width="752" alt="Schermafbeelding 2022-09-20 om 20 57 33" src="https://user-images.githubusercontent.com/45852917/191341856-31a18bd0-d56e-443f-83c2-9e9505249368.png">

**Comment by jangler** [comment]
Can you test for me whether Schism handles command-line arguments correctly on macOS? For example, what if you open Terminal and type `schismtracker path/to/a/module.it`?

I also see that there was some `macosx-sdlmain.m` code contributed in 25784ce that's *definitely* wrong, although I'm not sure what the right fix is. I wonder if that's related.

**Comment by digistorm79** [comment]
It works when using the terminal. It doesn't work with the Finder. I tested the latest release version, 20221020. The output when launching from the terminal is:

> digistorm@Caesius MacOS % ./schismtracker ../../../../DOSBox/Music/MODULES/Artists/PM/INSPIRAT.S3M 
> objc[23342]: Class SDLApplication is implemented in both /Applications/schismtracker/Schism Tracker.app/Contents/Resources/libSDL2-2.0.0.dylib (0x104e9f4e0) and /Applications/schismtracker/Schism Tracker.app/Contents/MacOS/schismtracker (0x1045b4a28). One of the two will be used. Which one is undefined.

**Comment by asbjornu** [comment]
I've also noticed this problem. Probably something we can add an automated test for, perhaps? Related to #308.
