### ISSUE TITLE
Question: Original IT source code as reference?

### ISSUE THREAD

**Issue by Some1NamedNate** [schismtracker/schismtracker#326]
Just out of curiosity, when the [original source code to Impulse Tracker](https://github.com/herrnst/impulsetracker) was released under the New BSD License (or "Modified BSD License"), has it been used as reference material for aiding Schism Tracker's development by any means?

**Comment by jangler** [comment]
I've never looked at it, and the bulk of Schism development took place before it was released. I wouldn't be surprised if Saga Musix or some other contributor (possibly even before Schism migrated to GitHub) had used it as a reference at some point, though.
