### ISSUE TITLE
JACK audio driver not working ("jack: Audio target 'jack' not available")

### ISSUE THREAD

**Issue by loquesangra** [schismtracker/schismtracker#329]
`$ schismtracker --audio-driver=jack sweet\ dreams.xm`

jack: ALSA: Couldn't open audio device: No such file or directory

ALSA: Couldn't open audio device: No such file or directory

Couldn't initialise audio!

`$ export SDL_AUDIODRIVER=jack ; export AUDIODEV=jack`

`$ schismtracker --audio-driver=jack sweet\ dreams.xm`               

jack: Audio target 'jack' not available

Audio target 'jack' not available

Couldn't initialise audio!

**Comment by mrpapersonic** [comment]
Looks like your SDL wasn't built with JACK support.

**Comment by devloop0123** [comment]
> `$ schismtracker --audio-driver=jack sweet\ dreams.xm`
> 
> jack: ALSA: Couldn't open audio device: No such file or directory
> 
> ALSA: Couldn't open audio device: No such file or directory
> 
> Couldn't initialise audio!
> 
> `$ export SDL_AUDIODRIVER=jack ; export AUDIODEV=jack`
> 
> `$ schismtracker --audio-driver=jack sweet\ dreams.xm`
> 
> jack: Audio target 'jack' not available
> 
> Audio target 'jack' not available
> 
> Couldn't initialise audio!

Issue's been closed already, but I want to point out that, as mrpapersonic already implied, if you build SDL2 with Jack support, override your system's default with it (I just let cmake install SDL2 into /usr),  then compile schismtracker, then Schism works with Jack.
![jack](https://github.com/schismtracker/schismtracker/assets/163681888/952296b8-cc38-4b33-87d2-f059bb821e12)
