### ISSUE TITLE
Use schismtracker as VSTi in other DAWs?

### ISSUE THREAD

**Issue by tokariu** [schismtracker/schismtracker#333]
How about wrapping schismtracker up into vst-plugin so we could use it's instruments and awesome sampler/envelope features in other DAWs?
I was thinking a little bit on ReViSiT vst plugin which is kinda dead nowadays and schismtracker still got the drive.

**Comment by babatunde3** [comment]
I don't know about that one... I think it's best if you just use schism tracker because it's not rewire...

**Comment by mrpapersonic** [comment]
I don't think this is really worth the effort to put in the codebase neither the upkeep to maintaining it (nor am I particularly keen on working with *anything* from Steinberg)
