### ISSUE TITLE
macOS build problem in GH Actions

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#337]
See <https://github.com/schismtracker/schismtracker/actions/runs/3586014080/jobs/6034696121>. Might be a problem with [scripts/build-uni.sh](https://github.com/schismtracker/schismtracker/blob/master/scripts/build-uni.sh)? None of the Actions stuff has changed recently on our end.

**Comment by mrpapersonic** [comment]
Just a shot in the dark here, but it might just be a problem with permissions. Maybe running `chmod +x ../scripts/build-uni.sh` before configure would work.

**Comment by jangler** [comment]
Looks like that doesn't help, unfortunately.

**Comment by mrpapersonic** [comment]
Ok, I think I've found the problem. [GitHub is actively moving runners to macOS 12 Monterey](https://github.blog/changelog/2022-10-03-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-12/), but the script still utilizes the old SDKs from macOS 11.

So, the simplest solution is to change this line from `macos-latest` to `macos-11`.
https://github.com/schismtracker/schismtracker/blob/83d5f9c8f97698a24562f3e7779ff2e14b246ee0/.github/workflows/build.yml#L93

EDIT: It's also be a good idea to update SDL2 on macOS to 2.26.0 on lines 132 and 136.

**Comment by jangler** [comment]
Oddly, I got `error: SDL for Mac OS X only supports deploying on 10.7 and above` when trying that (<https://github.com/schismtracker/schismtracker/actions/runs/3587326002/jobs/6037537879>). The runner should be 11.x and the SDK should be 10.9, so I'm not sure why that's happening.

**Comment by mrpapersonic** [comment]
It's a new SDL minimum OS limit, at the top of [build-uni.sh](https://github.com/schismtracker/schismtracker/blob/master/scripts/build-uni.sh) 10.6 needs to be replaced with 10.7, and 1060 needs to be replaced with 1070.

**Comment by jangler** [comment]
Oh, I bet it's the `-mmacosx-version-min=10.6` in `scripts/build-uni.sh`.

**Comment by jangler** [comment]
jinx

**Comment by mrpapersonic** [comment]
SDL is bugged. :) https://github.com/libsdl-org/SDL/issues/6586.
Rollback to 2.24.2?
