### ISSUE TITLE
Actions: set-output deprecated

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#338]
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mrpapersonic** [comment]
I actually updated this in 97fa0efe0eb4ae7c64861f59cd7e5417265ea778, but I forgot to write it in the commit message.
