### ISSUE TITLE
Feature request: drag and drop samples/instruments

### ISSUE THREAD

**Issue by babatunde3** [schismtracker/schismtracker#341]
I'm tired of looking for samples in the software, and I would also love to have conversion of stereo to mono since the original Impulse Tracker didn't support stereo samples

**Comment by jangler** [comment]
Alt+Shift+D in the ~~pattern editor~~ sample list converts stereo samples to mono.

**Comment by jangler** [comment]
Shouldn't be too hard with <https://wiki.libsdl.org/SDL2/SDL_DropEvent>.

**Comment by sagamusix** [comment]
Done in c98f03f33735484f41a4ecd3306620cff691f542
