### ISSUE TITLE
Feature request: Headless mode

### ISSUE THREAD

**Issue by arisboch** [schismtracker/schismtracker#347]
Is there any chance, that a headless mode would be implemented? I'm using the schismtracker to convert chiptune files (.it, .xm, and so on) in a bash script, and would like to keep the program window hidden.

**Comment by sagamusix** [comment]
If by converting you mean converting to streaming formats (WAV, MP3, etc.), you could give [openmpt123](https://lib.openmpt.org/libopenmpt/) a try.

**Comment by arisboch** [comment]
@sagamusix Thanks a lot, the program you suggested does exactly what I need :)
