### ISSUE TITLE
Request: Ability to load various video game music formats (e.g. vgz/vgm, gym, nsf, spc etc.)

### ISSUE THREAD

**Issue by TinyXL** [schismtracker/schismtracker#350]
Hi !  Hope you're well? 
What it says on the tin I guess... I understand that with some of these formats there's a need to somehow insert/recreate/something the instruments since some of the formats are purely note data relying on a (fm) synth to create the tones. But really if even just the plain note stuff can be loaded the workload of searching for the right instruments can be shifted to the user (i.e. give them a warning that it's up to them to supply the sounds etc.).Not sure how hard or easy something like this is to implement. But whatever happens - Thanks for everything so far! <3

**Comment by ghost** [comment]
The problem with most of these formats is that they aren't module formats - i.e. they aren't just note data + instruments. Some of them are streams of data that get sent to the soundchip, and in some cases they are code that needs to be emulated which then generates the data that goes to the soundchip. That's so they can support all the different music engines and software used by different games from different developers, regardless of how the music is stored/generated by the game. But what it means in practise is that even simply getting note data is really tricky, compared to loading a module file where you know there's note data there and the differences between formats are just how that's laid out in the file.

**Comment by jangler** [comment]
mb14 is right. For example, note that even FamiTracker can't load NSF files, so I feel safe in saying that it's out of scope for Schism 😛
