### ISSUE TITLE
Fn functionality inverts globally, despite macOS System settings

### ISSUE THREAD

**Issue by Q-mii** [schismtracker/schismtracker#352]
When cross-referencing settings with DefleMask, I found that when on macOS Schism Tracker is running, fn functionality is not only inversed for the app, but for the **whole system**. **This even happens when "use F1, F2, etc. keys as function keys" is turned off.**

**Comment by mrpapersonic** [comment]
I looked into this when you posted it but I forgot to reply (its been 8 months :o ). This is because of some really ancient code in ibook-support.c that IIRC calls some kernel functions to reverse the fn keys. Not sure if it can be configured programmatically to just application-wide though...
