### ISSUE TITLE
Playback: Notes without corresponding instruments don't behave correctly

### ISSUE THREAD

**Issue by mrpapersonic** [schismtracker/schismtracker#356]
For example:
![image](https://user-images.githubusercontent.com/37962225/223571895-e858d0cb-d159-487f-b5b1-76b48f67a784.png)
In IT, the note would play on instrument 1, but in Schism nothing is played at all (presumably because it thinks I'm trying to play instrument 00??)
This last worked in 20220125.

**Comment by sagamusix** [comment]
Might have been introduced by 1b2f7d5522fcb971f134a6664182ca569f7c8008 then (potentially the change on line 2048)? The changes were mostly ported over from OpenMPT, where this is not a problem, so the patch might have been incomplete.

**Comment by sagamusix** [comment]
(BTW, what most people don't know / realize is that on row 0, you will actually hear instrument 1 being played at C-0, but usually that is just some mostly inaudible rumbling, so it's not well-known and neither OpenMPT nor Schism can currently emulate that)

**Comment by sagamusix** [comment]
Pushed a fix, including a fix for the second issue I mentioned, so it's entirely possible that other stuff is now broken. ;)
