### ISSUE TITLE
Schism hangs system when run in console/framebuffer

### ISSUE THREAD

**Issue by sparky4** [schismtracker/schismtracker#360]
running in TTY will cause the entire input system freezes and the system has to be remotely shut down.
I just simply ran schism tracker in the TTY and the input system locks up completely.

it works perfectly in X11

**Comment by mrpapersonic** [comment]
IIRC you can only get tty input in SDL2 if you install `libudev-dev` and `libevdev-dev` and build SDL2 yourself.
