### ISSUE TITLE
Channel Surround and Pan control won't work when in Instrument mode

### ISSUE THREAD

**Issue by pedrohex** [schismtracker/schismtracker#364]
Channel Surround and Pan control won't work when in Instrument mode

Not sure this is a bug but, even disabling all of the instrument options regarding the Pan and Volume, the channel simply ignores the configuration and it is using other one, not sure which.

To reproduce:
1- Create a new song.
2- Enable Instrument mode.
3- Load any instrument.
4- Try set the channel 1 (or other) with the surround option, or change the pan.
5- Play the song.

Thanks

**Comment by sagamusix** [comment]
Works as expected here in Schism Tracker 20221201. Make sure that your instruments and samples don't have Default Pan enabled, because that overrides channel panning and surround. If it still doesn't work after ensuring that, please provide a minimal test case to look at.

**Comment by pedrohex** [comment]
You're right, my bad with this. Thank you @sagamusix
