### ISSUE TITLE
Bug: playback of panning fx on no-note row does play a short note on repeated playthrough

### ISSUE THREAD

**Issue by Athaphian** [schismtracker/schismtracker#367]
I hope I describe this correctly in the title.

I was playing deadlock.xm from Elwood (download available on modarchive: https://modarchive.org/index.php?request=view_by_moduleid&query=35280) and I noticed a weird high pitched note that should not be there I believe (listening to the youtube video recorded from impulse tracker).

When you load this file and navigate to pattern 30 then hit F6, on the second playthrough, it will play a high pitch note on channel 24 position 11. There is a pan FX with an assigned instrument but no note action. I think it should not play any sound there.

Removing the instrument assignment fixes the problem.

Tested on version 20221201

**Comment by mrpapersonic** [comment]
This is a quirk in how IT works vs. FT2. When IT sees an instrument with no note value, it will automatically use the note value that was previously assigned (which is commonly used for techniques like sample-swapping), unlike FT2. Schism does its best to import files from other trackers, but it's almost guaranteed you won't get proper playback.

You can emulate this behavior in OpenMPT by converting the file type to IT and setting the compatibility toggles to the defaults.

**Comment by Athaphian** [comment]
You are right. I have just tested this on IT in DOS and it works the exact same way. So this issue can be closed. Thanks for the explanation.
