### ISSUE TITLE
segfault when browsing a large sample in the samples list

### ISSUE THREAD

**Issue by faithanalog** [schismtracker/schismtracker#376]
yeah maybe i should've trimmed it down before loading it into schism, but that's besides the point hahahaha.

I have a sample which is `13886208` samples long. you can see from this debugger screenshot that `pos` is at `13886488` which is higher than that.

https://github.com/schismtracker/schismtracker/blob/aa27baa87c7d7ceca47b1240923ff17cbbaba4c7/schism/sample-view.c#L128

![20230905_01h58m57s_grim](https://github.com/schismtracker/schismtracker/assets/1389549/1c2a5549-c84e-4e63-a0a2-c8a69679e96c)

This is a 16-bit sample, but I think there's  a similar bug in the 8-bit rendering code. It seems like this bug actually exists with samples of any length honestly; I think it'll always go out of bounds. Large samples probably just makes it more likely to end up reading memory that's not actually readable since `step` is larger.

changing this from a do-while to a while fixes the crash, though it makes 1-audiosample-long samples not render anything. Which, why would you use a 1-audiosample-long sample? But I guess I could handle that edgecase too.

i might also poke at making this not use floats because i don't think there's really a reason for this to be floating point math. but that's entirely unrelated to the actual bug and ill do that as its own thing

**Comment by mrpapersonic** [comment]
I updated the code in the newest release, can you check if this is still a problem there?

**Comment by faithanalog** [comment]
No crashes or out of bounds reads, and everything renders fine! :D

![20230908_17h55m31s_grim](https://github.com/schismtracker/schismtracker/assets/1389549/c762dcef-e4b7-46f9-b93f-15788878b242)
![20230908_17h55m26s_grim](https://github.com/schismtracker/schismtracker/assets/1389549/79aad93f-e231-46ed-b194-9b1f6963bf6b)
![20230908_17h55m20s_grim](https://github.com/schismtracker/schismtracker/assets/1389549/a7c47802-c224-49a3-9d21-e02ad131454d)
![20230908_17h55m17s_grim](https://github.com/schismtracker/schismtracker/assets/1389549/d2c8a311-7db6-4af8-b70c-577f23bce99b)
