### ISSUE TITLE
Version 20230906 fails to start on M1 MacBook Pro - libogg.

### ISSUE THREAD

**Issue by axelrafn** [schismtracker/schismtracker#378]
Thanks for the software, I regularly use it to go through my old modules and scene stuff!
But with the latest version I installed today, I can't open the software.

Error: 
Reason: tried: '/usr/local/lib/libogg.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libogg.0.dylib' (no such file), '/usr/local/lib/libogg.0.dylib' (no such file), '/usr/lib/libogg.0.dylib' (no such file, not in dyld cache)

I have this problem both with the Homebrew install as well as if I just download the zip and extract.
I did try and install libogg itself via Homebrew and it is installed in /opt/homebrew/Cellar/libogg/ but Schism won't read that directory anyway.

I would just symlink it to a place Schism is looking in, but that would just be a hack to get it running.

**Comment by mrpapersonic** [comment]
I just updated the file in the release, can you try opening that one?

**Comment by axelrafn** [comment]
Works beautifully now! Opens up, no problem =)

Thanks for the quick work =D
