### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by etaloncop** [schismtracker/schismtracker#379]
Heya, kinda new in this, 
You guys dont really have any getting started guide of some sort, do you? and if so why its not linked in the readme?
I would very much appreciate at least some basic sample library (maybe sine pulse sawtooth etc.) to get started. It is really confusing for a person that finds this repo and wants to give it a shot. As I download it and I dont have anything to get started making music, right?
a) Where do I get some basic samples
b) How do I do looping, it doesnt work for me (and the F1 help doesnt really help either)
![image](https://github.com/schismtracker/schismtracker/assets/136369289/0f176b9d-d6f1-41fe-a553-5968e5cee694)
c) Instruments, what are they? Why dont i just use samples?
d) can I add multiple samples at once? maybe whole directory?
e) can I loop just part of the pattern?
f) Are there any presets to learn from? What are the keywords i would search for? For some reason just searching with schism keyword doesnt yield many results.

**Comment by mrpapersonic** [comment]
> a) Where do I get some basic samples

You can get many samples from [existing](https://modarchive.org) [modules](http://modland.com/pub/modules/Impulsetracker/). In fact, most modules already use samples ripped from other modules. Schism directly supports importing samples from modules, too.
> b) How do I do looping, it doesnt work for me (and the F1 help doesnt really help either)

For samples to loop, you have to set the loop method to either On Forwards or On Ping Pong, and then set the loop begin and end points. The sustain loop is largely irrelevant until instrument mode is enabled.
> c) Instruments, what are they? Why dont i just use samples?

Instruments let you add volume, pan, and pitch/filter effects on a sample and are useful for e.g. chiptunes. You can also set different samples to be played at different pitches, which is useful for making nice sounding instruments like a piano.
> d) can I add multiple samples at once? maybe whole directory?

I don't think so, you have to load them all in separately.
> e) can I loop just part of the pattern?

Yep. You can set the loop start with SB0 and mark the end with SBx, with x being the amount of times you want it to loop.
> f) Are there any presets to learn from? What are the keywords i would search for? For some reason just searching with schism keyword doesnt yield many results.

Schism is a modern clone(?) of Impulse Tracker for DOS. You can find a lot of [material for using IT](https://ia802805.us.archive.org/25/items/ImpulseTrackerIIUserManual/Impulse%20Tracker%20II%20User%20Manual.pdf) that can be applied to Schism as well.

**Comment by etaloncop** [comment]
Thank you so much for such a quick reply, I cannot thank you enough, you are awesome

**Comment by etaloncop** [comment]
Damn, finally figured out how to do portamento, thats sick

**Comment by etaloncop** [comment]
OOoh this is so much fun

**Comment by etaloncop** [comment]
I need a way to apply more effects

**Comment by mrpapersonic** [comment]
You can't apply more than one effect at a time, but there are some effects that have equivalents in the volume column (portamento up, down, and tone portemento are notable examples). If you truly do need more effects, [Renoise](https://www.renoise.com) has that ability.

**Comment by faithanalog** [comment]
there's also an old manual from 2007 at https://archive.org/details/SchismTrackerUsersManual

it's quite useful and most of it still applies since schism has not had a lot of churn as a program, though it is wrong about some limitations schism doesn't have anymore / unaware of features that were added after that point. I was referencing it to learn how to set up the advanced midi configuration

I also highly recommend exploring other peoples' files to see what they do. It's great because you can hear it, play it, watch things happen, make changes and see what it did. This is what really got me into using schism and out of the "blank canvas and i dont know what anything does" pit. http://modarchive.org/ has a lot!
