### ISSUE TITLE
Program portability

### ISSUE THREAD

**Issue by quardbreak** [schismtracker/schismtracker#380]
Hello! This feels stupid to ask such question, but does Schism Tracker have an ability to store and read configuration data inside the same folder where executables located (outside AppData)?

**Comment by mrpapersonic** [comment]
No. It's hardcoded in Schism here:
https://github.com/schismtracker/schismtracker/blob/a2a4c0b8de93669fef44957c964b8625ec5a04e4/schism/config.c#L50

**Comment by quardbreak** [comment]
> No. It's hardcoded in Schism here:
> 
> https://github.com/schismtracker/schismtracker/blob/a2a4c0b8de93669fef44957c964b8625ec5a04e4/schism/config.c#L50

Oh, that's sad. I wanted to have some kind simplicity to move the program with all data, or have different versions of the program in separate folders with their own config file, but seeing how this works right now, this sounds pretty limited today...

**Comment by mrpapersonic** [comment]
It's possible to make a --portable flag at configure time that sets the .schism dir to ".". Or we could just do what OpenMPT does and search for a schismtracker.portable file in the current directory (I think thats how it does that?). I wouldn't mind accepting a PR of the former if anyone's willing to implement it :)

**Comment by quardbreak** [comment]
I think this would be awesome! Let it search for `config` file in the program folder first (as a priority target) before creating/searching file in usual paths. Sadly, I can't contribute by myself, but  I hope someone else will understand this idea well.
