### ISSUE TITLE
Cannot allocate memory when loading samples from .XI, .ITI or .PAT file

### ISSUE THREAD

**Issue by KungFuFurby** [schismtracker/schismtracker#381]
Sequel to #370. Affects the pre-compiled build and my own source build off of commit [ab2161d](https://github.com/schismtracker/schismtracker/commit/ab2161da8050b101a649dfbdc99ed8d0683ae745) on a 64-bit Intel Mac on Mac OS X 10.15.7.

I got this error in my log when trying to load from a .XI, .ITI or .PAT file (these were my test cases):
`(null): Cannot allocate memory`

I traced the fault to this call... https://github.com/schismtracker/schismtracker/blob/ab2161da8050b101a649dfbdc99ed8d0683ae745/schism/audio_loadsave.c#L1401

**Comment by mrpapersonic** [comment]
Can you try using 5afd9e2fba4287d329ef75e889bbaa0649c68bca? I edited the filesize code, but I can't test it because I don't have a working mac right now..

**Comment by KungFuFurby** [comment]
You succeeded! Not only will I close this issue as a result, but I will close #159 as well, as #159 is an ancestor to #370 and #381. Thank you very much for fixing something that had been broken for many years!
