### ISSUE TITLE
Volume envelope sustain loop "one tick off" error

### ISSUE THREAD

**Issue by digistorm79** [schismtracker/schismtracker#383]
Schism Tracker seems to play volume envelopes back differently than Impulse Tracker. It plays the sustain loop one tick shorter than Impulse Tracker.
I discovered it when listening to a module of my own that I know very well. This is the envelope that clearly sounds wrong:
![Envelope](https://github.com/schismtracker/schismtracker/assets/45852917/49879b29-0a5a-4cc6-9ba7-e8eee9830241)
This is part of the pattern data:
![pattern](https://github.com/schismtracker/schismtracker/assets/45852917/455e7ccd-4da0-4b25-8e96-7c3f7cacc865)
On Schism Tracker, it plays for 3 ticks and is silent for 3 ticks. This is maybe? as expected, but Impulse Tracker plays it for 4 ticks and is silent for 2 ticks. So on the note off command, it hangs on for 1 tick before advancing to the next envelope node. To verify this, I exported the song with Schism Tracker, I used the diskwriter from Impulse Tracker and I captured the output in DOSBox. These are the recordings:
Schism Tracker:
![Scherm­afbeelding 2023-10-16 om 08 31 29](https://github.com/schismtracker/schismtracker/assets/45852917/7f18a72f-09ac-4f54-b104-edac91a2f942)
Impulse Tracker diskwriter:
![Scherm­afbeelding 2023-10-16 om 08 31 44](https://github.com/schismtracker/schismtracker/assets/45852917/92aaa817-dcc9-48ee-82bd-374924e379bb)
Impulse Tracker non-MMX output on SB16:
![Scherm­afbeelding 2023-10-16 om 08 31 48](https://github.com/schismtracker/schismtracker/assets/45852917/eb2402c3-0b86-4e32-a752-cbdec1d734c8)

At 125 bpm, on tick is very conveniently 20 ms, so it is quite easy to see what's going on. The diskwriter (and the MMX or filtered mixer) use volume ramps (that by the way are quite different from the volume ramps of Schism Tracker) but you can clearly see that Schism Tracker plays the sample for 3 ticks while Impulse Tracker plays it for 4 ticks. And when listening, this clearly sounds off because the note are now too short, shorter then I intended when writing this song. It is so obvious that I am pretty sure Impulse Tracker has always behaved in this way or I would have changed the way the song is setup.
So… this seems like a bug to me. I don't know what the documentation says about this, but this is actual captured behavior.
I will attach a stripped down version of the song in case you want to use it for debugging.
[ANSWER-D.IT.zip](https://github.com/schismtracker/schismtracker/files/12912985/ANSWER-D.IT.zip)

**Comment by mrpapersonic** [comment]
OpenMPT has a test case for this bug: [EnvOffLength.it](https://wiki.openmpt.org/Development:_Test_Cases/IT#EnvOffLength.it). I'll look into this when I get the chance.

**Comment by mrpapersonic** [comment]
Fixed with bc81f605d927ca931a886417641da29fc89283b8.
