### ISSUE TITLE
Caps lock keyjazz not working on mac os

### ISSUE THREAD

**Issue by abandpass** [schismtracker/schismtracker#385]
In F2 screen, keyjazz is not working under mac os.
Holding caps lock has no effect in pattern edit screen.  Notes get written to pattern as usual even if holding caps lock key.
Tested on mac os 13.6 and mac os 14.

Any help welcome.  Even a starting point to peek at the code.  Thanks!

**Comment by mrpapersonic** [comment]
I can reproduce this but I have no hints as to why it doesn't work. Here's the part of the code that says whether it should write notes to the pattern:
https://github.com/schismtracker/schismtracker/blob/49cab29d49644b2c8bd2ce60f3fe0946dd473703/schism/page_patedit.c#L3198
And here's where CAPS_PRESSED gets defined:
https://github.com/schismtracker/schismtracker/blob/49cab29d49644b2c8bd2ce60f3fe0946dd473703/schism/main.c#L683

**Comment by abandpass** [comment]
Thanks mrpapersonic for the super fast reply!

Disclaimer : i know just enough to be dangerous around C code.

I think the bug is not in schism tracker's code.
I did some tests with SDL2.28.4.  test/checkkeys reports both key press and release when pressing caps lock.  I think this explains the behavior in schism tracker as it is consistent with what SDL2 reports.
It was fixed in the past in SDL2: https://github.com/libsdl-org/SDL/issues/1123

**Comment by mrpapersonic** [comment]
Looks like this really isn't "our" problem, but I'll keep the issue open until the SDL devs find out a way to solve this (if ever) :/

**Comment by abandpass** [comment]
With your help, i managed to write a small workaround.  With this quick fix, on Mac OS keyjazz is on when caps lock is on.
Not perfect but better than no keyjazz.  I don't think it breaks anything so far with my limited testing.

```diff
diff --git a/schism/page_patedit.c b/schism/page_patedit.c
index ac3dc1d1..5fbe14dc 100644
--- a/schism/page_patedit.c
+++ b/schism/page_patedit.c
@@ -3194,8 +3194,11 @@ static int pattern_editor_insert(struct key_event *k)
 		if (k->is_repeat && !keyjazz_repeat)
 			return 1;
 
-
+		#ifdef MACOSX
+		int writenote = !(SDL_GetModState() & KMOD_CAPS);
+		#else
 		int writenote = !(status.flags & CAPS_PRESSED);
+		#endif
 		if (writenote && !patedit_record_note(cur_note, current_channel, current_row, n, 1)) {
 			// there was a template error, don't advance the cursor and so on
 			writenote = 0;

**Comment by esaruoho** [comment]
@abandpass can ya make a PR so it doesnt just stay as a comment on an issue?

**Comment by abandpass** [comment]
@esaruoho Yes i will do it soon.  It might take a few days as i never did this before.

**Comment by abandpass** [comment]
Got around to creating my first PR : https://github.com/schismtracker/schismtracker/pull/388
Thanks @esaruoho for asking :)

**Comment by mrpapersonic** [comment]
Does the code I added actually work for anyone else? It works on my powerbook running leopard but not under a hackintosh running catalina.

**Comment by vcaputo** [comment]
> Does the code I added actually work for anyone else? It works on my powerbook running leopard but not under a hackintosh running catalina.

No mac here otherwise I'd give it a try...

**Comment by abandpass** [comment]
It works fine, been using it on my M1 and M2 macs running Sequoia 15.0.1.  Thanks for this!

**Comment by mrpapersonic** [comment]
nice! I guess mine just doesn't work with it for some reason. Thanks!
