### ISSUE TITLE
No --version on Windows

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#39]
see https://github.com/schismtracker/schismtracker/pull/38#issuecomment-242561539

**Comment by jangler** [comment]
JosepMA posted in #38:

> The --version is not working on any build I have, and that includes one that I made out from 20120105 sources back then: http://psycle.free.fr/josepma/SchismTracker-20120105-win32-mingw-3.4.2.zip
> In fact, nothing that is written to the console ( printf/ puts ) seems to be printed.
> 
> Edit: It seems it is some SDL redirection or similar. I found the text that was supposed to be written, in a file named stdout.txt in the same dir where i am executing it.
> 
> http://sdl.beuc.net/sdl.wiki/FAQ_Console

**Comment by sagamusix** [comment]
Windows GUI applications cannot simply write to the console even if they are run from console. They would have to open their own console window. The only way to "fix" this would be to compile the program using the CONSOLE subsystem, but that would always open an ugly console window next to the GUI window, so it's not a nice solution. This is not an SDL limitation. Other applications fix this by e.g. printing the console output to a message box.

**Comment by jangler** [comment]
Case closed! Thanks, Saga.

**Comment by asbjornu** [comment]
@sagamusix Ah, so this explains why most Windows applications suck so utterly in their integration (or lack thereof) with the command line. Thanks!

**Comment by asbjornu** [comment]
However, that still leaves the case unclosed on how we're supposed to do any form of testing of the compiled binary on Windows. Ideas?

**Comment by sagamusix** [comment]
I dunno, why would you require the console for testing? I suppose we're doing things differently for OpenMPT/libopenmpt, but not having the console available doesn't stop us from unit testing. :)

**Comment by jangler** [comment]
If `make` succeeds on AppVeyor but we get an executable that's so broken that it can't parse command-line flags, then someone has most likely pushed or PR'd something that they didn't even bother to build and run. I like sanity checks, but I don't feel that that one is necessary.

Like Saga suggests, unit testing would be much more useful, but the Schism codebase would probably require a lot of refactoring to afford that.

**Comment by asbjornu** [comment]
@sagamusix I agree unit testing would be the absolutely preferred thing to do here, but as @jangler  writes, that would require some major refactoring of the Schism Tracker code base.

I just wanted to add a sort of [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) test, so we could get maximum amount of testing for minimum amount of effort, which `--version` does well enough on (imho) sensible operating systems, but which is impossible to do on Windows. Well, well. :smile:

**Comment by ghost** [comment]
Can you run --version and then cat stdout.txt? Isn't that the point of those files?

**Comment by sagamusix** [comment]
Yeah, that's what I would have thought as well. And even if that doesn't work, add a simple command line switch which e.g. writes to a file on all platforms, or exists with a specific exit code, or something like that.

**Comment by asbjornu** [comment]
@mb14, @sagamusix: I didn't even know `stdout.txt` existed. But now that I do, I've done just what you suggest in #44. :smile:

**Comment by sagamusix** [comment]
Ah, it was mentioned in the link from @jangler's first post, so I assumed you saw that, hence the confusion. :)
