### ISSUE TITLE
I noticed that a feature from the original Impulse Tracker is missing (2 nodes on the same tick)

### ISSUE THREAD

**Issue by Hundredlegger** [schismtracker/schismtracker#390]
As the title says, I noticed that original Impulse Tracker songs made by the OG program have songs where the instruments can have 2 nodes on the same tick in their envelope (as long as it has a different value), but Schism Tracker doesn't allow this for some reason no matter what I tried.

I'm not sure if this is a bug or oversight, but I'm going to submit it as an issue here.

**Comment by vcaputo** [comment]
Thanks for the report

**Comment by sagamusix** [comment]
No, that is definitely not possible in Impulse Tracker. In fact, Impulse Tracker behaves very strangely when two nodes share the same tick (the envelope is paused and the second node is processed one tick later). You will indeed find some IT files in the wild where two nodes share a tick, but those were made with earlier versions of ModPlug Tracker. The way ModPlug Tracker worked was that the timing would be as expected (i.e. not delayed by one tick), but the effect of the second node would only be heard on the next tick. Schism Tracker's player is based on the original ModPlug engine, so when encountering a ModPlug-made module that makes use of this quirk, it will sound as intended.
