### ISSUE TITLE
Possible to fix sdl on console?

### ISSUE THREAD

**Issue by guaka** [schismtracker/schismtracker#393]
When launching over ssh schism looks like this:

<img width="1161" alt="image" src="https://github.com/schismtracker/schismtracker/assets/54728/7f03dff7-effb-4417-b327-a554f3c7e139">

<img width="772" alt="image" src="https://github.com/schismtracker/schismtracker/assets/54728/df4ff1dd-d1ba-42f0-8e0e-c03f5c11abe5">

On a first glance it seems interesting to look at 
https://github.com/schismtracker/schismtracker/blob/1dabb2bb38754547be0e1533e01ff2a585275a69/schism/draw-char.c#L555

Obviously rewriting everything to have ncurses in addition to SDL would be the clean fix, but it would be a long arduous process. If there is a quick win here that makes SDL work properly on the console that seems much nicer.

Anyone who's more into this codebase with thoughts on this?

**Comment by mrpapersonic** [comment]
Schism emulates a VGA screen and prints to it using a custom built in font, which explains why everything looks so garbled over ssh. It's trying to display a 640x400 image using just ASCII chars.

VNC or something similar would be a better solution for running Schism remotely.
