### ISSUE TITLE
Strange bug: one note (or more?) doesn't hold the sustain loop on the envelope

### ISSUE THREAD

**Issue by digistorm79** [schismtracker/schismtracker#395]
I wanted to write an old tune of mine to wav to use it in a video, and something just didn't sound right. After spending way too much time, I discovered that one note (and maybe more) just let the "playhead" (the moving line) shoot through the sustain loop of the envelope, as if it was played very short. Most notes behave as they should, but this one doesn't. I can't figure it out, I spend a lot of time checking and trouble shooting, but when I found out that Impulse Tracker does play the song correct, and also this note with the sustain loop, I figured it has to be a bug in Schism Tracker. But I don't have a clue what is going wrong.
I will attach the tune (it is very small, was used in a 64k intro) so maybe someone with debugging tools can find out what is happening.

For debugging and comparing purposes, follow these steps:

- Open HELLO.IT ([HELLO.IT.zip](https://github.com/schismtracker/schismtracker/files/13745940/HELLO.IT.zip))
- Go to the pattern editor with F2
- Go to pattern 7
- Play the pattern with F6
- Watch note A-5 on channel 05 and row 31
- It is the same as all other notes, like its neighbours on channels 03 and 04, but unlike those, it does not do the sustain loop on the envelope.
- Go to the instruments with F4 while the pattern is still playing and go to instrument 06
- Open the volume tab and observe how all notes wait on the sustain loop of the instrument, except that one note.

Do all of these things in Impulse Tracker and you will see and hear the difference.

If there are still questions, please feel free to ask them.

**Comment by mrpapersonic** [comment]
This plays fine in Schism 20230906, so it's caused by the lot of playback changes I made between that and 20231029. I'll see if I can pinpoint which commit caused it soon.

**Comment by mrpapersonic** [comment]
I've found the issue and created a test case for it:
[InstrAfterNoteOffAndNoVolume.it.zip](https://github.com/schismtracker/schismtracker/files/14087813/InstrAfterNoteOffAndNoVolume.it.zip)

Something in the playback code is keeping instrument envelopes from retriggering after a note off and the instrument volume is zero.

It looks like this issue is linked to #398.
