### ISSUE TITLE
Regression: Sample default volume is indexed with instrument number instead of sample number.

### ISSUE THREAD

**Issue by digistorm79** [schismtracker/schismtracker#399]
It seems that the latest release version with bug fixes to the handling of envelopes has a regression.
Samples can have a default volume, that is used if there is no explicit value in the volume column. It seems that in the latest version, it uses the instrument number to lookup this value in the sample properties and does **not** lookup the sample number that should be playing. This messes up songs where the instrument number and sample number are not the same (they can be arbitrarily mapped).

I created a test case song that has 16 samples with increasing default volume (1 to 16). I then reversed the order of the **instruments** so that instrument 1 uses sample 16, instrument 2 uses sample 15 and so on.

In Impulse Tracker this song plays (repeatedly) the instrument in decreasing order (from 16 to 1) and therefore the samples in **increasing** order (from 1 to 16). Because it takes the default volume of the **samples** into account, and the samples are played in increased order, the resulting playback volume also increases from 1 to 16. This can be observed in the playback screen (F5) when you look at the debug window (one time PageUp when you are at the default screen with the volume bars). Column Smp shows the sample played at the moment (increasing from 1 to 16) and the Vl column shows the applied volume value, taken from the default volume, also increasing from 1 to 16.

In the latest release of Schism Tracker, if you observe the same screen, you will see the Smp value increase from 1 to 16, but the Vl value (which is the same as the sample number) is **decreasing** from 16 to 1, following the **instrument** number and not the sample number.

[BUG.IT.zip](https://github.com/schismtracker/schismtracker/files/14220617/BUG.IT.zip)

**Comment by mrpapersonic** [comment]
Fixed with 70be34f8195577f473c880e906a934403b708b60.
