### ISSUE TITLE
GitHub import from hg repo broken

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#4]
A bunch of commits that are fine in the [hg repo](https://bitbucket.org/Storlek/schismtracker) are completely broken after being imported from GitHub. The most recent example of this is a39e55e2fef31d748282890a3e068f4253c91fdc ("rm unused param"). It would be _really nice_ to be able to `git blame` and such properly, so I'm going to try other means of converting the repo over to Git.

This inevitably means some `git push -f`, but I'd rather overwrite the history than have the history be all but useless.

**Comment by ghost** [comment]
This sucks! Good luck.

**Comment by jangler** [comment]
It's been done. Thank you, http://arr.gr/blog/2011/10/bitbucket-converting-hg-repositories-to-git/.
