### ISSUE TITLE
Playback as in the original Impulse Tracker in Instruments tab

### ISSUE THREAD

**Issue by MorthimerMcMare** [schismtracker/schismtracker#400]
Not an issue, a question.

In original Impulse Tracker 2.14, in Instruments tab, you can play multiple sounds at once when holding several PC keyboard keys; each note stops when corresponding key is released. Extremely useful in chords.

In Schism Tracker,  the note continues playing until the next key is pressed (or, when `Alt + N`/"Multisample playback" is enabled, until `F8` not hit).

So the question is: how to return the behaviour from IT214? Tested with "Schism Tracker built Jan 31 2024 12:56:03" and "Schism Tracker 20240129".

**Comment by mrpapersonic** [comment]
There's no real way to return this behavior in the current codebase. It doesn't sound very difficult to implement though, it could be as simple as an array of `SDL_Keysym`s.

Priority for me right now is on playback bugs and getting #343 finally merged into master. Once those are dealt with I'll see if I can come up with something for this.

**Comment by MorthimerMcMare** [comment]
Will wait, thank you!

It's a little unfortunate that I don't know SDL. Will promise nothing, but how do you feel about code written on the library by a newbie?

**Comment by mrpapersonic** [comment]
Any patch you can give is appreciated! It's okay if you're starting out, consider it a learning experience :) we all start somewhere.

**Comment by a11cf0** [comment]
I've just tried setting up a channel counter  incrementing/decrementing it on each keydown/keyup and then passing it to song_keydown. This seems to work like in IT at first glance, but I'm not entirely sure.

**Comment by mrpapersonic** [comment]
Can you send the changes as a patch or a PR?

**Comment by a11cf0** [comment]
My first counter-based attempt was totally wrong. Let's have another try at this.

**Comment by mrpapersonic** [comment]
This should now be implemented proper with 85bad05cf099fb78039a1d80a875a04224ee73fa.

**Comment by a11cf0** [comment]
The latest implementation significantly changes note playback behavior  in the pattern editor when inserting notes while a song is playing, because it uses the new keyjazz offset even when a channel number or KEYJAZZ_CHAN_CURRENT is requested. Impulse Tracker seems to use the real current channel everywhere, except in the instrument editor.

**Comment by mrpapersonic** [comment]
> Impulse Tracker seems to use the real current channel everywhere, except in the instrument editor.

After screwing around with Impulse Tracker more, yeah that's right. Fixed with e8e630320e052bd281afa845032a07d2cf20d6f4
