### ISSUE TITLE
Regression: Instrument volume shenanigans

### ISSUE THREAD

**Issue by zavok** [schismtracker/schismtracker#402]
After update to 20240129 (tried in today's git version as well) playing instrument on the same channel now resets volume of previous instrument to default value. You usually need to set "New Note Action" to continue/off/fade in the instrument settings to notice this.
Because this only happens when instrument's sample is set to 01, I think this bug might be related to [issue 399](https://github.com/schismtracker/schismtracker/issues/399)

You can probably understand it better by looking at attached example:
[volbug.it.gz](https://github.com/schismtracker/schismtracker/files/14285027/volbug.it.gz)
See how there's still sound on instrument 02 even though all note volumes  are set to 00.

**Comment by mrpapersonic** [comment]
Fixed with 70be34f8195577f473c880e906a934403b708b60

**Comment by zavok** [comment]
Thanks for your hard work!
