### ISSUE TITLE
[wiki] Link to Impulse Tracker in the wiki is broken

### ISSUE THREAD

**Issue by DarckCrystale** [schismtracker/schismtracker#403]
In [Links](https://github.com/schismtracker/schismtracker/wiki/Links), the Impulse Tracker link redirects to the Internode support page explaining their hosting service is shut down.

You may want to update it to the [Web Archive last version](https://web.archive.org/web/20230717162958/http://www.users.on.net/~jtlim/ImpulseTracker), to find if it's hosted elsewhere or to find someone to host it back 🙂 

*note: other links maybe broken, I didn't checked them*

**Comment by mrpapersonic** [comment]
The wiki is globally editable, feel free to edit it yourself there.

**Comment by DarckCrystale** [comment]
Done with the web archive link
