### ISSUE TITLE
schismtracker gets stuck at the 1st row of every module/midi

### ISSUE THREAD

**Issue by ruby-R53** [schismtracker/schismtracker#405]
i got the 20240129 build on gentoo and when i tried to play some modules, schismtracker initially would play them correctly except for .it, where for some reason the samples seem to get retriggered and the timing is off; and .mid, where although schismtracker was playing it, i got no sound output whatsoever

i then tried to compile from github thinking there was something wrong with how it was packaged in gentoo, but i got the same issue, and now it somehow can't play any modules at all anymore:

on some modules, it's able to play the first row but then it just stops after that, and on the rest of my modules it just keeps playing the 1st row over and over again really fast, and i have to press F8 a few times to make it stop

i'm not sure if that's a problem with how i built schismtracker or if it's actually related to how i installed SDL2, it was working fine before that build, maybe now it requires another SDL2 feature that i didn't enable?

**Comment by mrpapersonic** [comment]
I think this is something external to schism. Are you using pulseaudio, pipewire, etc. or just ALSA?

**Comment by ruby-R53** [comment]
it's running pulseaudio over pipewire, didn't see a `configure` option to make it use something else

**Comment by mrpapersonic** [comment]
that's weird, I'm also using pulseaudio on pipewire and it plays just fine...
![image](https://github.com/schismtracker/schismtracker/assets/37962225/42066a06-7cdc-4997-8316-c7815ee783ad)
what version of SDL2 are you using?

**Comment by ruby-R53** [comment]
i'm running SDL 2.28.5, i'm gonna try building that latest version now

**Comment by ruby-R53** [comment]
SOLVED: it was an issue with my MIDI output options this whole time!
