### ISSUE TITLE
Issue with SDL 2.30 on Windows

### ISSUE THREAD

**Issue by JosepMaJAZ** [schismtracker/schismtracker#406]
Warning:

Schismtracker is affected by this issue on windows:

https://github.com/libsdl-org/SDL/issues/9177

I've been trying to find out what happened, until I started to check why the older build worked and the current one not.

If anyone encounters the problem, switch back the SDL2.dll to 2.28 until they release 2.30.1 on msys2.

**Comment by mrpapersonic** [comment]
You can just use the [official build of SDL2](https://github.com/libsdl-org/SDL/releases/tag/release-2.30.1), there's no notable differences between their builds and msys2's.

**Comment by mrpapersonic** [comment]
SDL 2.30.1 is now available on msys2.
