### ISSUE TITLE
Midi note-on and note-off have switched places

### ISSUE THREAD

**Issue by devloop0123** [schismtracker/schismtracker#408]
When using midi out, notes trigger a note-off first and then a note-on (or simultaneously, but note-off is apparently processed first. In the pianoteq midi snooper they appear on the same midi tick), and these messages are sent only when the *next* note is due. 
So in pattern with C5---C4-------C6---
it plays instead.... __----C5-------C4----
    
This happens with the downloaded 20240308 and also the selfcompiled master 20240311. Version 20230907 works correctly, and is the last one to do so.

Here I play a pattern with first note 60 and later note 48:

Aseqdump output for 20230907, all is well:
 14:3   Start
 14:3   Reset
 14:3   Control change          0, controller 0, value 127
 14:3   Note on                 0, note 60, velocity 80
 14:3   Note off                0, note 60
 14:3   Note on                 0, note 48, velocity 60
 14:3   Note off                0, note 48
 14:3   Note off                0, note 48
 14:3   Control change          0, controller 120, value 0
 14:3   Control change          0, controller 121, value 0
 14:3   Control change          0, controller 123, value 0

Aseqdump output for 20240308:
 14:3   Start
 14:3   Reset
 14:3   Control change          0, controller 0, value 127
 14:3   Reset
 14:3   Program change          0, program 127            
 14:3   Note off                0, note 0                         
 14:3   Note off                0, note 60 
 14:3   Note on                0, note 60, velocity 80    
 14:3   Note off                0, note 48
 14:3   Note off                0, note 48
 14:3   Control change          0, controller 120, value 0
 14:3   Control change          0, controller 121, value 0
 14:3   Control change          0, controller 123, value 0

Both play the same pattern. One additional difference is that with the newer Schism Tracker version, in the instrument's note list, I have to assign a sample number to the notes, otherwise there's no midi output at all. 

This is on Linux, btw. Alsa midi.

**Comment by mrpapersonic** [comment]
I don't know anything about midi in the codebase so I can't really look into this right now. Once I get a better grasp on how Schism's midi stuff work I'll see if i can replicate it.

**Comment by kitchen-ace** [comment]
I believe 671c4b0 is the commit that broke midi playback; I am experiencing the same issues as well with newer versions. Using git to reset to the commit before that one makes things work OK.

**Comment by mrpapersonic** [comment]
wow thanks, I'll look into this tonight!

**Comment by devloop0123** [comment]
Alas, issue is not completely fixed yet. The timing is now right, but now note off events are sent instead of note on events.

Edit: after manually assigning a sample to every note on the instrument page, then playing a pattern, only the very first note-on event is an erroneous note off event instead. 

Subsequent notes are played correctly, apart from the fact that their velocity is that of the *previous* note. Maybe that's why the first note on is sent as a note off: note on velocity 0 is usually interpreted as note-off.
