### ISSUE TITLE
note off/fade panning bug

### ISSUE THREAD

**Issue by gretzky2** [schismtracker/schismtracker#417]
instrument: set NNA to note-off + set pan to 0 (left)
channel: set initial pan to 64 (right)

module.it plays correctly in openmpt123 not schismtracker

[module.it.zip](https://github.com/schismtracker/schismtracker/files/15065572/module.it.zip)

**Comment by sagamusix** [comment]
While the issue was invisible to us, I created #418 as a replacement, which just got fixed.
