### ISSUE TITLE
Create Xcode project

### ISSUE THREAD

**Issue by asbjornu** [schismtracker/schismtracker#42]
In the build instructions for OS X, there is mention of an `Schism Tracker.app` bundle that somehow got to exist, but which source seems to have been missing for a while. What I believe we need to get a fully automated OS X build of Schism Tracker is a fully working `.xcodeproject` that outputs an `Schism Tracker.app`.

The `AUTHORS` file mentions a mister Tim Douglas (is @timdouglas the one?) that "maintained the original Mac OS X packages", but the commit history has no traces of his name and I can't find the source code he maintained anywhere.

I believe the easiest way to achieve success here is to resurface the Xcode project file and related source code that was used to build the `Schism Tracker.app` bundle to begin with, but if that's impossible, we need to create a new Xcode project that successfully builds and packages everything up into an `.app` bundle.

**Comment by timdouglas** [comment]
Nothing to do with me, sorry...

**Comment by asbjornu** [comment]
@timdouglas According to [How many of me](http://howmanyofme.com/search/), there's only 430 people named Tim Douglas or Timothy Douglas in USA, so it was worth a shot. :smile: Well, well.

**Comment by jangler** [comment]
It's actually pretty easy to put together a `.app` bundle without Xcode. I think we can pull all the files except the executable itself from the previous OS X release.

**Comment by asbjornu** [comment]
@jangler But if we ever want to change the properties of the `.app` bundle, wouldn't it be great to have an Xcode project? Replacing stuff inside an old bundle to create a new bundle feels so ... icky. :smile:

**Comment by asbjornu** [comment]
Relatedly, I just found [this `create-darwin-app.sh` script](https://github.com/davvid/schismtracker-mirror/blob/laptop-octave/scripts/create-darwin-app.sh) in @davvid's fork. Could provide useful if we chose to go the "replace stuff in old `.app` bundle" route.

**Comment by jangler** [comment]
Closing this since it's inherent in #40.

**Comment by asbjornu** [comment]
Ok.
