### ISSUE TITLE
Possible stability issues with 20240426 release?

### ISSUE THREAD

**Issue by skope2v** [schismtracker/schismtracker#428]
Hello. First thank you for working on my fav tracker. (: 

I've encountered some weirdness with the latest release (20240426) on both Windows (provided 64-bit binary package from here) and Linux (built from source, no modifications just straight up ./configure & make & sudo make install on Debian stable like I always do, because the package in Debian stable repo has cobwebs on it).

On Windows when I'm on the sample screen, pressing enter to load a sample will crash Schism completely. A few times I've pressed enter on a sample slot and got as far as to the file selector screen it will crash in the same way by entering a directory.

Under Linux I'm having issues with keyboard input which seems to stop working after some time has passed (unsure how long but I'm guesstimating 5-15 minutes of use). I'm not sure if it's something specific I do that triggers it. It affects naming a song in the song info screen, naming a file in the save module screen, making entries in the orderlist, trying to rename a sample. However editing patterns will oddly enough still work. I've noticed that unfocusing Schism and going back to it will return keyboard input for a while but it will loose it again eventually.

I haven't encountered any of these issues on prior releases and I have for now reverted to using 20240409 on both machines which works as expected for me. (:

**Comment by mrpapersonic** [comment]
> On Windows when I'm on the sample screen, pressing enter to load a sample will crash Schism completely. A few times I've pressed enter on a sample slot and got as far as to the file selector screen it will crash in the same way by entering a directory.

This is sort of to be expected as I had to replace a lot of the filesystem code to support NT unicode on windows, and since I don't really use windows regularly a lot of these passed by me. I'll see if I can replicate it.

> Under Linux I'm having issues with keyboard input which seems to stop working after some time has passed (unsure how long but I'm guesstimating 5-15 minutes of use). I'm not sure if it's something specific I do that triggers it. It affects naming a song in the song info screen, naming a file in the save module screen, making entries in the orderlist, trying to rename a sample. However editing patterns will oddly enough still work. I've noticed that unfocusing Schism and going back to it will return keyboard input for a while but it will loose it again eventually.

This is really weird, I don't remember editing anything around those files. It looks like it only affects keyboard input through `SDL_TEXTINPUT` since all of those input fields use it.

Sidenote: are you using X11 or wayland? that might help narrow things down a bit.

**Comment by skope2v** [comment]
> Sidenote: are you using X11 or wayland? that might help narrow things down a bit.

I'm using Cinnamon on X11. (:

**Comment by mrpapersonic** [comment]
Loading in the sample library was fixed with ddcea2702c7717cb9110d09bcb8331e069e18672

**Comment by skope2v** [comment]
Small update regarding the text input thing, I had this happen this morning on my Windows 10 desktop PC and on version 20240409. I was editing the song name and could backspace chars out but not enter new ones in. Toggling between windowed and fullscreen alleviated this. Could this be an SDL issue perhaps?

**Comment by mrpapersonic** [comment]
It could be, but I think a thing I did in the instrument page list code could be eating all of the events; I'll debug this when I get the chance.

**Comment by mrpapersonic** [comment]
> Under Linux I'm having issues with keyboard input which seems to stop working after some time has passed (unsure how long but I'm guesstimating 5-15 minutes of use). I'm not sure if it's something specific I do that triggers it. It affects naming a song in the song info screen, naming a file in the save module screen, making entries in the orderlist, trying to rename a sample. However editing patterns will oddly enough still work. I've noticed that unfocusing Schism and going back to it will return keyboard input for a while but it will loose it again eventually.

Just replicated this, can't tell what's causing it though. Taking Schism in and out of fullscreen (on my window manager effectively the same as focusing+unfocusing) does fix it.

**Comment by mrpapersonic** [comment]
well, I can't get it to trigger consistently, and when I do I don't get any debug output from Schism (regarding string conversion) meaning that
 a). the events are getting sent but not handled by Schism
 b). there is no text input event getting sent from SDL (unlikely)
 c). this was caused by the old (very hacky) text input code

outside of this issue, there ought to be a fallback for applying text anyway.

**Comment by mrpapersonic** [comment]
fwiw I haven't been able to cause this since my last post, so if this problem still exists I won't be of any help unfortunately :(

**Comment by mrpapersonic** [comment]
Does this issue still exist? I've been able to make tunes without any problems over here.

**Comment by skope2v** [comment]
As a matter of fact this seems to have stopped. I haven't had this happen again since summer probably.

**Comment by mrpapersonic** [comment]
Awesome :D
