### ISSUE TITLE
Collapse stereo sample to mono in sample list

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#43]

**Comment by sagamusix** [comment]
Just to give some ideas, there should probably be an option to mix both channels to mono, and one to split them into two sample slots. The latter can be very useful e.g. when targetting 100% Impulse Tracker compatibility.

**Comment by HybridDog** [comment]
You could also convert a stereo sample to three mono samples with different volume level.
In audacity you can do this easily:
duplicate the track
convert one to mono
duplicate the mono track
invert one mono track
combine the stereo track with the inverted mono track

**Comment by jangler** [comment]
> convert one to mono

That'd be what we're doing here, haha. Not inverting anything or adjusting volumes; there are already commands for those things.

**Comment by sagamusix** [comment]
Besides - why three samples? The most common and useful encodings for stereo are Left/Right and Mid/Side - but the latter is not particularly useful in Schism Tracker.

**Comment by HybridDog** [comment]
If you split the stereo track to three mono tracks (left, mid(both) and right), you can then move the volume difference to the sample settings, which makes it possible to easily adjust the stereo strength there.
But if you split it to two samples (left and right), you can't simply change the stereo strength because mid is part in both, so if you e.g. make left louder, mid is strengthened on the left side too.

**Comment by jangler** [comment]
Having the option to take just right channel, just left channel, or mix would be my plan here. But your suggestion would give mix, inverted mix, and side, yes?

**Comment by jangler** [comment]
Downmix implemented; would be nice to be able to just take left or right channel as Saga says, using a dialog similar to the one used when loading a stereo sample.

**Comment by jangler** [comment]
Auto-splitting into two sample slots would be a pain, though. It's pretty fast to just export the sample, load it twice (once left channel, once right channel), and then delete the export. I'll just merge and close this issue for now; this feature was for me anyway ;)
