### ISSUE TITLE
ST3 command SAx (SB Stereo Control) not imported correctly

### ISSUE THREAD

**Issue by 0xHexaDecimator** [schismtracker/schismtracker#430]
Impulse Tracker (and openMPT) ignores the panning effect S8x in Scream Tracker 3 modules saved with Sound Blaster drivers; the ST3 SB drivers did not support panning effects. (IT also translates the effect to SA0)
Schism appears to play the S8x effect in ST3 modules regardless of what ST3 drivers the module was saved with.
https://github.com/schismtracker/schismtracker/assets/151794548/68839eaf-de2b-4e94-9afd-a5d2ce51b679
[strshine.zip](https://github.com/schismtracker/schismtracker/files/15195446/strshine.zip)

**Comment by sagamusix** [comment]
There's a few incorrect things here.

- Impulse Tracker never ignores S8x effects in S3M. Neither does OpenMPT. There are many modules written with SB drivers but were intended to be listened with external players which did support panning regardless of the soundcard, so simply ignoring panning commands in this case would be a bad idea.
- "Starshine" does not contain any S8x effects, it contains SAx effects (so IT does not translation, it simply does not know what to do with this effect), which is ST3's super-weird "stereo control" effect. SAx directly interferes with the SB mixing code and does not allow free-range panning. This effect was poorly understood for the longest time (you cannot possibly understand it without reading ST3 source), so most players that claimed to support it imported it as a variant of command S8x, probably based on a few (incomplete) observations in other modules. But that's not quite close to the true functionality of that command. OpenMPT implements an approximation of the SAx command. I'll see if I can port it over to Schism Tracker.

**Comment by 0xHexaDecimator** [comment]
ah
> *  OpenMPT implements an approximation of the SAx command. 

openMPT shows them as S8x, so I assumed it was an incorrect interpretation of the effect.
![image](https://github.com/schismtracker/schismtracker/assets/151794548/96fe3f44-e6de-4c1f-ae0b-800ad47eb7fa)

**Comment by sagamusix** [comment]
Yeah, OpenMPT needs to convert the command internally to something more sensible - the same way as Schism Tracker does now. For these sort of things, it's always important to check how they look in the original tracker, because such conversions are not uncommon when importing files from non-native formats (which is why you saw three completely different things in IT, Schism and OpenMPT).
