### ISSUE TITLE
starting Schism freezes sound servers

### ISSUE THREAD

**Issue by devloop0123** [schismtracker/schismtracker#431]
(On Linux) Schism version 20240503 force-starts the jack server with 
jackd -T -ndefault -T -d alsa
which freezes the active pulseaudio server until I kill said process. If jack's already running then all is fine. 

Linux Mint 21.3

**Comment by devloop0123** [comment]
Found the probable cause: 

Even though jackdbus may be active, and pulseaudio's module-jackdbus-detect is loaded, starting jackd from the terminal does not automatically lead to the creation of pulseaudio-jack-sink, which freezes pulseaudio apps, including Schism itself (because that leaves them without a sink?).

I never encountered this problem before since I always start Jack, when needed, with Qjackctl, and a pulseaudio-jack-sink/source  always magically appears.

**Comment by mrpapersonic** [comment]
> (On Linux) Schism version 20240503 force-starts the jack server with 
> 
> jackd -T -ndefault -T -d alsa
> 
> which freezes the active pulseaudio server until I kill said process. If jack's already running then all is fine. 
> 
> 
> 
> Linux Mint 21.3

This was the default behavior in `jack_client_open`, so I thought it'd be fine, but \<rant\>the stupid amalgamation of different sound servers on Linux proves me wrong again\</rant\> :)

what would be the preferred default behavior be, even? Is this even a fault of Schism? This sounds like more of a pulseaudio-jack issue to me than anything.

**Comment by devloop0123** [comment]
> what would be the preferred default behavior be, even? Is this even a fault of Schism? This sounds like more of a pulseaudio-jack issue to me than anything.

Hard to say. It's a bit of a mess indeed. I personally prefer no application to autostart jack at all. If I'd want to use it, it would already be active.

**Comment by devloop0123** [comment]
Turns out, when using jack in conjuction with pulseaudio, starting jack with the jackd command is not the proper way at all. I need to run:

jack_control start

which activates jackdbus, activates jack with the proper settings as defined in ~/.config/jack/conf.xml, and now pulseaudio does create the proper jack source and jack sink.

**Comment by devloop0123** [comment]
Adding JackNoStartServer in line 335 of midi-jack.c solves the problem:

	client = JACK_jack_client_open(PORT_NAME, JackNoStartServer, JackNullOption, NULL);

**Comment by mrpapersonic** [comment]
`JackNoStartServer` should probably be the default. [RtMidi does that as well](https://github.com/thestk/rtmidi/blob/53809fc1869a9789c4631a11081c1840b6db1527/RtMidi.cpp#L4115), so I guess it might be more useful to connect when polling midi ports anyway.
