### ISSUE TITLE
Regression: F4 silences all instruments

### ISSUE THREAD

**Issue by jengelh** [schismtracker/schismtracker#437]
Last known good version: 20240503
First known bad version: 20240515
System: Linux 6.8 amd64 on openSUSE Tumbleweed

Modules affected: [house9.mod](https://modarchive.org/index.php?request=view_by_moduleid&query=46518), [nitestrm.mtm](http://www.mediafire.com/file/29b0x7s973zdxmv/Lee%20Jackson%20-%20Apogee%20era.zip), 
Modules not affected: [external.xm](https://modarchive.org/index.php?request=view_by_moduleid&query=66187)

1. `schismtracker -p house9.mod`, or start playback with F5
2. let some rows play
3. press F4 to call up the Instrument Dialog
4. active channels finish playing the current sample and then go silent. Playback otherwise continues (one can also switch back to F5)

**Comment by jengelh** [comment]
Bisect:

```
commit aa84148e019a65f3d52ecd33fd84bfecfdb87bf4 (HEAD)
Date:   Sun May 12 14:30:21 2024 +0200

    Fix for OpenMPT test case NoMapEffects.it.
```

Commenting out the `continue;` line seems to fix house9.mod, but I still notice missing notes when nitestrm.mtm processes order 1 row 56.

**Comment by mrpapersonic** [comment]
Looking at the affected modules, it looks like this only happens in sample mode, so this is probably a missing conditional for instrument mode.
