### ISSUE TITLE
macOS fn-return should be Insert. Schism ignores.

### ISSUE THREAD

**Issue by esaruoho** [schismtracker/schismtracker#438]
The macOS native way of doing an `insert` is to press `Function-Return`. 

Schism ignores this.

Can you make this work?

Or what's the workaround for Mac Laptops to have Insert key in the Pattern Editor?

**Comment by mrpapersonic** [comment]
SDL 2 doesn't have a way of detecting if the fn key is down. would `Ctrl-Return` be a suitable alias?

**Comment by esaruoho** [comment]
> would `Ctrl-Return` be a suitable alias?

sure, anything that would work would work

**Comment by esaruoho** [comment]
@mrpapersonic btw, are you absolutely 100% sure FN is not detected? because i just pressed FN-Shift-Backspace on my macOS laptop and it functioned as "Delete".

**Comment by mrpapersonic** [comment]
I mean SDL doesn't provide any means to check if the Fn key is held down (nor does it send any events when it's pressed). The OS or SDL itself is probably filtering Fn-Shift-Backspace to Del internally.

**Comment by esaruoho** [comment]
> I mean SDL doesn't provide any means to check if the Fn key is held down (nor does it send any events when it's pressed). The OS or SDL itself is probably filtering Fn-Shift-Backspace to Del internally.

got it. any ideas what might be the way to filter fn-shift-something to Insert internally?

**Comment by ghostlevel** [comment]
> would `Ctrl-Return` be a suitable alias?

I just recently started looking into finding a little 'fix' (personal hacky solution) checking & modifying the source, finding a replacement key but... 

More to the point:

If Ctrl-Return is used as an alias for Insert, 
won't there be a problem when doing Alt-Ctrl-Return for Alt-Insert in the pattern editor? 
Or perhaps it could be avoided?

Because by default using Ctrl-Alt-Return on macOS toggles the Fullscreen mode ON/OFF.

>Ins/Del Insert/Delete a row to/from current channel
>Alt-Ins/Del Insert/Delete an entire row to/from pattern

Oh and... i only realise now the Fullscreen shortcut is also triggered by Command-Alt-Return.

[That's using the 20240515 binary/release.]

**Comment by mrpapersonic** [comment]
I dug up the scancode table in SDL's source, and found this gem of documentation:
https://github.com/libsdl-org/SDL/blob/f88e8da1762aca7f57ed5372035f22af7f6d495f/src/events/scancodes_darwin.h#L106
...but in the same file, there's one for `Fn-Enter` as well:
https://github.com/libsdl-org/SDL/blob/f88e8da1762aca7f57ed5372035f22af7f6d495f/src/events/scancodes_darwin.h#L140
I have no idea which one would be right to use here (or if these are even still correct), but this is at least a start

**Comment by mrpapersonic** [comment]
Mystery solved! This is the keyboard layout on the powerbook g4:
![PowerBook G4 keyboard](https://github.com/schismtracker/schismtracker/assets/37962225/a60a7ec4-4933-4cb7-a421-4ec5de06f8ba)
"enter" used to actually be its own key. neat!

**Comment by mrpapersonic** [comment]
Fixed with a4bc4bbe2b160c7d5ce4c8e318979ecc8569d915

**Comment by ghostlevel** [comment]
> Fixed with [a4bc4bb](https://github.com/schismtracker/schismtracker/commit/a4bc4bbe2b160c7d5ce4c8e318979ecc8569d915)

After a quick test I can confirm Fn-Return and Fn-Alt/Option-Return work as intended in the Pattern Editor.
Thanks for the fix!
