### ISSUE TITLE
release 20240523: there are no sources in tar.gz format anymore and the provided zip'ed sources contain tar.gz file

### ISSUE THREAD

**Issue by fordfrog** [schismtracker/schismtracker#447]
in previous releases there used to be sources file with `.tar.gz` extension, but for the latest release there are sources with `.zip` extension, but that file contains sources packaged in `.tar.gz` file. i guess that was not the intention to change the extension and do zip compression on already compressed file.

**Comment by mrpapersonic** [comment]
oops, fixed
