### ISSUE TITLE
Minipop slider click areas offset by one cell

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#46]
[HybridDog writes](https://github.com/schismtracker/schismtracker/issues/30#issuecomment-247249629):

> By the way, there's another problem: The areas where mouse clicks for spawning the minipop are recognized have a left one-character-sized unwanted offset:
> ![2016-09-15-083754_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3192173/18540738/0cbcea7c-7b21-11e6-8d6c-20a8ae25c9d7.png)
> the red box shows where you need to click, the blue one shows the area without the unwanted offset

**Comment by HybridDog** [comment]
Maybe someone added spaces before the fields for decorative reasons but didn't update an offset,
the problem doesn't apply to the right fields (Instrument etc.).

**Comment by jangler** [comment]
Easy fix, just had to change a few numbers.
