### ISSUE TITLE
Anyone else have full-windows fullscreen issues with Windows versions?

### ISSUE THREAD

**Issue by BackSpace54** [schismtracker/schismtracker#460]
Hi,
with latest ST 20240609 and Windows versions (32 and 64 bits) when switching to full windows or fullscreen the cursor in Schism Tracker is jailed in a small part of the screen.
Have you experienced the same issue?
Tested on Windows11 with 555.99 nvidia drivers, ST 20240529 works fine in full windows/full screen on the same PC.

**Comment by mrpapersonic** [comment]
yeah, I didn't catch this cause I use schism with a fixed size of 640x400 which this issue just happens to not exist with. I'll replace the binaries on the release to the fixed code once they finish building :)
