### ISSUE TITLE
Schism Tracker 20240609 (macOS build) crashes on launch

### ISSUE THREAD

**Issue by digistorm79** [schismtracker/schismtracker#463]
As described, the latest build of Schism Tracker (20240609) for macOS crashes on launch. MacOS gives this information on crashing:

`Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /Users/*/libFLAC.12.dylib
Referenced from: <CA736528-8326-3E6F-AB91-6851F077F0C2> /private/var/folders/*/Schism Tracker.app/Contents/MacOS/schismtracker
Reason: tried: '/Users/*/libFLAC.12.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/*/libFLAC.12.dylib' (no such file), '/Users/*/libFLAC.12.dylib' (no such file), '/usr/local/lib/libFLAC.12.dylib' (no such file), '/usr/lib/libFLAC.12.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)`

I checked the presence of libFLAC.12.dylib and I also copied the same file from the previous version of Schism Tracker but that did nothing.

I am running on macOS Sonoma 14.5 on a M1 Pro chip. The previous build still works fine. Maybe this happened together with the merger of the ppc build and the Intel/ARM build?

**Comment by mrpapersonic** [comment]
~~Is this on Apple Silicon? I can't replicate this on Intel Catalina.~~ whoops. didn't read :)

**Comment by mrpapersonic** [comment]
Same issue as #378 but fortunately only for arm64.

**Comment by mrpapersonic** [comment]
This issue should be fixed as of this build (from commit ab05a80b2e8a409a06a89013c00b852fba184d41): [schismtracker-20240610-macos.zip](https://github.com/schismtracker/schismtracker/actions/runs/9454719141/artifacts/1587024187). please test it so I don't push out a broken build again :)

**Comment by digistorm79** [comment]
Yes, it is working.

**Comment by madwreck** [comment]
Loading for me on m2 MacBook Air (Sonoma 14.5), however it crashes when attempting to load sample. Repro steps:

1.  Open program
2. Press f3
3. when sample slot 01 is selected, press Enter/Return
4. Program crashes
