### ISSUE TITLE
Every sample file is in an "Unknown format" unless I load it from a module

### ISSUE THREAD

**Issue by ruby-R53** [schismtracker/schismtracker#480]
I installed Schism from its latest commit, which was supposed to fix that, but apparently it's not working for me. Any file I try to load as a sample just doesn't load at all and I get that "Unknown format" description at the format field.

However, if I try to get a sample directly from a module instead of from a file, Schism plays it normally somehow.

If necessary, this is how I `configure` it:

```
./configure --enable-extra-opt --enable-alsa-linking \
            --disable-sdltest
```

and turning any of those options off/on doesn't have any effect.

**Comment by abandpass** [comment]
I have the same behavior when building under Mac OS 14.5 (Apple Silicon).  I don't use any options when doing ./configure however.  When i open up Schism, press F3, then try to load a sample, any samples i have are not recognized.

**Comment by ruby-R53** [comment]
yeah it's weird, at least it's not only me who has the same issue xd
