### ISSUE TITLE
"Note off" command with instrument number

### ISSUE THREAD

**Issue by AeroPurple** [schismtracker/schismtracker#485]
When a "note off" (===) command has an instrument parameter, the note being cut reverts to the instrument's default volume value before cutting.

I noticed this when listening to the module "blocks.it" ( https://modarchive.org/index.php?request=view_by_moduleid&query=169515 ) and OpenMPT has no issues playing back this track.

I recorded a side-by-side comparison here: https://github.com/schismtracker/schismtracker/assets/174095112/994f0509-6811-4ad0-af36-f694bf9d14e5

Changing the instrument number on the "note off" command actually didn't change the sample being played back. It sounded just the same. The only way I could fix it was by removing the instrument number altogether.

**Comment by sagamusix** [comment]
The module was written with an old version of OpenMPT. OpenMPT generally tries to play files made with older OpenMPT versions by emulating the playback bugs those versions had. Schism Tracker does not emulate old OpenMPT quirks (or even old Schism Tracker quirks for that matter). If you go to Song Properties in OpenMPT and click the "Set Defaults" button to activate all the latest IT playback compatibility settings, the file will also sound broken there. If you want to listen to the file without playback quirks, you'll have to remove all the instrument numbers next to note-offs.

**Comment by AeroPurple** [comment]
Okay, that makes sense. Thanks!

**Comment by mrpapersonic** [comment]
I'm considering adding a menu of playback compatibility flags but it would definitely have to be after #476 gets figured out, which would make the implementation much easier.
