### ISSUE TITLE
keyjazzing starts a neverending stream of MIDI tick codes

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#49]
If we play a note keyjazz-style, a stream of MIDI ticks starts which continues until e.g. the stop key is pressed - even once the keyjazzed sample has finished, the ticks will go on.

While maybe keyjazzing is technically (or is in implementation terms) playback, IMHO for MIDI tick code purposes this probably isn't what we really want.

Any opinions?

**Comment by ghost** [comment]
OTOH, maybe for MIDI instruments that have, e.g, arpeggiators or delay effects, you _would_ want ticks - should it be a config option?

**Comment by sagamusix** [comment]
It definitely doesn't make sense to send MIDI ticks just "sometimes" (your second comment already explains why - try setting LFOs or arpeggiators to "MIDI sync" mode in a device to see the effect), so they should either be sent always or never.

**Comment by ghost** [comment]
Yeah, convincing point. Will close this and leave it how it is.
