### ISSUE TITLE
Schismtracker-git Save Instrument to Disk (null is a directory)

### ISSUE THREAD

**Issue by brandflake11** [schismtracker/schismtracker#491]
**Preliminary System Info:**
On UniversalBlue Fedora Atomic Sway 40

**How I Install/use Schismtracker:**
Download the release zips from this github repo and compile (using instructions from INSTALL) in an Arch Linux distrobox container and run the compiled schism from distrobox (specifically using [this](https://github.com/brandflake11/arch-audio-container) container). This time, I compiled the git source version after the very last commit (that fixed Alt-O crashing)

**The Problem:**
I'm not sure if this is a feature that hasn't been implemented yet, but in the Instrument List, performing an Alt-O, after fixing the segfault, now just returns a "(null) is a directory message", and doesn't save the .it format that the help states it should (unless it is saving it to an unusual directory). Exporting the instrument with Alt-T does work, but should the Alt-O still work?

**Comment by mrpapersonic** [comment]
Put a filename into the instrument filename box...

**Comment by esaruoho** [comment]
> Put a filename into the instrument filename box...

i think having a warning for that, and/or autofocus instrument filename box, before allowing it to do it's job, would be pretty good, right?

**Comment by brandflake11** [comment]
To be honest, I didn't even know there was a separate filename input at the bottom of the General tab in the Instrument List. 

After looking into how Impulsetracker handles this, the message without a filename is: "Error: Instrument [num of instrument] NOT saved! (No Filename?)" I think something like this would be clearer, and if we wanted to keep close to Impulsetracker, as schism is a recreation, then maybe including this message would be more helpful than "(null) is a directory", which looks like a bug. 

I also like the idea of autofocusing the instrument filename box; I think that also makes sense.

I need to learn c so I can help out with the programming (I'm sorry about that!)

**Comment by mrpapersonic** [comment]
yep, there was an error for it like that. Don't know what really caused it to stop displaying tho, might need to screw around more with the code
