### ISSUE TITLE
Schism drops .xm effect Kxx

### ISSUE THREAD

**Issue by 0xHexaDecimator** [schismtracker/schismtracker#492]
The .xm effect Kxx is a note-off where xx is an optional delay in ticks
![image](https://github.com/user-attachments/assets/a63aad18-d5ef-47c6-9346-5bc182d630ac)
IT converts the effect to a note-off
![image](https://github.com/user-attachments/assets/a22207b5-d2f3-4471-b1d8-d4a4ac4daf7a)
When converting .xm to .it with openMPT, it converts the effect to a note-off with SDx
![image](https://github.com/user-attachments/assets/32866b4a-3aca-4286-b970-482aedea950c)
Schism drops the effect entirely
![image](https://github.com/user-attachments/assets/8b1183ec-46df-4f66-8b93-98ce4e11f4ab)

**Comment by sagamusix** [comment]
This is one of the few non-IT effects that Schism Tracker actually imports as a custom effect. It shows up as effect `$` (but cannot be saved to IT files of course). What you are observing is a special case for `K00`: FastTracker 2 has a bug with parameter 0 and neither plays the effect, nor the note next to it. If you tried this with command `K01`, you would have seen the effect being imported as expected.

**Comment by sagamusix** [comment]
Hm actually the description in the Schism source is inaccurate... the `K00` effect itself should still be executed but the note and instrument columns next to it should be ignored...
