### ISSUE TITLE
Recognize Uppercase File Extensions

### ISSUE THREAD

**Issue by brandflake11** [schismtracker/schismtracker#494]
**Preliminary System Info:**
On UniversalBlue Fedora Atomic Sway 40

**How I Install/use Schismtracker:**
Download the release zips from this github repo and compile (using instructions from INSTALL) in an Arch Linux distrobox container and run the compiled schism from distrobox (specifically using [this](https://github.com/brandflake11/arch-audio-container) container). This time, I compiled the git version of schismtracker.

**The Suggestion:**
Recently I've noticed that schismtracker doesn't recognize capital file extensions (.IT, .XM, .MOD). I think it would be advantageous, as schismtracker is used to interface with classic modules, and if the person tries to open up their modules from the DOS era, it might be all uppercase. 

Is it possible to have this as a feature, so users don't need to batch rename all of their old modules (including ones from the modarchive that might be uppercased)?

**Comment by vcaputo** [comment]
My guess is fnmatch.h has changed in ways that broke the way schism integrated it / defined FNM_CASEFOLD to 0.  Maybe old versions didn't gate the FNM_CASEFOLD on _GNU_SOURCE et al:
```
#if !defined _POSIX_C_SOURCE || _POSIX_C_SOURCE < 2 || defined _GNU_SOURCE
# define FNM_FILE_NAME>· FNM_PATHNAME>··/* Preferred GNU name.  */
# define FNM_LEADING_DIR (1 << 3)>······/* Ignore `/...' after a match.  */
# define FNM_CASEFOLD>·· (1 << 4)>······/* Compare without regard to case.  */
# define FNM_EXTMATCH>·· (1 << 5)>······/* Use ksh-like extended matching. */
#endif
```
^^^ /usr/include/fnmatch.h on this Arch install.

Try this for your configure line:
`CFLAGS=-D_GNU_SOURCE ./configure` then recompile, it made it work again here.

**Comment by brandflake11** [comment]
Compiling with this configure line fixed it for me. I didn't realize that it could be a system library that caused this. I guess in a way that means I just didn't compile it correctly. Is this something that should be left open, or should we put the CFLAGS here in the INSTALL file for others to compile with? 

Unfortunately, I don't know enough about C and make to know.

**Comment by mrpapersonic** [comment]
err, yeah. I removed the `_GNU_SOURCE` define because I really don't like relying on any gnu extensions (POSIX is the primary goal). Additionally this will break on most systems especially regarding unicode things.

Really, we just need a charset-aware implementation of fnmatch that implements real case folding (which I'll probably set to fall back to the system implementation if charset decoding failed...)
