### ISSUE TITLE
Automatically select window type (Channels)

### ISSUE THREAD

**Issue by HybridDog** [schismtracker/schismtracker#50]
If you play a file, three windows appear. The channel window, the lowest one, is always set to display 24 possible channels:
![2016-09-29-124210_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3192173/18951115/93995206-8643-11e6-9bd1-106bc21c3f2b.png)
Instead of setting it to 24, it could automatically detect the amount of used channels and configure the window type that every channel is visible:
![2016-09-29-124325_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3192173/18951117/9c26c4a8-8643-11e6-9465-348fdf93e60f.png)
So no space is wasted (more detail instead) and with more than 24 used channels every channel would be displayed.
For people who don't like this behaviour, a setting can be added to disable it.
To not break existing configurations, the setting is disabled by default.

**Comment by jangler** [comment]
> If you play a file, three windows appear. The channel window, the lowest one, is always set to display 24 possible channels:

Based on your second screenshot I'm sure you know this, but all of that is just the default.

> For people who don't like this behaviour, a setting can be added to disable it.

Would definitely be an opt-in and not an opt-out. Could mess up people's existing configurations.

**Comment by HybridDog** [comment]
There are tracker music files which have many enabled channels although only a few of them are used.
Example: https://sourceforge.net/p/extremetuxracer/code/HEAD/tree/branches/release_0.4/data/music/race1-jt.it

> Could mess up people's existing configurations.

ok, l updated issue text

**Comment by jangler** [comment]
I'm gonna mark this wontfix; it's easy enough to just cycle through the possible displays with PgUp / PgDn to get the detail level you want. Maybe easier than having the tracker guess for you.
