### ISSUE TITLE
Handling of XM volume column panning slides

### ISSUE THREAD

**Issue by 0xHexaDecimator** [schismtracker/schismtracker#501]
There are FT2 compatibility effects to handle volume column panning slides, but they appear to go unused. 
(Schism also cannot save XM modules, unsure why that's stated!)
![image](https://github.com/user-attachments/assets/8b41ff23-cb46-4530-ac12-f7c194862702)
­

Here's some of those panning slides
![image](https://github.com/user-attachments/assets/4ecbcf20-9637-4464-8fb6-ff1e7c7c8cd6)

Schism appears to translate them into P0x/Px0, even shifting other effects over to the volume column to make that happen.
![image](https://github.com/user-attachments/assets/68951ae6-24dc-4f92-b45b-0d6330d479b1)

Where moving an effect to the volume column is not possible, Schism just drops the effect entirely instead. 
![image](https://github.com/user-attachments/assets/be4b0cde-4fea-408e-b92f-1fd029bc6e00)

**Comment by mrpapersonic** [comment]
looks like the FT2 compatibility vol effects were never implemented in the hackarounds used for XM import:
https://github.com/schismtracker/schismtracker/blob/ee44cb6ebc509beca517d5cfe5a44cb6c7a3c0cd/fmt/generic.c#L100

no mention of panning slide effects here at all. as a result it falls back to shoving it in the effects column which is Good Enough for 99% of cases, probably why this wasn't caught early on.

**Comment by mrpapersonic** [comment]
Fixed with b271945064ec8a1378cb02b9bf25b829883b26b0
