### ISSUE TITLE
Save/Export page buttons obscured by extended directory navigation window

### ISSUE THREAD

**Issue by 0xHexaDecimator** [schismtracker/schismtracker#502]
Buttons on the save (F10) and export (Shift+F10) module pages are blocked by the extended directory navigation window on the right.
![image](https://github.com/user-attachments/assets/91ed32f2-029a-4030-b935-207aa91c9f1b)
You can still click the buttons through the black window, but you definitely can't read them.

**Comment by mrpapersonic** [comment]
oops, I didn't even notice that when reworking it :/

will probably switch the export module page to use different dimensions because I like the added directory space in the load screen

**Comment by retrohun** [comment]
git diff -b 1f10ee72..e8384f2c
The oldest commit broke it in the end of May. Not just committed a unicode stuff, but also resized the widgets.
Unaware about that the save_module_draw* stuff uses load_module_draw* p.ex.

schism/page_loadmodule.c:
 588 static void save_module_draw_const(void)
 589 {
 590         load_module_draw_const();
 591 }

The only altered file in the topic commit is:
$ git diff -b 1f10ee72..e8384f2c --numstat
32      55      schism/page_loadmodule.c

1f10ee72 (HEAD) page_loadmodule: unicode-awareness

One possibble solution is to cherry-pick former widget sizes till save_module* will be populated.

**Comment by hotgar** [comment]
You could probably move the directory widget's lower edge a couple of lines up since its scrollable anyway and place the buttons under it.

**Comment by retrohun** [comment]
> You could probably move the directory widget's lower edge a couple of lines up since its scrollable anyway and place the buttons under it.

It is unsatisfactory even for a workaround. Imagine a newbie user or a former impulse tracker fan who wants to save their songs in .S3M. Even if it would be properly documented in the future, the inteface would remain counter-intuitive.

**Comment by hotgar** [comment]
![2024-08-01T16-00-07-144](https://github.com/user-attachments/assets/71aa5ab6-f614-42e9-91ec-a51e447f3828)
Would something like this be really that unintuitive? Just an idea.
You may even put a text label there specifying that those buttons are for output format selection.
Or maybe even move the buttons to the very bottom of the screen.

**Comment by retrohun** [comment]
Hmmm, subjective opinion, but cool! I only miss ".MOD" selector "radio" button.

**Comment by mrpapersonic** [comment]
> ![2024-08-01T16-00-07-144](https://private-user-images.githubusercontent.com/4434388/354101342-71aa5ab6-f614-42e9-91ec-a51e447f3828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NTg5MTcsIm5iZiI6MTcyMjU1ODYxNywicGF0aCI6Ii80NDM0Mzg4LzM1NDEwMTM0Mi03MWFhNWFiNi1mNjE0LTQyZTktOTFlYy1hNTFlNDQ3ZjM4MjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDAzMDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U2OWU1ZTI5YjlhN2M1ZTk0ODI4NTBjOWU4YmMxNzA3ZjMzYzk2YTg5ZjA4ZGM4ZWMxOTNhNmQxZjM3MjMwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n0XYshw9GyOtg1pDixZvEdtgGdeHMMz37V_OnWLcjCQ) Would something like this be really that unintuitive? Just an idea. You may even put a text label there specifying that those buttons are for output format selection. Or maybe even move the buttons to the very bottom of the screen.

I actually really like this idea, but I'd personally add more spacing between the buttons to make it look more "even" (and possibly expand the directory a little to the bottom as well). I'll implement this whenever I get to it :p

**Comment by gera2342** [comment]
@mrpapersonic Now switching between tabs using tab key gets stuck on "dir_list" tab in both "load_module" and "exportsave" pages. Something with `dir_list_handle_key*` functions?

**Comment by mrpapersonic** [comment]
The separate handle key functions didn't return the value that the original did (which is actually important) but for some reason gcc didn't care to warn me about that (even though I specifically remember that it has before... ugh)

Fixed in a4c55e2
