### ISSUE TITLE
Custom font does not get applied in parts of Load Module tab

### ISSUE THREAD

**Issue by AeroPurple** [schismtracker/schismtracker#504]
I have just made a custom font and saved it to font.cfg, and it works fine. However, when I opened the Load Module (F9) tab, two of the panels did not inherit the custom font.

![image_2024-07-29_18-03-12](https://github.com/user-attachments/assets/259b0586-8299-47c2-9209-2c59dc41ab68)

As you can see, the module titles are fine, but the directory names and filenames use the default font.

There may be a legitimate reason for this, like characters outside of the default 256 showing up in the names, but still, it feels like a bug to me.

**Comment by mrpapersonic** [comment]
This was already fixed in the current source tree with a45c7842be029979d7097314b336b96797791caf

**Comment by AeroPurple** [comment]
Indeed, it is now fixed as of version 20240809!
Though, unfortunately, the custom font is not applied to the Audio Devices lists in Preferences, as seen in this screenshot:
![audio devices in Preferences](https://github.com/user-attachments/assets/d2f4f7f5-1ea0-4f7a-9a3b-76293e155090)

**Comment by mrpapersonic** [comment]
Fixed that with 0d0ddcc81d2690b443edc7afbd60d19caac8a833

**Comment by AeroPurple** [comment]
Okay, I know that I sound like a broken record right now, but there are still some areas that do not have custom fonts applied.
So far I've only encountered these two in 20240909:

The textbox for typing in the filename is one, though considering the textbox having a different problem in Issue #528, this might have already been fixed:
![image](https://github.com/user-attachments/assets/d6c6e700-0a14-49e8-be98-3aeaec6f0e8f)

And another one can be found in the Message Editor:
![image](https://github.com/user-attachments/assets/fb94013c-10ce-4d85-9c61-ac8f36bd4c50)

Again, since these are the only ones I've seen in the current version, if they will be fixed, then the custom fonts will have zero issues.

**Comment by mrpapersonic** [comment]
The message editor is intentional and that behavior has been the default since forever ago. You can change it to the regular font using Ctrl-T.

The search bar is more difficult to deal with because of internal stuff regarding encoding conversions (to/from UTF-8 and CP437) which is a pain.
