### ISSUE TITLE
macOS Build Failure

### ISSUE THREAD

**Issue by SaaxBox** [schismtracker/schismtracker#505]
An unknown error is observed after `brew install`-ing the packages specified in [building_on_osx.md](https://github.com/SaaxBox/schismtracker/blob/master/docs/building_on_osx.md), restarting my terminal, running `autoreconf -i`, `cd`-ing into the build folder, and running `../configure && make`.
```
../configure: line 5856: syntax error near unexpected token `SDL,'
../configure: line 5856: `    PKG_CHECK_MODULES(SDL, sdl2 >= $min_sdl_version,'
```

Can provide more information as needed.

**Comment by mrpapersonic** [comment]
`pkg-config` or `pkgconf` is needed to bootstrap the configure file.

(actually, why does homebrew not install this by default?)
