### ISSUE TITLE
huxchx.it (my own mod) is broken

### ISSUE THREAD

**Issue by mrpapersonic** [schismtracker/schismtracker#508]
link: https://modarchive.org/module.php?199486

**Comment by gera2342** [comment]
If you mean the weird beep, it also happens in this module http://modland.com/pub/modules/Protracker/Quazar/trolly-tune.mod (OpenMPT plays ok)

**Comment by mrpapersonic** [comment]
That's a mod tune, so it's more difficult to say whether it's an importer bug or a replayer bug. Unlike the replayer, importers do not import the same as Impulse Tracker, by design. for instance, Impulse Tracker's XM importer does some very weird things to volume column effects that schism does not replicate.

To check if it's really a bug in Schism's replayer or a bug in the importer:
1. load the module into Schism
2. save it as an IT file and export the result to a wav
3. open the result IT file in the original Impulse Tracker and play it back using the wav writer driver
4. compare the results. if playback is the same, it's an importer bug, otherwise, it's a replayer bug. (sometimes it could even be both!)

maybe this should be officially documented somewhere? :p

**Comment by gera2342** [comment]
Yeah the beep is present in both wav files

[trolly.zip](https://github.com/user-attachments/files/16509829/trolly.zip)

**Comment by sagamusix** [comment]
That module makes use of a quirk of the ProTracker routine (arpeggio frequency wrap-around) that cannot be emulated with Schism Tracker, because it's not a multi-format module player.
