### ISSUE TITLE
Filters broken since 20240714

### ISSUE THREAD

**Issue by laamaa** [schismtracker/schismtracker#511]
Since commit [bshift: add compiler-independent bitshift functions](https://github.com/schismtracker/schismtracker/commit/209e93e0c2beddf92f257aa6411f09084071c8a4),  the builds created by GH actions seem to have broken filters, at least on my Fedora 40 Linux box.

When a filter is set to anything below Z7F, the instrument gets just muted.

Example module included below,
[laamaa-novelleplus.zip](https://github.com/user-attachments/files/16522164/laamaa-novelleplus.zip)

how it should play back: https://www.youtube.com/watch?v=V6xCVt98V1o

**Comment by mrpapersonic** [comment]
seems to be related to #508. That module also uses filters and samples using it get muted instantly.

**Comment by laamaa** [comment]
The filters seem to start working correctly again when SNDMIX_PROCESSFILTER is reverted to the code before the previously mentioned comment, so probably something to do with those changes:

https://github.com/schismtracker/schismtracker/commit/209e93e0c2beddf92f257aa6411f09084071c8a4#diff-3e648fd0ca0e5701e2c98f9185c0660fc1eb15d81b5939a43c3b677678969a50R287-R292

**Comment by mrpapersonic** [comment]
note to self: this is caused by using 32-bit signed bit shift operations; here it has to use 64-bit because of the extra precision it allows
