### ISSUE TITLE
portable.txt is read from current directory rather than program directory

### ISSUE THREAD

**Issue by sagamusix** [schismtracker/schismtracker#512]
https://github.com/schismtracker/schismtracker/blob/c98f03f33735484f41a4ecd3306620cff691f542/schism/config.c#L75

As a result, if there is a portable.txt in Schism's directory, launching `./schismtracker` from that directory correctly realizes that this is supposed to be a portable installation, but running `/path/to/schismtracker` will try to read the file from wherever the current directory is, 
and the installation is not recognized to be portable.

**Comment by mrpapersonic** [comment]
Getting the current program directory in general is a hassle, and mostly platform specific. A *somewhat reliable* method of doing this:
1. Make platform-specific implementations; the good news is that [I've written code to do this before (see the `GetProcessName` functions, the file descriptor code is irrelevant for schism)](https://hg.paper.us.eu.org/minori/file/tip/dep/animone/src/fd), though C++17 and not C99. this crap would probably get stuffed into the `osdefs.c` for each platform
2. if that fails, fall back to getting the parent directory of `argv[0]`
3. and if that also fails somehow, just use the current directory or assume nonportable

though tbh, we could also just copy `argv[0]` and say that that's "good enough"...

**Comment by sagamusix** [comment]
> Getting the current program directory in general is a hassle, and mostly platform specific.

Not on SDL ;)

https://wiki.libsdl.org/SDL2/SDL_GetBasePath

**Comment by mrpapersonic** [comment]
WTF. I didn't even know SDL had a filesystem API :p 

that makes this a whole lot easier then
