### ISSUE TITLE
macOS  keyboard repeat rate + speed does not conform to macOS Settings

### ISSUE THREAD

**Issue by esaruoho** [schismtracker/schismtracker#522]
20240809 build

![key repeat](https://github.com/user-attachments/assets/bfb34343-f54d-477a-a07b-c6e6ffb2def1)

i don't know why this doesn't follow key rate. i have them at max in macOS Keyboard. but Schism ignores them.

**Comment by mrpapersonic** [comment]
Schism specifically doesn't follow the system key repeat rate, see `docs/configuration.md` on how to configure it.

It's very useful to have a different key repeat rate for tracking than say, typing a word document for example, which is why this feature was re-added after it broke in the SDL2 port.
