### ISSUE TITLE
Focus Jump in Load Module menu (F9) 20240809

### ISSUE THREAD

**Issue by brandflake11** [schismtracker/schismtracker#523]
**Preliminary System Info:**
On UniversalBlue Fedora Atomic Sway 40

**How I Installed/used Schismtracker:**
Use the Arch Linux package in Arch's extra repo in an Arch container with distrobox. Schismtracker 20240809

**The Problem:**
In the Load Module menu (F9), when the cursor is in the directory box (shows all of the directories listed on the rightmost side of the program), using the arrow keys if you type up after the ".." the cursor will jump to the module files box instead of going up to the "/".

**Comment by mrpapersonic** [comment]
This is the same issue as jiffygist reported in another issue and was fixed by a4c55e24505a600d373e1015b68817cfe4aa1602

**Comment by brandflake11** [comment]
Ah, sorry, I missed it!
