### ISSUE TITLE
Load Module: file search is broken

### ISSUE THREAD

**Issue by drradio** [schismtracker/schismtracker#528]
File search in Load module page does not work in version 20240909, but works in 20240809.
How to reproduce:
1) Open Load module page (F9);
2) Enter part of file name;
3) Nothing...

OS: Debian GNU/Linux 12.7 (stable)
Tested build: Schismtracker 20240909 (built from source)

**Comment by 0xHexaDecimator** [comment]
Broken with 20240909 on Windows 10 as well 

EDIT: Apparently it works if I type the _entire_ filename (including extension) into the searchbar

**Comment by drradio** [comment]
Found a bug in charset_strncasecmp. Preparing patch.

**Comment by drradio** [comment]
Created pull request #529.
