### ISSUE TITLE
How to scale window without scaling UI?

### ISSUE THREAD

**Issue by polyzium** [schismtracker/schismtracker#54]
How i can force Schism to have more screen space/to set large video mode like on this screenshot?

http://4.bp.blogspot.com/-08x0xDsRYfY/Utfyvto5uFI/AAAAAAAAHkc/V19V74gZ1zg/s1600/schism.gif

P.S. Sorry for my bad English

**Comment by jangler** [comment]
Unfortunately not possible in Schism unless I'm missing something big. I wonder where Tracker Base got that image.

**Comment by polyzium** [comment]
Me too actually. Btw will u implement this sometime in the future?
P.S. Also is it possible to port schism to ncurses without SDL and framebuffer stuff?

**Comment by polyzium** [comment]
Maybe previous versions (2009 like on this screenhsot) do have this ability?

**Comment by jangler** [comment]
@Storlek might know some lore related to this.

**Comment by polyzium** [comment]
I just emailed Storlek about that and here's what he responded me:

"Ahh, unfortunately that's not real, we can only wish. Someone made a mock-up of what the screen could look like if it was bigger. Since the whole interface is built with hardcoded position numbers, making it resizable would be a huge undertaking.

Similarly, I think it'd take an impractical amount of work to port Schism Tracker to ncurses as it'd require abstracting out all the SDL input and output, and curses keyboard handling is not nearly as robust (many keys won't translate, combinations of modifiers won't work, etc.) — not to mention the added issues of handling other character sets, and either remapping all the funny line drawing characters or requiring a custom font.

But maybe some new program in the future will come along and solve all of these things……… ;)"

Well, this screenshot is fake. And also Schism will not support ncurses. It's a pity...

**Comment by jangler** [comment]
Well, I guess that answers that question. It is a pity; you're not the only one to want this feature. Thanks for helping resolve this.

**Comment by sagamusix** [comment]
If you don't need an exact IT clone but just want to have the IT look&feel in a higher resolution, you can probably give "BeRoTracker Impulse" a try. It's a version of BeRoTracker with a resizable IT-like interface. ftp://ftp.modland.com/pub/software/trackers/Windows/BeRoTracker/
