### ISSUE TITLE
More than 64 channel XM file loading problem

### ISSUE THREAD

**Issue by DroidU** [schismtracker/schismtracker#541]
If I load the following 2 XM modules edited with OpenMPT, it sees it as a MOD and nonsensical things appear.
- https://api.modarchive.org/downloads.php?moduleid=183643#psirius_-_signals.xm
- https://api.modarchive.org/downloads.php?moduleid=183611#psirius_-_a_small_big_bang.xm

If I save these to IT with OpenMPT and then load it, it loads it with warning messages, but only up to 64 channels.

**Comment by sagamusix** [comment]
Using more than 64 channels in IT (and XM) files is an OpenMPT extension that really shouldn't exist. I don't think there is any software outside OpenMPT supporting this extension.

**Comment by 0xHexaDecimator** [comment]
> If I load the following 2 XM modules edited with OpenMPT, it sees it as a MOD and nonsensical things appear.

Schism loads any module formats it cannot identify as a 15 sample MOD (because 15 sample MODs are non-identifying)
There probably should be a warning for nonstandard XM modules with too many channels (iirc Milky can produce these).

**Comment by DroidU** [comment]
> Using more than 64 channels in IT (and XM) files is an OpenMPT extension that really shouldn't exist. I don't think there is any software outside OpenMPT supporting this extension.

BeRoTracker can play it perfectly.

**Comment by sagamusix** [comment]
That makes it two implementations then. But that still doesn't matter because Schism Tracker, except for very few exceptions, stays true to IT's original limitations, and does not support more than 64 channels.
