### ISSUE TITLE
schismtracker-20241021.source.tar.gz missing mem.h

### ISSUE THREAD

**Issue by jengelh** [schismtracker/schismtracker#548]
The https://github.com/schismtracker/schismtracker/releases/download/20241021/schismtracker-20241021.source.tar.gz tarball does not included mem.h like the git repository does. As a result, there is a compile error

```
2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -c -o fmt/schismtracker-flac.o `test -f 'fmt/flac.c' || echo './'`fmt/flac.c
[    8s] In file included from ./include/fmt.h:30,
[    8s]                  from fmt/flac.c:27:
[    8s] ./include/util.h:97:10: fatal error: mem.h: No such file or directory
[    8s]    97 | #include "mem.h" // XXX these includes suck
```

Should that tarball be used at all?

**Comment by mrpapersonic** [comment]
I'm so sorry... I've neglected to add a `make distcheck` test to CI for the longest time and now it's bitten me again :)

I'll fix the tarball, but the release will still be pointing to the wrong commit which is annoying.
