### ISSUE TITLE
Warning is shown when font.cfg does not exist

### ISSUE THREAD

**Issue by sagamusix** [schismtracker/schismtracker#549]
This appears to be new in the 20241021 release:

![grafik](https://github.com/user-attachments/assets/1032e3aa-91fb-4e89-b9e3-2d8c7861ce60)

**Comment by mrpapersonic** [comment]
I think this is win32's slurp acting up. slurp implicitly believes the file exists and tries to open it (and fails) so I think it needs to actually stat the file properly and not just assume the file exists when no existing stat structure is passed.
