### ISSUE TITLE
Toggle sample quality without converting distorts sample

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#55]
Original sample (16-bit):
![before](https://cloud.githubusercontent.com/assets/1653421/19967998/fc29f3ea-a1a8-11e6-9153-e007a39d65b1.png)

After toggle quality without conversion:
![after](https://cloud.githubusercontent.com/assets/1653421/19967997/fc2a056a-a1a8-11e6-9bd3-8c59bdfdbc6f.png)

After toggle quality with conversion:
![after2](https://cloud.githubusercontent.com/assets/1653421/19967999/fc307b7a-a1a8-11e6-831a-e5c1dbadad8b.png)

Only happens with certain samples. Impulse Tracker does this too, but it seems very wrong and not at all useful. Most samples just become noise.

**Comment by ghost** [comment]
I think the point is that if you've loaded your sample and it's noise you can use this to fix it. Less of an issue now we all use RIFF WAV but back in DOS days there were lots of samples in "formats" that were just headerless PCM with a random file extension.

With conversion: Takes the sample to be 8 or 16 bit PCM (whatever's in the Quality field), actively converts it to the other one
Without conversion: Toggles between interpreting the sample as 8-bit or 16-bit PCM without modifying the data at all

Someone correct me if I'm wrong :)

**Comment by jangler** [comment]
That's correct re: the implementation, and "the point" makes sense to me. I'll close this; there's no reason to break IT compatibility here.
