### ISSUE TITLE
Facebonk thinks schismtracker.org is about hacking, or something

### ISSUE THREAD

**Issue by logiclrd** [schismtracker/schismtracker#556]
This isn't an actual issue about Schism Tracker, per se. I'm creating it here because I couldn't find any chat or mailing list or other contact info. Maybe I just missed it. Anyway, I hope you'll forgive me.

I played with trackers as a kid, especially Scream Tracker and Impulse Tracker, and I was delighted when I discovered Schism Tracker a year ago.

I posted a link to schismtracker.org to my Facebonk profile to share it with whoever is weird enough to follow me. And... Facebonk decided that your web site has something to do with hacking, or something. I appealed, and they denied the appeal.

Apparently, Facebonk considers tracker music to be a major cybersecurity issue!

![Screenshot_20241115-072617.png](https://github.com/user-attachments/assets/6d87356f-4e08-4af0-bcc5-dbd237591b97)

Not sure there's anything to be done about it. Facebonk is pretty opaque about such things. Anyway, just thought I'd let you know, mostly more for the amusement factor than anything else.

**Comment by TheSystemGuy1337** [comment]
There is **nothing** the developers of Schism can do to fix this. They would likely have to move domains, which is expensive and time consuming and that may not even fix the issue. You could try to circumvent their broken moderation via link shorteners or direct obfuscation of the URL in binary or hexadecimal, but I do not recommend engaging in such tactics.

**Comment by mrpapersonic** [comment]
I don't really care about facebook nor about their weird moderation guidelines (I couldn't even put my own damn website on my profile for months) and as TheSystemGuy1337 said there's nothing we can do about it.

P.S. this would belong better maybe in a discussions thread
