### ISSUE TITLE
Linking error on Mint 17.2

### ISSUE THREAD

**Issue by discworld** [schismtracker/schismtracker#56]
When compiling on Linux Mint 17.2, I got this linking error:
> /usr/bin/ld: schism/util.o: undefined reference to symbol 'powf@@GLIBC_2.2.5'
> //lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line

I managed to successfully link it eventually by manually adding libm to the failed command ( -lm). 

Compiled from master branch, HEAD was at f5f711aa1d1fb894238283fe5a8bf30ad41f38a0.

**Comment by jangler** [comment]
I had this same issue with Debian sid using crouton, and fixed it the same way. Will need to take a look at the autoconf stuff; I see that `LIBM` and `-lm` are used but are apparently not functioning on some distros.

**Comment by discworld** [comment]
I managed to make it work with this change:

```
-LT_LIB_M
-AC_SUBST(LIBM)
+AC_SEARCH_LIBS([powf], [m])
```

**Comment by jangler** [comment]
Works for me on Arch and Debian sid. One of the Travis builds and one of the AppVeyor builds failed for seemingly unrelated reasons; I need to figure out what's up with them…

Edit: the CI builds are working now.

**Comment by discworld** [comment]
For the Travis build, it's as if SDL is not installed.

**Comment by jangler** [comment]
Not sure why it took me so long to merge this change; it's merged now and all the builds succeeded.
