### ISSUE TITLE
Only able to select MIDI ports provided by OSS on Linux

### ISSUE THREAD

**Issue by meanwhile0** [schismtracker/schismtracker#560]
I'm running a system using PipeWire, and I'm unable to configure Schism Tracker to use any MIDI ports provided by drivers other than OSS. I've only tested this with the latest release version available on the Arch repos (20241021). I've attempted to manually tell Schism to use PipeWire's `MIDI Through Port-0` port in the config as this is the same port exposed to other SDL2 applications I've tested, but to no avail.

![image](https://github.com/user-attachments/assets/0d3ceb8e-c5b6-4f6e-8143-6ac262629580)

I've attempted to build Schism from source to see if the issue persists at all, but the compilation failed with the following errors regarding `midi-alsa.c`:
```
gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I.                -D_REENTRANT   -DUTF8PROC_EXPORTS -g -O2 -Werror=return-type -MT sys/alsa/schismtracker-midi-alsa.o -MD -MP -MF sys/alsa/.deps/schismtracker-midi-alsa.Tpo -c -o sys/alsa/schismtracker-midi-alsa.o `test -f 'sys/alsa/midi-alsa.c' || echo '../'`sys/alsa/midi-alsa.c
In file included from ../sys/alsa/midi-alsa.c:46:
/usr/include/alsa/seqmid.h:525:39: error: unknown type name ‘snd_ump_endpoint_info_t’; did you mean ‘snd_seq_port_info_t’?
  525 |                                 const snd_ump_endpoint_info_t *info,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~
      |                                       snd_seq_port_info_t
/usr/include/alsa/seqmid.h:528:36: error: unknown type name ‘snd_ump_block_info_t’
  528 |                              const snd_ump_block_info_t *info);
      |                                    ^~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:3533: sys/alsa/schismtracker-midi-alsa.o] Error 1
```

**Comment by mrpapersonic** [comment]
The alsa compile error is a bug in alsa fixed with https://github.com/alsa-project/alsa-lib/commit/07cee0ba05179a56764c35975d5822420d4f31f9.

The Arch Linux builds are not being given the necessary alsa and jack development headers, which is why they fail to find any midi ports (if they had been provided they would be loaded and started at runtime).

**Comment by meanwhile0** [comment]
I've compiled alsa-lib from git along with Schism, and I can happily report I've now got access to the MIDI ports I was missing. Thanks for the help!

**Comment by mrpapersonic** [comment]
no problem! I've contacted the maintainer of the Arch package so hopefully it will be fixed soon :)

**Comment by mrpapersonic** [comment]
Closing since I brought it up with the maintainers @ arch linux gitlab. See downstream issue: https://gitlab.archlinux.org/archlinux/packaging/packages/schismtracker/-/issues/1
