### ISSUE TITLE
Resize sample UX improvement

### ISSUE THREAD

**Issue by skope2v** [schismtracker/schismtracker#561]
Hi! I have a feature request regarding the resize sample (effectively resample) functions (Alt-E and Alt-F). As an alternative to only achieving this by entering the target file size (New Length), an additional input box either below or above New Length where you could enter the desired target sample rate (New Rate?) instead would be a little more user friendly. I could see modifying one would affect the other where if you have a sample at 44100hz and 10000 length, modifying rate to 22050 would show 5000 in the length box or vice versa.

I really don't like having to whip out a calculator everytime I wanna downsample somthing to a specific rate. (:

**Comment by mrpapersonic** [comment]
Yeah I agree, that would definitely be an improvement.

Maybe this could be implemented by adding an extra key modifier onto the normal resize sample keybinds (i.e. `Alt-Shift-E` and `Alt-Shift-F`) so that they're easy to remember and adapt to?

**Comment by skope2v** [comment]
Yes that's an even better way to do it, and feels more true to the "IT way". (:
