### ISSUE TITLE
Lxx does Gxx D00 instead of G00 Dxx

### ISSUE THREAD

**Issue by digistorm79** [schismtracker/schismtracker#564]
As in the title, the Lxx command does not set the volume slide while continuing the previous portamento with G00, but it sets the portamento speed and continues the previous volume slide with D00. I verified it with one of my own songs that I know very well (that is how I spotted it).

**Comment by mrpapersonic** [comment]
Can you attach the module?

**Comment by digistorm79** [comment]
It is a bit cumbersome maybe for you, but it is this module. Pattern 39 - 45, first channel. The difference is subtle maybe if it's not your own song, but you can make it very obvious by changing the effect command on row 002, 018 and 050 from L0B to L01. This should change the volume slide (G00 D01) but it changes the portamento speed (G01 D00). This makes the melody completely out of tune because G01 is too slow to reach the requested notes compared to G20. Hope this helps 😊. Of course, real Impulse Tracker does it right (which I checked on real hardware).
[CXPRESS.IT.zip](https://github.com/user-attachments/files/18131192/CXPRESS.IT.zip)

**Comment by mrpapersonic** [comment]
Weird, this worked in 20240809. I assume 223e327d9448561931b8cac8a55180286b17276c caused this...
