### ISSUE TITLE
Effect command S7C is not working

### ISSUE THREAD

**Issue by digistorm79** [schismtracker/schismtracker#568]
Effect command S7C should enable the pitch envelope. I tested the latest version (20241021) and the version that has the Lxx command working (20240809) and both do not execute the S7C command. I tested the opposite command (S7B - turn pitch envelope off) and that DOES work.
I chopped up the song that alerted me to this bug (it is quite big otherwise) and have attached it.
[S7C bug.it.zip](https://github.com/user-attachments/files/18152000/S7C.bug.it.zip)
On row 32 it should approach that note from below, quite obviously. In the mentioned versions it plays the pitch flat.

**Comment by mrpapersonic** [comment]
Pitch envelopes in general actually look to have been a bit broken after the fix for s77.it was pushed a year ago (granted, they were already broken, but still).

**Comment by mrpapersonic** [comment]
Fixed with c0e45f94f52bcafc7c1e75b11afefdd207a35794
