### ISSUE TITLE
can't open the tracker in mac os 10.4.11 (powerbook g4 12")

### ISSUE THREAD

**Issue by byChillout** [schismtracker/schismtracker#569]
I tried all the binaries but the app crashes immediatly, any advice or is just not compatible with that system? 

Thanks you :)

**Comment by mrpapersonic** [comment]
weird, the binary was working for me under Leopard and Panther. not sure if tiger has something special. I'll look into this.

**Comment by mrpapersonic** [comment]
OK, the binary for the latest release (20241021) only supports Leopard. However, the build was later altered to make the binaries work on Panther as well, but it seems an old bug crept back in regarding audio device selection.

**Comment by byChillout** [comment]
Thanks you so much for the response, and sorry for my English, I'm not native. Otherwise I will keep checking the post.

**Comment by mrpapersonic** [comment]
Ok, I got the binary working on my DLSD powerbook g4, but I uncovered another critical bug in the process at #572...
