### ISSUE TITLE
MultiTracker speed/tempo effect.

### ISSUE THREAD

**Issue by AliceLR** [schismtracker/schismtracker#570]
MTM has an unsolvable problem for tracker replayers, which is that half of MTMs with high `Fxx` values expect to be played with MultiTracker `Fxx` semantics and the other half expect to be played with Dual Module Player `Fxx` semantics. As there is minimal fingerprinting in MTM modules, it is impossible to tell which way to play MTMs unless there are blatant tells which users are not guaranteed to put in their modules.

Specifically:
* In MultiTracker, `Fxx` with a value less than `20h` sets the speed AND resets the tempo to 125. `Fxx` with a value of `20h` or greater sets the tempo AND resets the speed to 6. MTMs that rely on this will NOT play properly in any replayer that doesn't attempt to support it, which was most of them until a couple years ago.
* In Dual Module Player, `Fxx` behaves like it does in every other format. MTMs that rely on setting *both speeds and tempos* will not play properly in MultiTracker. This behavior was not intended by MultiTracker and is not indicated anywhere in the module.

Whichever one you choose, everyone loses, because it's easy to make a module that relies on one behavior that looks like it relies on the other. Please do not encourage the further use of this format by supporting saving with it, or at least inject some sort of explicit fingerprinting so we can detect Schism MTMs.

libxmp issue that prompted libxmp and OpenMPT to attempt detection, including a breakdown of the affected modules I could find: https://github.com/libxmp/libxmp/issues/607
libxmp pull request for attempted detection: https://github.com/libxmp/libxmp/pull/610 https://github.com/libxmp/libxmp/commit/487ec7b20ff998be52958050fae51e43a095ac2b

**Comment by sagamusix** [comment]
In addition to what I wrote on IRC: Reading a format is one thing. But writing a format, especially an obscure one like MTM, adds *a lot* of responsibility. This is why I keep saying no when someone wants OpenMPT to be able to save in any of the formats it can load beyond the ones it already supports.
Unlike formats dedicated for interchange (such as WAV or VGM), few tracker formats are designed with interchange in mind, and at this point I would say that unless a program already has perfect playback capabilities (e.g. through reverse-engineering the original playback code), it's not a good idea to add file export support for it. Schism's IT-centric engine is probably not up for this task when it comes to MTM. The only way I could see this fly is by removing support for saving any effects beyond those that have been carefully confirmed to work exactly the same like in MultiTracker, which would probably not make the feature very useful.

So, please please please - consider dropping the reintroduced MTM saving code again. It just makes every tracker/library developer's life harder, and doesn't serve a concrete purpose as far as I can tell.
