### ISSUE TITLE
CI stuff broken

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#58]
Builds are failing for reasons unrelated to code changes.

**Comment by jangler** [comment]
#60 fixed Travis (I think), but AppVeyor 32-bit still needs to be addressed.

**Comment by asbjornu** [comment]
I'm suspecting that AppVeyor is failing because the worker VM's are now shipped with 32-bit MSYS2  out of the box. I'm investigating the issue here: https://github.com/appveyor/ci/issues/733#issuecomment-260139198.

**Comment by asbjornu** [comment]
My suspicion was wrong, so I've filed appveyor/ci#1170 that will hopefully get a quick resolution.

**Comment by asbjornu** [comment]
I submitted #62 that fixes the problem.
