### ISSUE TITLE
Schismtracker can't read my config in $HOME/.schism/config and spits out invalid encoded filenames in the working directory instead.

### ISSUE THREAD

**Issue by KynikossDragonn** [schismtracker/schismtracker#581]
I don't know what to make of the following:
![Screenshot_2024-12-24_01-33-44](https://github.com/user-attachments/assets/8aa00555-ae72-4469-bb26-c981142ea7d3)

I built using the latest snapshot which as of writing is: https://github.com/schismtracker/schismtracker/commit/5df9a50e1508e94c40d5a7a4888c8f460a31d925

I noticed unlike the last time I built this several months ago I suddenly need libutf8proc installed which I had not previously had installed under Void Linux. Maybe it's related to this?

I built using: `../configure --disable-debug --disable-profiling --without-sdl12 && make -j9`

I have `LANG=en_US.UTF-8` in my environment. My kernel version is 6.6.67_1 and the libutf8proc library package on Void Linux is version 2.9.0_1, GCC is version 13.2.0 currently on Void Linux as well.

**Comment by mrpapersonic** [comment]
I've been replicating this as well, but I'm not entirely sure what's causing it.

**Comment by mrpapersonic** [comment]
note that I think this is likely a problem with the diskwriter. For me it was producing those odd files when I would save songs (as they were all just IT files)

**Comment by mrpapersonic** [comment]
Aha! I was able to reproduce it; it only happens when creating backup files (which makes sense, since I'd hacked around that code a bit)
