### ISSUE TITLE
Qxx behaviour when sample has ended

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#6]
In Impulse Tracker (and OpenMPT), Qxx only retriggers a sample if the sample is still playing. It doesn't restart a sample that has already ended.

[QXXTEST.zip](https://github.com/jangler/schismtracker/files/263627/QXXTEST.zip)

The first note (row 0) should retrigger as usual, because the sample hasn't yet ended by tick 4.

The second note (row 16) should just play once (three octaves up), because at this pitch the sample is already ended by tick 4. In Schism Tracker, this retriggers, and sounds like a three-octaves-up version of the first note.

The third note (row 32) should also just play once, because the sample has ended by row 36. In Schism Tracker, this plays once on row 32, and twice more on row 36.

Arguably the Schism behaviour is more useful, but it's better to be compatible (to get the current behaviour, put a loop of silence at the end of any Qxx'd samples).

**Comment by jangler** [comment]
That's interesting; [the retrigger "player abuse test"](https://github.com/jangler/schismtracker/wiki/Player-abuse-tests#retrigger) mentions this behavior but doesn't actually test it. We should either revise that test to include this case or create another test for it.
