### ISSUE TITLE
Info page pattern has different row center when compared to the original IT

### ISSUE THREAD

**Issue by Pigu-A** [schismtracker/schismtracker#63]
This came into my attention when I was testing my IT tracker art on Schism:
![it](https://cloud.githubusercontent.com/assets/7795387/20455998/9d4b3da6-ae9c-11e6-9c56-ff6d46ba8c26.png)
![shi](https://cloud.githubusercontent.com/assets/7795387/20455984/b7584f00-ae9b-11e6-9ce1-a0c58b648287.png)

**Comment by 0x5742** [comment]
Oh wow, this is a bug of the "tiny detail" sort that even *I* never thought about. Good job, you get a gold star. :star:

**Comment by jangler** [comment]
Sorry I took so long to change roughly one line of code! :P
