### ISSUE TITLE
"ALSA: Resource temporarily unavailable" when selecting first MIDI port on a device

### ISSUE THREAD

**Issue by porta2note** [schismtracker/schismtracker#64]
In the MIDI configuration screen. When I go down the list of devices, I can only activate the second or later instance of each device. I.e. on my firewire interface with two MIDI out ports I can only activate the second port, the first one stays locked to "disabled." Using a simple 1-port USB dongle I can't enable it at all, it's stuck on "disabled" and nothing can be done. Pressing spacebar to activate the port generates an "ALSA: Resource temporarily unavailable" error in the message console.

More details & screenshot for explanation here (scroll down) :
http://chipmusic.org/forums/topic/18439/what-happened-to-schismtrackerorg/page/6/

The issue occurs for me on Fedora 21, Mint 17, Mint 18, and AVLinux 2016 (Debian), including on a freshly compiled version with no preexisting config file. I'm using the latest 2016.11.14 snapshot, compiled by myself, and it occurs on all of them. I built the exact same source tarball on my Mac (OSX 10.8) and it doesn't happen there. It was also present at least as far back as version 2016.07.31.

Happens regardless of whether the ALSA or Pulse driver is being used, but does NOT happen on the "dummy" driver. I haven't tried OSS yet.

Anyone have an idea how to fix this? I have a live act coming up early in January and I really want to incorporate Schism into it.

**Comment by jangler** [comment]
I know very little about this, but here are some preliminary thoughts while I look into it:

Just as a sanity check, what's the output of `aplaymidi -l` and `aconnect -l` for you while Schism is running?

PulseAudio still uses ALSA's MIDI interface, so the ALSA message regardless of which driver you're using is normal.

There's a compile flag called `-DUSE_DLTRACK_ALSA` which is relevant to the ALSA MIDI implementation; have a look at the block comment in [sys/alsa/midi-alsa.c](https://github.com/schismtracker/schismtracker/blob/master/sys/alsa/midi-alsa.c) for more info. You could try editing your Makefile to do whatever it doesn't currently do in that regard.

**Comment by jangler** [comment]
Never mind about `USE_DLTRiCK_ALSA`; there's an explicit compiler directive to exit with a useless fatal error if that macro isn't defined.

**Comment by jangler** [comment]
Also, it's indeed weird that the OSS MIDI devices show up on your MIDI screen; they don't show up on mine. Do those files actually exist in your filesystem?

**Comment by porta2note** [comment]
Okay, weird. Just tested on my Fedora workstation. After a fresh boot there was no /dev/midi* and no OSS device appeared in Schism. With nothing connected the only ports I had were 14:0 MIDI Through and 5 Multicast/IP ports, all of which were fully selectable.

When I **plugged in a USB MIDI interface, /dev/midi2 appeared**, both in the filesystem and Schism. "24:0 USB to MIDI adapter" also appeared in Schism.
![dev_midi](https://cloud.githubusercontent.com/assets/24555710/21165722/13813b9e-c156-11e6-8863-d735c5d60da4.png)

Selecting 24:0 exhibits the "Resource temporarily unavailable" bug. /dev/midi2 can be configured as an input or output device but when I go make a MIDI instrument with it, Schism crashes with `schismtracker: ../schism/midi-core.c:772: midi_send_buffer: Assertion `((unsigned)pos) < ((unsigned)qlen)' failed.` as soon as I select the output channel.

It looks like ALSA or Pulse might be wrapping the MIDI port to a virtual OSS /dev/midi device and reserving it? I don't have the ALSA-OSS translation layer installed as far as I know.

Note: the AVLinux machine I tried has ALSA+JACK but does not have Pulse - same issue. I am currently installing FreeBSD on it so I can try it with a pure OSS setup.

**Comment by porta2note** [comment]
The USB to MIDI adapter works fine in Renoise with its ALSA driver immediately after closing Schism (and with /dev/midi2 still present.) It can be selected and outputs data as it should.

**Comment by porta2note** [comment]
> Just as a sanity check, what's the output of aplaymidi -l and aconnect -l for you while Schism is running?

![aplay](https://cloud.githubusercontent.com/assets/24555710/21168251/684d8bd0-c167-11e6-9332-20a6e4372fac.png)

Same machine, only one MIDI device connected. I can try it on my workstation w/multiple devices when I get home...

**Comment by porta2note** [comment]
Ok, sorry for the post spam. Apparently providing OSS /dev/midi devices is standard ALSA behavior (https://linuxmusicians.com/viewtopic.php?f=27&p=76617&sid=86faa9a21b6a3b4757cc2ce46119e58d#p76617) and not really configurable.

I'm *completely* wild guessing here, but is it possible Schism starts up, sees /dev/midix, figures OSS is installed and locks it for exclusive use, not realizing that ALSA is actually using that port? And then when the user goes to select the "actual" port (e.g. 24:0 in my screenshot) ALSA thinks it's in use?

**Comment by jangler** [comment]
Alright, thanks for the info. I should be able to look at this tomorrow and see if I can reproduce / find the source of the problem.

Edit: my MIDI config is screwed up in the first place, so I'll have to fix that first…

**Comment by jangler** [comment]
I actually can't reproduce this using either software or hardware MIDI clients. I can select the ports as is appropriate, and the /dev/midi3 that appears in my filesystem isn't on the clients list.

**Comment by jangler** [comment]
Also, I think the crash is what #51 is about.

**Comment by porta2note** [comment]
That's weird - what distro are you running & with what MIDI device? It occurs on my netbook which got a completely fresh install of AVLinux (Debian) and all my Mint & Fedora machines so I don't think it's a configuration issue. I'll try some live CDs and see if I can figure out exactly which distros are problematic.

BTW for MIDI interfaces: have tried a Roland UM-One, a generic Ebay USB-MIDI, a firewire Digidesign Digi 002, and SB Audigy 2 - same result.

**Comment by porta2note** [comment]
Is it possible/easy to completely disable ALSA/Pulse or OSS support at compile time? (I.e make an ALSA-only build & an OSS-only build?)

**Comment by jangler** [comment]
Arch Linux, kernel version 4.8.8, alsa-lib version 1.1.2. MIDI devices were FluidSynth and E-MU Xmidi 1x1 tab.

I would look at the USE_OSS and USE_ALSA flags in Makefile.am for disabling support for one audio driver or the other.

**Comment by porta2note** [comment]
I can confirm the same behavior occurs on Linux Mint 18 straight off the LiveCD (and probably most other Ubuntu/Debian-based distros, as well as Fedora as mentioned.) I suspect this is a case of Arch doing something different, or "Arch is Arch" as they say. Do you mind trying a liveCD of one of the more popular distros on your hardware and see if it occurs?

I'll try making up some OSS- & ALSA-only builds and see what happens.

(I can't seem to get the FreeBSD version I built to work but that is another issue entirely and *definitely* related to my unfamiliarity with BSD.)

**Comment by jangler** [comment]
First I'm going to try with the VMs I already have set up, but yes. (Probably won't get to it for another few days, though.)

**Comment by laamaa** [comment]
> I'll try making up some OSS- & ALSA-only builds and see what happens.

I had the same problem on my Thinkpad with Lubuntu 19.10, disabling -DUSE_OSS in makefile seems to fix the problem

**Comment by laamaa** [comment]
I wonder if this would be a suitable way around the problem? Seems to work on my laptop at least. https://github.com/laamaa/schismtracker/blob/4ecb01b4292eba57283750539530ddeafe024dfd/schism/midi-core.c#L320-L328

I also tried looking at the OSS midi code and it indeed opens all /dev/midi* handles as @porta2note suspected, but changing that behavior is something beyond my amateur programmer skills...

**Comment by laamaa** [comment]
I submitted PR #257 for this, it has worked well at least for me with a bunch of different Linux setups
