### ISSUE TITLE
Buggy mouse cursor when selecting track view 2/3

### ISSUE THREAD

**Issue by polyzium** [schismtracker/schismtracker#66]
The screenshot below describes it
![default](https://cloud.githubusercontent.com/assets/22579935/21460683/0c0a8be6-c95c-11e6-89e3-52b2bc213b70.png)
Original IT doesn't have this issue
![default](https://cloud.githubusercontent.com/assets/22579935/21460681/04ec5efc-c95c-11e6-91df-13d864ff31f4.png)

**Comment by 0x5742** [comment]
This might be dependent on video driver or the like; I recall IT tripping all over the mouse cursor on half-size text on my old PC.

**Comment by HybridDog** [comment]
Where can l find the track view?
