### ISSUE TITLE
Note-off + instrument behaviour is incorrect

### ISSUE THREAD

**Issue by iamgreaser** [schismtracker/schismtracker#7]
This has been wrong for years and Modplug users have been making wrong IT files for years because of this (I had to fix Janky the Ghost's Funk Parade because of this Modplug bug). I've forgotten the exact behaviour of this, sadly. Something like this:

Modplug version: Ignore instrument and just do a note-off.

Real version:
- Reset the volume to the sample volume of the target sample.
- If there is a sample default pan, reset the pan to that too. (Not tested with instrument pan but it's likely that fires too.)
- Switch to the new instrument + sample but KEEP PLAYING THE CURRENT SAMPLE.
- If "Old Effects", switch to the new instrument envelopes and run them from the start.

If there really aren't any legitimate cases as to why the hell you would use a note-off with an instrument number then the easiest fix is to strip them on load, but that idea makes me feel bad inside. It would be more sensible to make it spew out a horrible sound, although you'd probably want to make sure that b-knox never touches it, otherwise he'll abuse the living shit out of it.

At this stage, libit216 plays this "as intended" (read: wrong) so either there's a mistake in my transcription or my sound driver isn't accurate. Seeing as both SB16 and GUS seem to behave in the same way here, and there are still a few songs that break in libit216, I'll need to find out where the C code and the reference assembly code diverges. It's probably buried in the `goto` soup somewhere.

**Comment by jangler** [comment]
Can you provide a test case module for this? I tried to make one based on your description, but IT v2.14 and Schism 20160513 played it back identically.

In any case, we've been in the habit of fixing "why the hell would you do this" playback bugs as long as they don't require a ton of code restructuring. I'm _definitely_ not in favor of stripping anything on load.

**Comment by ghost** [comment]
Stripping on load gets a no from me, and spewing out a horrible sound seems even worse. Best would be to fix it so it's compatible with IT.

[Test case (?)](https://github.com/jangler/schismtracker/files/265069/issue7.zip) - I'm not exactly sure what I'm supposed to be testing here, so bear with me...

 it214 does seem to set volume to the volume of the target sample, doesn't seem to affect pan, though, both schism and IT keep playing the current sample. 

Schism isn't resetting the volume correctly or doing the new instrument envelopes if "Old Effects" is on. Not sure what else is different.

**Comment by iamgreaser** [comment]
That should be a good enough test case, just remember to enable/disable "Old Effects" while testing.

**Comment by ghost** [comment]
Sample 2 should probably be different to sample 1, rather than just a different pitch, to completely clarify what's going on.

**Comment by sagamusix** [comment]
> Best would be to fix it so it's compatible with IT.

Just a thought - OpenMPT has compatibility flags for things it (and other trackers) did wrong in the past, to keep playing them wrong (or right, depending on how you see it) for existing tracks made with older versions, but uses IT's behaviour by default for new files. It might make sense to introduce something similar for Schism, especially now that e.g. e7b1461fe751554309fd403713c2a1ef322105ca will definitly break some old modules.

**Comment by jangler** [comment]
I'm exhausted from looking at this right now, but `csf_instrument_change()` is currently not called in `csf_process_effects()` in this case, and even if it _were_ called, it wouldn't have the correct logic.

**Comment by sagamusix** [comment]
Look out for kITInstrWithNoteOff in OpenMPT's Snd_fx.cpp - I have fixed this in OpenMPT not too long ago.

**Comment by PlasticCog** [comment]
I recall that the instrument note-off command in IT would trigger the Release part of the ADSR envelope, so the note would fade out from the sustain part, therefore you could make more realistic piano and guitar sort of sounds. Modplug and other players that ignore IT instrument specs have annoyed the crap out of me for over 10 years :D

**Comment by jangler** [comment]
Well, luckily this is a very specific edge case—normal note-offs are handled just fine, AFAIK :)

And strictly speaking, a note-off just disables the sustain loop (and only the sustain loop) of an instrument envelope. The concept of ADSR doesn't really apply to IT envelopes, which can have both an "envelope loop" and "sustain loop" that each operate on an arbitrary number of nodes.

**Comment by jangler** [comment]
Incremental progress. The relevant OpenMPT revision is [here](https://source.openmpt.org/browse/openmpt?op=comp&compare[]=%2F@5828&compare[]=%2F@5829).

**Comment by langel** [comment]
Yes, I think a proper easter egg would be to have an embedded airhorn sample go off anytime someone puts an instrument number against a note-off.  Make sure to use the old school dub airhorn and not the tweaker one the kids are into.  Thanks!

**Comment by algorev** [comment]
How's it going?

**Comment by jangler** [comment]
trying to find a good dub airhorn sample but no luck so far

**Comment by langel** [comment]
should I make a PR?

**Comment by alpharisc** [comment]
This is still happening, I was going to open a new case but there is also an issue with panning. The best way I can describe it is:

Default Pan ignored on Sample or Instrument when New Note Action is triggered, and panning position returns to "Order List and Panning" default (e.g. if it is centre and you set the sample to have a default pan of LEFT, it will ignore that, and go to centre, impulse tracker and Open MPT do not behave in this manner).
[PAN_BUG.zip](https://github.com/schismtracker/schismtracker/files/10509108/PAN_BUG.zip)

I have attached the file, just solo channel 1, or 2 to hear what I am talking about, the echo notes pan back to the centre (channel default).

**Comment by mrpapersonic** [comment]
I believe 85b44b7fad163edb1b3e877d0d643f5dec4f6deb solves this

**Comment by sagamusix** [comment]
`NoteOffInstr.it` is something different (instrument number *after* a note cut), this issue here is about an instrument number *next to* a note-off. As mentioned above, the `kITInstrWithNoteOff ` compatibility flag in OpenMPT fixes this.

**Comment by mrpapersonic** [comment]
Ah, sorry, I was just going through old player issues and linking them to my own commits... 19a43e0e020a883b00ae97ddebc7189e06ec4774 & ef8881c7501ef2bf40d6602e1d3cdf484dbfb210 should've solved this then. The previously posted `issue7.it` plays as it does in MPT now as well.

**Comment by mrpapersonic** [comment]
yep, this was fixed by those two commits (both the regular & Old Effects behavior). Closing this now
