### ISSUE TITLE
Config option for note off on key release with playback tracing enabled

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#70]
Raised by joemaro in IRC. Expected behavior was for playback tracing (Ctrl+F) to change the way note entry works in the pattern editor so that it would be like MIDI in that a note off would be placed when the key is released.

The current behavior is that the pattern edit keys work as usual while tracing is enabled, with the only difference being that the cursor follows playback. This is also sensible, so a config option would be the way to handle this.

**Comment by 0x5742** [comment]
Isn't this already implemented as `keyjazz_noteoff` in the configuration?

**Comment by 0x5742** [comment]
..... wait, you're talking about actually *writing* the `===`, not just triggering a note off. Derr.

Should be easy enough with another option, anyhow - `keyjazz_write_noteoff` perhaps. Then upon noteoff write the note off into current row (if there's a note already, maybe current+1? how should that work?)

**Comment by jangler** [comment]
~~Oh yep, you're right, thanks. Wish I had any contact info for them now :P~~

Edit: Cross-post with Storlek.

**Comment by 0x5742** [comment]
and chaos ensued

**Comment by jangler** [comment]
Writing the note off into the next row if there's already a note in the current row sounds like the most sensible option. Wouldn't work 100% if you're overwriting stuff or at the end of the pattern, but it seems good enough. Saga mentioned that OpenMPT has this config option, so I might look at how OpenMPT handles it.

**Comment by 0x5742** [comment]
Hmm. Now that I'm looking at this: does that `#if 0`'d code starting on line 3164 basically do the sameish thing except different? (I actually don't remember.) Might just rip that chunk out, no sense having it there. If need be we can find it in the version history :)

**Comment by jangler** [comment]
Oh yeah, I noticed that and then forgot about it. I will indeed rip it out. (But if only there were a more helpful comment than `/* ? */` so that we knew *why* it was disabled…)

**Comment by 0x5742** [comment]
lol, yeah.
