### ISSUE TITLE
Muting/unmuting channels

### ISSUE THREAD

**Issue by Kn0p** [schismtracker/schismtracker#74]
I've noticed that when I enter notes in a muted channel, that channel automatically gets unmuted and keeps playing along, even though visually it says it's still muted. Seems odd to me. Is this normal behavior? Sometimes I play "live" with IT/Schism, just let it loop a pattern and add stuff as I go, i.e. "[preparing" a rhythm on a muted track and unmuting it later on.

(I'm running build 20160913, win, 64 bit)

**Comment by jangler** [comment]
Definitely a bug IMO; IT doesn't do this.

**Comment by jangler** [comment]
Should be fixed in ece0a18. Maybe it's time to merge and draft a new release. Not going to close until someone else verifies the fix, though.

**Comment by jangler** [comment]
Or since it's been three weeks, maybe I will :P
