### ISSUE TITLE
osx: no automatic builds?

### ISSUE THREAD

**Issue by esaruoho** [schismtracker/schismtracker#76]
Just saw @jangler  release https://github.com/schismtracker/schismtracker/releases/tag/20170420 only to see that there's no OSX build? Is this liable to change?

**Comment by jangler** [comment]
Technically there *are* automatic OS X builds via Travis CI, but yeah, we still haven't figured out a non-ugly way of putting them somewhere (Travis doesn't archive anything by itself). We should probably just bite the bullet and do something ugly like `rcp` the binary somewhere in the build script.

**Comment by esaruoho** [comment]
how does computer OSX new build download please?

**Comment by jangler** [comment]
There are raw Mach-O (OS X) binaries for the "deploy-test" tags on the https://github.com/schismtracker/schismtracker/releases page. We haven't implemented packing that into an .app bundle yet, but that's on my to-do list for this week.

**Comment by esaruoho** [comment]
@jangler does the #132 PR somehow help with the automatic creation of fully functioning macOS builds?

**Comment by jangler** [comment]
Please don't comment on closed issues marked as duplicate. You already commented on #125, which is the open issue regarding .app bundles, and #128 and #131, which are open issues regarding macOS builds that aren't "fully functioning", if that's what you mean.
