### ISSUE TITLE
Precompiled Win32 version won't launch

### ISSUE THREAD

**Issue by SparroHawc** [schismtracker/schismtracker#79]
Upon attempting to launch, an error message pops up stating that the libwinpthreads-1.dll file is missing.  Attempting to copy the library from X86-64 MinGW into the same directory as Schism Tracker changes the error message to "The application was unable to start correctly (0xc000007b).

**Comment by SparroHawc** [comment]
It seems the second error might be due to my audio driver crashing on me.  The dependency issue is still valid, but the 'unable to start correctly' error may not be.

**Comment by ghost** [comment]
Good spot, sorry about that SparroHawc. It should be the 32-bit dll from msys2. Anyway, I've emailed jangler with a zip including this file so hopefully we can get that uploaded and the windows build will work for you again. 

Thank you!

**Comment by jangler** [comment]
I updated the win32 zip in the latest release. Hopefully it works now!

**Comment by sagamusix** [comment]
Just for future reference, error 0xc000007b means that binaries of varying bitness are mixed; this can happen by putting a DLL of wrong bitness into the same folder (as happened in the initial post) or by embedding an incorrect manifest (which does not really apply to SchismTracker).

**Comment by jangler** [comment]
Looks like it's fixed?
