### ISSUE TITLE
Scrolling in "Load Instrument" screen doesn't work

### ISSUE THREAD

**Issue by zoikkis** [schismtracker/schismtracker#86]
In all the other Schism Tracker screens, when you keep arrow up/down pressed down, cursor starts soon scrolling automatically as it should, including Load Sample screen. However when in Load Instrument screen, pressing and keeping arrow button down doesn't do anything. Only when you raise the button it moves one increment but doesn't start scrolling at any point.

I've noticed the same behavior with several computers running different windows versions. Is there a reason behind this or is it a bug?

**Comment by jangler** [comment]
Hm, I can't reproduce this.

**Comment by vcaputo** [comment]
I can, by simply going to the instrument library page (Ctrl-F4), up/down arrows do nothing until released.

**Comment by vcaputo** [comment]
https://github.com/schismtracker/schismtracker/pull/87 seems to fix it, unsure if it breaks anything else, but at a glance I don't see why it would - but this code as-is kind of doesn't make sense, maybe it's a copy and paste from another listing which then got hacked up a bit leaving this oddity?

**Comment by jangler** [comment]
Oh, my bad; I misread and was looking at the Instrument List screen instead. Yeah, I can reproduce it.

**Comment by vcaputo** [comment]
@zoikkis in case it's unclear, this has been fixed in master and will be in the next release - thanks for the bug report!
