### ISSUE TITLE
Maintainership (Storlek contact)

### ISSUE THREAD

**Issue by uucidl** [schismtracker/schismtracker#9]
https://twitter.com/SwedishForSize/status/731863220374249473

Twitter isn't really great for archiving and reference. Short said, after a few hours after I broadcasted this repository on twitter, Storlek reacted saying they haven't been contacted and felt bad about how the fork happened.

Please check the twitter thread.

Some other links:
http://chipmusic.org/forums/topic/18439/what-happened-to-schismtrackerorg/

**Comment by jangler** [comment]
Storlek has been contacting me on IRC today, so I'm aware of the Twitter thread, and (as you probably know), that cm.o thread was the impetus for this fork. We'll discuss how we want to collectively move forward on this project.

**Comment by jangler** [comment]
Resolved. We created an organization (https://github.com/schismtracker) with Storlek and the rest of us, and transferred ownership of the repository to that organization.

**Comment by uucidl** [comment]
👍

**Comment by asbjornu** [comment]
Perfect!
