### ISSUE TITLE
Help with compiling 32-bit schism

### ISSUE THREAD

**Issue by zoikkis** [schismtracker/schismtracker#99]
I'm trying to make a 32-bit build of schismtracker with windows 8.1 and have done everything by instructions. After all the previous steps, I'm now inside Msys2 mingw 32bit shell, having created directory called "build" into the root directory where schismtracker source is and moved into that directory.

"jugger@HAL9000 MINGW32 ~/schismtracker/build"

Now when I write "../configure" it says "no such file directory"
If I write "../configure.ac" it says the following:
../configure.ac: line 1: dnl: no such command
../configure.ac: line 3: dnl: no such command
../configure.ac: line 4: error near unexpected keyword ”(”
../configure.ac: line 4: `dnl copyright (c) 2003-2005 Storlek <storlek@rigelseven.com>'

then I write "make" and it gives an empty line.

after that I write "../schismtracker &" and it tells the following

[1] 2884

jugger@HAL9000 MINGW32 ~/schismtracker/build
$ bash: ../schismtracker: No such file or directory

I put the schismtracker source folder into C:\msys32\home\[USERNAME]\ as I didn't find a way to navigate into other folders on my computer, but I guess that doesn't matter.

Any idea what's the problem here? All the previous steps seemed to go OK, no errors or anything

**Comment by vcaputo** [comment]
It sounds like you skipped the `autoreconf -i` step.

**Comment by zoikkis** [comment]
I did autoreconf -i , press enter, then it calculated for couple seconds and then empty line so it seemed to go OK

**Comment by zoikkis** [comment]
I have following files and folders in the schismtracker folder:
build
docs
fmt
font
helptext
icons
include
player
schism
scripts
sys
.gitignore
.travis.yml
appveyor.yml
AUTHORS
configure.ac
COPYING
INSTALL
Makefile.am
NEWS
README.md

**Comment by zoikkis** [comment]
should that "autoreconf -i" create a new file so that command "../configure" would actually work, or is it normal to get an empty line after that command?

**Comment by jangler** [comment]
Yeah, after running `autoreconf -i` successfully you should additionally have the files:

- aclocal.m4
- compile
- configure
- depcomp
- install.sh
- Makefile.in
- missing

… or at the very least the 'configure' script.

**Comment by zoikkis** [comment]
thanks! Looks like Comodo was blocking some of the executables, so trying again :)

**Comment by zoikkis** [comment]
I got it working. Compiled a version with sndmix.c-> VOLUMERAMPLEN value considerably increased and got rid of almost all crackles and pops. Thanks for your kind help!

**Comment by jangler** [comment]
Awesome :) and no problem. Going to reference #95 as I close this, for reference when tackling that issue.
